import type { AppearanceData } from '../types';

export const APPEARANCES = [
  {id:'skin-alabaster',label:'Alabaster',category:'skin'},
  {id:'skin-amber',label:'Amber',category:'skin'},
  {id:'skin-bronze',label:'Bronze',category:'skin'},
  {id:'skin-copper',label:'Copper',category:'skin'},
  {id:'skin-deep-brown',label:'Deep brown',category:'skin'},
  {id:'skin-ebony',label:'Ebony',category:'skin'},
  {id:'skin-fair',label:'Fair',category:'skin'},
  {id:'skin-golden',label:'Golden',category:'skin'},
  {id:'skin-gray',label:'Gray',category:'skin'},
  {id:'skin-olive',label:'Olive',category:'skin'},
  {id:'skin-pale-blue',label:'Pale blue',category:'skin'},
  {id:'skin-ruddy',label:'Ruddy',category:'skin'},
  {id:'skin-tan',label:'Tan',category:'skin'},
  {id:'skin-umber',label:'Umber',category:'skin'},
  {id:'skin-verdant',label:'Verdant',category:'skin'},
  {id:'eyes-almond-shaped',label:'Almond-shaped',category:'eyes'},
  {id:'eyes-deep-set',label:'Deep-set',category:'eyes'},
  {id:'eyes-downturned',label:'Downturned',category:'eyes'},
  {id:'eyes-hooded',label:'Hooded',category:'eyes'},
  {id:'eyes-large',label:'Large',category:'eyes'},
  {id:'eyes-narrow',label:'Narrow',category:'eyes'},
  {id:'eyes-round',label:'Round',category:'eyes'},
  {id:'eyes-upturned',label:'Upturned',category:'eyes'},
  {id:'eyes-wide-set',label:'Wide-set',category:'eyes'},
  {id:'eyes-watchful',label:'Watchful',category:'eyes'},
  {id:'hair-bald',label:'Bald',category:'hair'},
  {id:'hair-braided',label:'Braided',category:'hair'},
  {id:'hair-coiled',label:'Coiled',category:'hair'},
  {id:'hair-cropped',label:'Cropped',category:'hair'},
  {id:'hair-curly',label:'Curly',category:'hair'},
  {id:'hair-dreadlocked',label:'Dreadlocked',category:'hair'},
  {id:'hair-flowing',label:'Flowing',category:'hair'},
  {id:'hair-knot-tied',label:'Knot-tied',category:'hair'},
  {id:'hair-layered',label:'Layered',category:'hair'},
  {id:'hair-shaved',label:'Shaved',category:'hair'},
  {id:'hair-straight',label:'Straight',category:'hair'},
  {id:'hair-tousled',label:'Tousled',category:'hair'},
  {id:'hair-wavy',label:'Wavy',category:'hair'},
  {id:'face-angular',label:'Angular',category:'face'},
  {id:'face-heart-shaped',label:'Heart-shaped',category:'face'},
  {id:'face-long',label:'Long',category:'face'},
  {id:'face-oval',label:'Oval',category:'face'},
  {id:'face-round',label:'Round',category:'face'},
  {id:'face-square',label:'Square',category:'face'},
  {id:'face-soft-featured',label:'Soft-featured',category:'face'},
  {id:'face-weathered',label:'Weathered',category:'face'},
  {id:'feature-burn-scar',label:'Burn scar',category:'feature'},
  {id:'feature-broken-nose',label:'Broken nose',category:'feature'},
  {id:'feature-clouded-eye',label:'Clouded eye',category:'feature'},
  {id:'feature-dimples',label:'Dimples',category:'feature'},
  {id:'feature-facial-tattoo',label:'Facial tattoo',category:'feature'},
  {id:'feature-freckles',label:'Freckles',category:'feature'},
  {id:'feature-gold-tooth',label:'Gold tooth',category:'feature'},
  {id:'feature-laugh-lines',label:'Laugh lines',category:'feature'},
  {id:'feature-pierced-brow',label:'Pierced brow',category:'feature'},
  {id:'feature-prominent-tusks',label:'Prominent tusks',category:'feature'},
  {id:'feature-ritual-scars',label:'Ritual scars',category:'feature'},
  {id:'feature-split-lip',label:'Split lip',category:'feature'},
  {id:'style-ceremonial',label:'Ceremonial',category:'style'},
  {id:'style-colorful',label:'Colorful',category:'style'},
  {id:'style-disheveled',label:'Disheveled',category:'style'},
  {id:'style-formal',label:'Formal',category:'style'},
  {id:'style-layered',label:'Layered',category:'style'},
  {id:'style-military',label:'Military',category:'style'},
  {id:'style-practical',label:'Practical',category:'style'},
  {id:'style-religious',label:'Religious',category:'style'},
  {id:'style-travel-worn',label:'Travel-worn',category:'style'},
  {id:'style-understated',label:'Understated',category:'style'},
  {id:'movement-bounding',label:'Bounding',category:'movement'},
  {id:'movement-deliberate',label:'Deliberate',category:'movement'},
  {id:'movement-gliding',label:'Gliding',category:'movement'},
  {id:'movement-heavy-footed',label:'Heavy-footed',category:'movement'},
  {id:'movement-limping',label:'Limping',category:'movement'},
  {id:'movement-measured',label:'Measured',category:'movement'},
  {id:'movement-nervous',label:'Nervous',category:'movement'},
  {id:'movement-quick',label:'Quick',category:'movement'},
  {id:'movement-silent',label:'Silent',category:'movement'},
  {id:'movement-swaying',label:'Swaying',category:'movement'},
] as const satisfies readonly AppearanceData[];
