import type { GoalData } from '../types';

export const GOALS = [
  {id:'good-protect-a-threatened-village-from-exploitation',description:'Protect a threatened village from exploitation',category:'good'},
  {id:'good-protect-displaced-families-from-exploitation',description:'Protect displaced families from exploitation',category:'good'},
  {id:'good-protect-an-innocent-minority-from-exploitation',description:'Protect an innocent minority from exploitation',category:'good'},
  {id:'good-restore-safety-to-a-threatened-village',description:'Restore safety to a threatened village',category:'good'},
  {id:'good-restore-safety-to-displaced-families',description:'Restore safety to displaced families',category:'good'},
  {id:'good-restore-safety-to-an-innocent-minority',description:'Restore safety to an innocent minority',category:'good'},
  {id:'good-secure-fair-treatment-for-a-threatened-village',description:'Secure fair treatment for a threatened village',category:'good'},
  {id:'good-secure-fair-treatment-for-displaced-families',description:'Secure fair treatment for displaced families',category:'good'},
  {id:'good-secure-fair-treatment-for-an-innocent-minority',description:'Secure fair treatment for an innocent minority',category:'good'},
  {id:'good-provide-food-and-shelter-for-a-threatened-village',description:'Provide food and shelter for a threatened village',category:'good'},
  {id:'good-provide-food-and-shelter-for-displaced-families',description:'Provide food and shelter for displaced families',category:'good'},
  {id:'good-provide-food-and-shelter-for-an-innocent-minority',description:'Provide food and shelter for an innocent minority',category:'good'},
  {id:'good-expose-those-harming-a-threatened-village',description:'Expose those harming a threatened village',category:'good'},
  {id:'good-expose-those-harming-displaced-families',description:'Expose those harming displaced families',category:'good'},
  {id:'good-expose-those-harming-an-innocent-minority',description:'Expose those harming an innocent minority',category:'good'},
  {id:'good-build-lasting-support-for-a-threatened-village',description:'Build lasting support for a threatened village',category:'good'},
  {id:'good-build-lasting-support-for-displaced-families',description:'Build lasting support for displaced families',category:'good'},
  {id:'good-build-lasting-support-for-an-innocent-minority',description:'Build lasting support for an innocent minority',category:'good'},
  {id:'good-defend-the-rights-of-a-threatened-village',description:'Defend the rights of a threatened village',category:'good'},
  {id:'good-defend-the-rights-of-displaced-families',description:'Defend the rights of displaced families',category:'good'},
  {id:'good-defend-the-rights-of-an-innocent-minority',description:'Defend the rights of an innocent minority',category:'good'},
  {id:'neutral-map-every-route-through-a-frontier-region',description:'Map every route through a frontier region',category:'neutral'},
  {id:'neutral-map-every-route-through-a-growing-city',description:'Map every route through a growing city',category:'neutral'},
  {id:'neutral-map-every-route-through-a-remote-island',description:'Map every route through a remote island',category:'neutral'},
  {id:'neutral-establish-reliable-contact-with-a-frontier-region',description:'Establish reliable contact with a frontier region',category:'neutral'},
  {id:'neutral-establish-reliable-contact-with-a-growing-city',description:'Establish reliable contact with a growing city',category:'neutral'},
  {id:'neutral-establish-reliable-contact-with-a-remote-island',description:'Establish reliable contact with a remote island',category:'neutral'},
  {id:'neutral-document-the-customs-of-a-frontier-region',description:'Document the customs of a frontier region',category:'neutral'},
  {id:'neutral-document-the-customs-of-a-growing-city',description:'Document the customs of a growing city',category:'neutral'},
  {id:'neutral-document-the-customs-of-a-remote-island',description:'Document the customs of a remote island',category:'neutral'},
  {id:'neutral-maintain-balance-around-a-frontier-region',description:'Maintain balance around a frontier region',category:'neutral'},
  {id:'neutral-maintain-balance-around-a-growing-city',description:'Maintain balance around a growing city',category:'neutral'},
  {id:'neutral-maintain-balance-around-a-remote-island',description:'Maintain balance around a remote island',category:'neutral'},
  {id:'neutral-negotiate-safe-passage-through-a-frontier-region',description:'Negotiate safe passage through a frontier region',category:'neutral'},
  {id:'neutral-negotiate-safe-passage-through-a-growing-city',description:'Negotiate safe passage through a growing city',category:'neutral'},
  {id:'neutral-negotiate-safe-passage-through-a-remote-island',description:'Negotiate safe passage through a remote island',category:'neutral'},
  {id:'neutral-create-an-accurate-census-of-a-frontier-region',description:'Create an accurate census of a frontier region',category:'neutral'},
  {id:'neutral-create-an-accurate-census-of-a-growing-city',description:'Create an accurate census of a growing city',category:'neutral'},
  {id:'neutral-create-an-accurate-census-of-a-remote-island',description:'Create an accurate census of a remote island',category:'neutral'},
  {id:'neutral-understand-recent-changes-in-a-frontier-region',description:'Understand recent changes in a frontier region',category:'neutral'},
  {id:'neutral-understand-recent-changes-in-a-growing-city',description:'Understand recent changes in a growing city',category:'neutral'},
  {id:'neutral-understand-recent-changes-in-a-remote-island',description:'Understand recent changes in a remote island',category:'neutral'},
  {id:'evil-seize-control-of-a-wealthy-district',description:'Seize control of a wealthy district',category:'evil'},
  {id:'evil-seize-control-of-a-border-kingdom',description:'Seize control of a border kingdom',category:'evil'},
  {id:'evil-seize-control-of-a-powerful-guild',description:'Seize control of a powerful guild',category:'evil'},
  {id:'evil-break-the-resistance-within-a-wealthy-district',description:'Break the resistance within a wealthy district',category:'evil'},
  {id:'evil-break-the-resistance-within-a-border-kingdom',description:'Break the resistance within a border kingdom',category:'evil'},
  {id:'evil-break-the-resistance-within-a-powerful-guild',description:'Break the resistance within a powerful guild',category:'evil'},
  {id:'evil-exploit-the-resources-of-a-wealthy-district',description:'Exploit the resources of a wealthy district',category:'evil'},
  {id:'evil-exploit-the-resources-of-a-border-kingdom',description:'Exploit the resources of a border kingdom',category:'evil'},
  {id:'evil-exploit-the-resources-of-a-powerful-guild',description:'Exploit the resources of a powerful guild',category:'evil'},
  {id:'evil-silence-every-witness-in-a-wealthy-district',description:'Silence every witness in a wealthy district',category:'evil'},
  {id:'evil-silence-every-witness-in-a-border-kingdom',description:'Silence every witness in a border kingdom',category:'evil'},
  {id:'evil-silence-every-witness-in-a-powerful-guild',description:'Silence every witness in a powerful guild',category:'evil'},
  {id:'evil-corrupt-the-leadership-of-a-wealthy-district',description:'Corrupt the leadership of a wealthy district',category:'evil'},
  {id:'evil-corrupt-the-leadership-of-a-border-kingdom',description:'Corrupt the leadership of a border kingdom',category:'evil'},
  {id:'evil-corrupt-the-leadership-of-a-powerful-guild',description:'Corrupt the leadership of a powerful guild',category:'evil'},
  {id:'evil-turn-rival-factions-against-a-wealthy-district',description:'Turn rival factions against a wealthy district',category:'evil'},
  {id:'evil-turn-rival-factions-against-a-border-kingdom',description:'Turn rival factions against a border kingdom',category:'evil'},
  {id:'evil-turn-rival-factions-against-a-powerful-guild',description:'Turn rival factions against a powerful guild',category:'evil'},
  {id:'evil-rule-through-fear-across-a-wealthy-district',description:'Rule through fear across a wealthy district',category:'evil'},
  {id:'evil-rule-through-fear-across-a-border-kingdom',description:'Rule through fear across a border kingdom',category:'evil'},
  {id:'evil-rule-through-fear-across-a-powerful-guild',description:'Rule through fear across a powerful guild',category:'evil'},
  {id:'personal-master-the-skills-needed-for-a-demanding-craft',description:'Master the skills needed for a demanding craft',category:'personal'},
  {id:'personal-master-the-skills-needed-for-a-respected-order',description:'Master the skills needed for a respected order',category:'personal'},
  {id:'personal-master-the-skills-needed-for-a-distant-homeland',description:'Master the skills needed for a distant homeland',category:'personal'},
  {id:'personal-earn-recognition-from-a-demanding-craft',description:'Earn recognition from a demanding craft',category:'personal'},
  {id:'personal-earn-recognition-from-a-respected-order',description:'Earn recognition from a respected order',category:'personal'},
  {id:'personal-earn-recognition-from-a-distant-homeland',description:'Earn recognition from a distant homeland',category:'personal'},
  {id:'personal-overcome-a-lifelong-fear-of-a-demanding-craft',description:'Overcome a lifelong fear of a demanding craft',category:'personal'},
  {id:'personal-overcome-a-lifelong-fear-of-a-respected-order',description:'Overcome a lifelong fear of a respected order',category:'personal'},
  {id:'personal-overcome-a-lifelong-fear-of-a-distant-homeland',description:'Overcome a lifelong fear of a distant homeland',category:'personal'},
  {id:'personal-complete-a-promise-involving-a-demanding-craft',description:'Complete a promise involving a demanding craft',category:'personal'},
  {id:'personal-complete-a-promise-involving-a-respected-order',description:'Complete a promise involving a respected order',category:'personal'},
  {id:'personal-complete-a-promise-involving-a-distant-homeland',description:'Complete a promise involving a distant homeland',category:'personal'},
  {id:'personal-prove-personal-worth-before-a-demanding-craft',description:'Prove personal worth before a demanding craft',category:'personal'},
  {id:'personal-prove-personal-worth-before-a-respected-order',description:'Prove personal worth before a respected order',category:'personal'},
  {id:'personal-prove-personal-worth-before-a-distant-homeland',description:'Prove personal worth before a distant homeland',category:'personal'},
  {id:'personal-find-a-place-to-belong-within-a-demanding-craft',description:'Find a place to belong within a demanding craft',category:'personal'},
  {id:'personal-find-a-place-to-belong-within-a-respected-order',description:'Find a place to belong within a respected order',category:'personal'},
  {id:'personal-find-a-place-to-belong-within-a-distant-homeland',description:'Find a place to belong within a distant homeland',category:'personal'},
  {id:'personal-create-a-legacy-connected-to-a-demanding-craft',description:'Create a legacy connected to a demanding craft',category:'personal'},
  {id:'personal-create-a-legacy-connected-to-a-respected-order',description:'Create a legacy connected to a respected order',category:'personal'},
  {id:'personal-create-a-legacy-connected-to-a-distant-homeland',description:'Create a legacy connected to a distant homeland',category:'personal'},
  {id:'political-win-a-council-seat-in-the-city-government',description:'Win a council seat in the city government',category:'political'},
  {id:'political-win-a-council-seat-in-a-noble-court',description:'Win a council seat in a noble court',category:'political'},
  {id:'political-win-a-council-seat-in-a-divided-province',description:'Win a council seat in a divided province',category:'political'},
  {id:'political-reform-an-unjust-law-in-the-city-government',description:'Reform an unjust law in the city government',category:'political'},
  {id:'political-reform-an-unjust-law-in-a-noble-court',description:'Reform an unjust law in a noble court',category:'political'},
  {id:'political-reform-an-unjust-law-in-a-divided-province',description:'Reform an unjust law in a divided province',category:'political'},
  {id:'political-form-a-stable-coalition-in-the-city-government',description:'Form a stable coalition in the city government',category:'political'},
  {id:'political-form-a-stable-coalition-in-a-noble-court',description:'Form a stable coalition in a noble court',category:'political'},
  {id:'political-form-a-stable-coalition-in-a-divided-province',description:'Form a stable coalition in a divided province',category:'political'},
  {id:'political-prevent-a-coup-within-the-city-government',description:'Prevent a coup within the city government',category:'political'},
  {id:'political-prevent-a-coup-within-a-noble-court',description:'Prevent a coup within a noble court',category:'political'},
  {id:'political-prevent-a-coup-within-a-divided-province',description:'Prevent a coup within a divided province',category:'political'},
  {id:'political-secure-autonomy-for-the-city-government',description:'Secure autonomy for the city government',category:'political'},
  {id:'political-secure-autonomy-for-a-noble-court',description:'Secure autonomy for a noble court',category:'political'},
  {id:'political-secure-autonomy-for-a-divided-province',description:'Secure autonomy for a divided province',category:'political'},
  {id:'political-expose-official-corruption-in-the-city-government',description:'Expose official corruption in the city government',category:'political'},
  {id:'political-expose-official-corruption-in-a-noble-court',description:'Expose official corruption in a noble court',category:'political'},
  {id:'political-expose-official-corruption-in-a-divided-province',description:'Expose official corruption in a divided province',category:'political'},
  {id:'political-broker-a-durable-peace-for-the-city-government',description:'Broker a durable peace for the city government',category:'political'},
  {id:'political-broker-a-durable-peace-for-a-noble-court',description:'Broker a durable peace for a noble court',category:'political'},
  {id:'political-broker-a-durable-peace-for-a-divided-province',description:'Broker a durable peace for a divided province',category:'political'},
  {id:'financial-repay-a-dangerous-debt-to-a-distant-port',description:'Repay a dangerous debt to a distant port',category:'financial'},
  {id:'financial-repay-a-dangerous-debt-to-a-wealthy-guild',description:'Repay a dangerous debt to a wealthy guild',category:'financial'},
  {id:'financial-repay-a-dangerous-debt-to-a-growing-settlement',description:'Repay a dangerous debt to a growing settlement',category:'financial'},
  {id:'financial-build-a-profitable-trade-with-a-distant-port',description:'Build a profitable trade with a distant port',category:'financial'},
  {id:'financial-build-a-profitable-trade-with-a-wealthy-guild',description:'Build a profitable trade with a wealthy guild',category:'financial'},
  {id:'financial-build-a-profitable-trade-with-a-growing-settlement',description:'Build a profitable trade with a growing settlement',category:'financial'},
  {id:'financial-recover-assets-hidden-in-a-distant-port',description:'Recover assets hidden in a distant port',category:'financial'},
  {id:'financial-recover-assets-hidden-in-a-wealthy-guild',description:'Recover assets hidden in a wealthy guild',category:'financial'},
  {id:'financial-recover-assets-hidden-in-a-growing-settlement',description:'Recover assets hidden in a growing settlement',category:'financial'},
  {id:'financial-finance-a-new-venture-in-a-distant-port',description:'Finance a new venture in a distant port',category:'financial'},
  {id:'financial-finance-a-new-venture-in-a-wealthy-guild',description:'Finance a new venture in a wealthy guild',category:'financial'},
  {id:'financial-finance-a-new-venture-in-a-growing-settlement',description:'Finance a new venture in a growing settlement',category:'financial'},
  {id:'financial-protect-an-investment-tied-to-a-distant-port',description:'Protect an investment tied to a distant port',category:'financial'},
  {id:'financial-protect-an-investment-tied-to-a-wealthy-guild',description:'Protect an investment tied to a wealthy guild',category:'financial'},
  {id:'financial-protect-an-investment-tied-to-a-growing-settlement',description:'Protect an investment tied to a growing settlement',category:'financial'},
  {id:'financial-earn-enough-to-purchase-a-distant-port',description:'Earn enough to purchase a distant port',category:'financial'},
  {id:'financial-earn-enough-to-purchase-a-wealthy-guild',description:'Earn enough to purchase a wealthy guild',category:'financial'},
  {id:'financial-earn-enough-to-purchase-a-growing-settlement',description:'Earn enough to purchase a growing settlement',category:'financial'},
  {id:'financial-corner-the-market-serving-a-distant-port',description:'Corner the market serving a distant port',category:'financial'},
  {id:'financial-corner-the-market-serving-a-wealthy-guild',description:'Corner the market serving a wealthy guild',category:'financial'},
  {id:'financial-corner-the-market-serving-a-growing-settlement',description:'Corner the market serving a growing settlement',category:'financial'},
  {id:'religious-restore-a-sacred-site-in-a-ruined-temple',description:'Restore a sacred site in a ruined temple',category:'religious'},
  {id:'religious-restore-a-sacred-site-in-a-contested-holy-city',description:'Restore a sacred site in a contested holy city',category:'religious'},
  {id:'religious-restore-a-sacred-site-in-a-remote-mountain',description:'Restore a sacred site in a remote mountain',category:'religious'},
  {id:'religious-complete-a-pilgrimage-through-a-ruined-temple',description:'Complete a pilgrimage through a ruined temple',category:'religious'},
  {id:'religious-complete-a-pilgrimage-through-a-contested-holy-city',description:'Complete a pilgrimage through a contested holy city',category:'religious'},
  {id:'religious-complete-a-pilgrimage-through-a-remote-mountain',description:'Complete a pilgrimage through a remote mountain',category:'religious'},
  {id:'religious-recover-a-relic-lost-in-a-ruined-temple',description:'Recover a relic lost in a ruined temple',category:'religious'},
  {id:'religious-recover-a-relic-lost-in-a-contested-holy-city',description:'Recover a relic lost in a contested holy city',category:'religious'},
  {id:'religious-recover-a-relic-lost-in-a-remote-mountain',description:'Recover a relic lost in a remote mountain',category:'religious'},
  {id:'religious-convert-willing-followers-in-a-ruined-temple',description:'Convert willing followers in a ruined temple',category:'religious'},
  {id:'religious-convert-willing-followers-in-a-contested-holy-city',description:'Convert willing followers in a contested holy city',category:'religious'},
  {id:'religious-convert-willing-followers-in-a-remote-mountain',description:'Convert willing followers in a remote mountain',category:'religious'},
  {id:'religious-reconcile-rival-sects-within-a-ruined-temple',description:'Reconcile rival sects within a ruined temple',category:'religious'},
  {id:'religious-reconcile-rival-sects-within-a-contested-holy-city',description:'Reconcile rival sects within a contested holy city',category:'religious'},
  {id:'religious-reconcile-rival-sects-within-a-remote-mountain',description:'Reconcile rival sects within a remote mountain',category:'religious'},
  {id:'religious-fulfill-a-divine-omen-concerning-a-ruined-temple',description:'Fulfill a divine omen concerning a ruined temple',category:'religious'},
  {id:'religious-fulfill-a-divine-omen-concerning-a-contested-holy-city',description:'Fulfill a divine omen concerning a contested holy city',category:'religious'},
  {id:'religious-fulfill-a-divine-omen-concerning-a-remote-mountain',description:'Fulfill a divine omen concerning a remote mountain',category:'religious'},
  {id:'religious-protect-worshipers-traveling-to-a-ruined-temple',description:'Protect worshipers traveling to a ruined temple',category:'religious'},
  {id:'religious-protect-worshipers-traveling-to-a-contested-holy-city',description:'Protect worshipers traveling to a contested holy city',category:'religious'},
  {id:'religious-protect-worshipers-traveling-to-a-remote-mountain',description:'Protect worshipers traveling to a remote mountain',category:'religious'},
  {id:'family-reunite-relatives-separated-by-a-past-war',description:'Reunite relatives separated by a past war',category:'family'},
  {id:'family-reunite-relatives-separated-by-an-old-betrayal',description:'Reunite relatives separated by an old betrayal',category:'family'},
  {id:'family-reunite-relatives-separated-by-a-disputed-inheritance',description:'Reunite relatives separated by a disputed inheritance',category:'family'},
  {id:'family-protect-the-family-from-a-past-war',description:'Protect the family from a past war',category:'family'},
  {id:'family-protect-the-family-from-an-old-betrayal',description:'Protect the family from an old betrayal',category:'family'},
  {id:'family-protect-the-family-from-a-disputed-inheritance',description:'Protect the family from a disputed inheritance',category:'family'},
  {id:'family-restore-the-family-name-after-a-past-war',description:'Restore the family name after a past war',category:'family'},
  {id:'family-restore-the-family-name-after-an-old-betrayal',description:'Restore the family name after an old betrayal',category:'family'},
  {id:'family-restore-the-family-name-after-a-disputed-inheritance',description:'Restore the family name after a disputed inheritance',category:'family'},
  {id:'family-find-an-heirloom-lost-during-a-past-war',description:'Find an heirloom lost during a past war',category:'family'},
  {id:'family-find-an-heirloom-lost-during-an-old-betrayal',description:'Find an heirloom lost during an old betrayal',category:'family'},
  {id:'family-find-an-heirloom-lost-during-a-disputed-inheritance',description:'Find an heirloom lost during a disputed inheritance',category:'family'},
  {id:'family-arrange-a-safe-future-despite-a-past-war',description:'Arrange a safe future despite a past war',category:'family'},
  {id:'family-arrange-a-safe-future-despite-an-old-betrayal',description:'Arrange a safe future despite an old betrayal',category:'family'},
  {id:'family-arrange-a-safe-future-despite-a-disputed-inheritance',description:'Arrange a safe future despite a disputed inheritance',category:'family'},
  {id:'family-discover-the-truth-about-a-past-war',description:'Discover the truth about a past war',category:'family'},
  {id:'family-discover-the-truth-about-an-old-betrayal',description:'Discover the truth about an old betrayal',category:'family'},
  {id:'family-discover-the-truth-about-a-disputed-inheritance',description:'Discover the truth about a disputed inheritance',category:'family'},
  {id:'family-make-peace-with-relatives-over-a-past-war',description:'Make peace with relatives over a past war',category:'family'},
  {id:'family-make-peace-with-relatives-over-an-old-betrayal',description:'Make peace with relatives over an old betrayal',category:'family'},
  {id:'family-make-peace-with-relatives-over-a-disputed-inheritance',description:'Make peace with relatives over a disputed inheritance',category:'family'},
  {id:'survival-find-secure-shelter-before-a-deadly-winter',description:'Find secure shelter before a deadly winter',category:'survival'},
  {id:'survival-find-secure-shelter-before-an-advancing-army',description:'Find secure shelter before an advancing army',category:'survival'},
  {id:'survival-find-secure-shelter-before-a-spreading-plague',description:'Find secure shelter before a spreading plague',category:'survival'},
  {id:'survival-stock-enough-supplies-for-a-deadly-winter',description:'Stock enough supplies for a deadly winter',category:'survival'},
  {id:'survival-stock-enough-supplies-for-an-advancing-army',description:'Stock enough supplies for an advancing army',category:'survival'},
  {id:'survival-stock-enough-supplies-for-a-spreading-plague',description:'Stock enough supplies for a spreading plague',category:'survival'},
  {id:'survival-escape-the-region-ahead-of-a-deadly-winter',description:'Escape the region ahead of a deadly winter',category:'survival'},
  {id:'survival-escape-the-region-ahead-of-an-advancing-army',description:'Escape the region ahead of an advancing army',category:'survival'},
  {id:'survival-escape-the-region-ahead-of-a-spreading-plague',description:'Escape the region ahead of a spreading plague',category:'survival'},
  {id:'survival-protect-a-water-source-during-a-deadly-winter',description:'Protect a water source during a deadly winter',category:'survival'},
  {id:'survival-protect-a-water-source-during-an-advancing-army',description:'Protect a water source during an advancing army',category:'survival'},
  {id:'survival-protect-a-water-source-during-a-spreading-plague',description:'Protect a water source during a spreading plague',category:'survival'},
  {id:'survival-guide-companions-through-a-deadly-winter',description:'Guide companions through a deadly winter',category:'survival'},
  {id:'survival-guide-companions-through-an-advancing-army',description:'Guide companions through an advancing army',category:'survival'},
  {id:'survival-guide-companions-through-a-spreading-plague',description:'Guide companions through a spreading plague',category:'survival'},
  {id:'survival-learn-to-endure-a-deadly-winter',description:'Learn to endure a deadly winter',category:'survival'},
  {id:'survival-learn-to-endure-an-advancing-army',description:'Learn to endure an advancing army',category:'survival'},
  {id:'survival-learn-to-endure-a-spreading-plague',description:'Learn to endure a spreading plague',category:'survival'},
  {id:'survival-remove-the-threat-posed-by-a-deadly-winter',description:'Remove the threat posed by a deadly winter',category:'survival'},
  {id:'survival-remove-the-threat-posed-by-an-advancing-army',description:'Remove the threat posed by an advancing army',category:'survival'},
  {id:'survival-remove-the-threat-posed-by-a-spreading-plague',description:'Remove the threat posed by a spreading plague',category:'survival'},
  {id:'revenge-expose-the-architect-of-a-family-murder',description:'Expose the architect of a family murder',category:'revenge'},
  {id:'revenge-expose-the-architect-of-a-public-disgrace',description:'Expose the architect of a public disgrace',category:'revenge'},
  {id:'revenge-expose-the-architect-of-a-destroyed-home',description:'Expose the architect of a destroyed home',category:'revenge'},
  {id:'revenge-ruin-those-who-profited-from-a-family-murder',description:'Ruin those who profited from a family murder',category:'revenge'},
  {id:'revenge-ruin-those-who-profited-from-a-public-disgrace',description:'Ruin those who profited from a public disgrace',category:'revenge'},
  {id:'revenge-ruin-those-who-profited-from-a-destroyed-home',description:'Ruin those who profited from a destroyed home',category:'revenge'},
  {id:'revenge-bring-the-culprit-behind-a-family-murder-to-trial',description:'Bring the culprit behind a family murder to trial',category:'revenge'},
  {id:'revenge-bring-the-culprit-behind-a-public-disgrace-to-trial',description:'Bring the culprit behind a public disgrace to trial',category:'revenge'},
  {id:'revenge-bring-the-culprit-behind-a-destroyed-home-to-trial',description:'Bring the culprit behind a destroyed home to trial',category:'revenge'},
  {id:'revenge-recover-what-was-taken-during-a-family-murder',description:'Recover what was taken during a family murder',category:'revenge'},
  {id:'revenge-recover-what-was-taken-during-a-public-disgrace',description:'Recover what was taken during a public disgrace',category:'revenge'},
  {id:'revenge-recover-what-was-taken-during-a-destroyed-home',description:'Recover what was taken during a destroyed home',category:'revenge'},
  {id:'revenge-force-a-confession-about-a-family-murder',description:'Force a confession about a family murder',category:'revenge'},
  {id:'revenge-force-a-confession-about-a-public-disgrace',description:'Force a confession about a public disgrace',category:'revenge'},
  {id:'revenge-force-a-confession-about-a-destroyed-home',description:'Force a confession about a destroyed home',category:'revenge'},
  {id:'revenge-dismantle-the-faction-responsible-for-a-family-murder',description:'Dismantle the faction responsible for a family murder',category:'revenge'},
  {id:'revenge-dismantle-the-faction-responsible-for-a-public-disgrace',description:'Dismantle the faction responsible for a public disgrace',category:'revenge'},
  {id:'revenge-dismantle-the-faction-responsible-for-a-destroyed-home',description:'Dismantle the faction responsible for a destroyed home',category:'revenge'},
  {id:'revenge-confront-the-betrayer-tied-to-a-family-murder',description:'Confront the betrayer tied to a family murder',category:'revenge'},
  {id:'revenge-confront-the-betrayer-tied-to-a-public-disgrace',description:'Confront the betrayer tied to a public disgrace',category:'revenge'},
  {id:'revenge-confront-the-betrayer-tied-to-a-destroyed-home',description:'Confront the betrayer tied to a destroyed home',category:'revenge'},
  {id:'knowledge-translate-records-concerning-an-ancient-empire',description:'Translate records concerning an ancient empire',category:'knowledge'},
  {id:'knowledge-translate-records-concerning-a-planar-anomaly',description:'Translate records concerning a planar anomaly',category:'knowledge'},
  {id:'knowledge-translate-records-concerning-a-vanished-expedition',description:'Translate records concerning a vanished expedition',category:'knowledge'},
  {id:'knowledge-locate-a-lost-archive-about-an-ancient-empire',description:'Locate a lost archive about an ancient empire',category:'knowledge'},
  {id:'knowledge-locate-a-lost-archive-about-a-planar-anomaly',description:'Locate a lost archive about a planar anomaly',category:'knowledge'},
  {id:'knowledge-locate-a-lost-archive-about-a-vanished-expedition',description:'Locate a lost archive about a vanished expedition',category:'knowledge'},
  {id:'knowledge-interview-the-last-witness-to-an-ancient-empire',description:'Interview the last witness to an ancient empire',category:'knowledge'},
  {id:'knowledge-interview-the-last-witness-to-a-planar-anomaly',description:'Interview the last witness to a planar anomaly',category:'knowledge'},
  {id:'knowledge-interview-the-last-witness-to-a-vanished-expedition',description:'Interview the last witness to a vanished expedition',category:'knowledge'},
  {id:'knowledge-prove-a-disputed-theory-about-an-ancient-empire',description:'Prove a disputed theory about an ancient empire',category:'knowledge'},
  {id:'knowledge-prove-a-disputed-theory-about-a-planar-anomaly',description:'Prove a disputed theory about a planar anomaly',category:'knowledge'},
  {id:'knowledge-prove-a-disputed-theory-about-a-vanished-expedition',description:'Prove a disputed theory about a vanished expedition',category:'knowledge'},
  {id:'knowledge-preserve-forbidden-knowledge-of-an-ancient-empire',description:'Preserve forbidden knowledge of an ancient empire',category:'knowledge'},
  {id:'knowledge-preserve-forbidden-knowledge-of-a-planar-anomaly',description:'Preserve forbidden knowledge of a planar anomaly',category:'knowledge'},
  {id:'knowledge-preserve-forbidden-knowledge-of-a-vanished-expedition',description:'Preserve forbidden knowledge of a vanished expedition',category:'knowledge'},
  {id:'knowledge-discover-the-origin-of-an-ancient-empire',description:'Discover the origin of an ancient empire',category:'knowledge'},
  {id:'knowledge-discover-the-origin-of-a-planar-anomaly',description:'Discover the origin of a planar anomaly',category:'knowledge'},
  {id:'knowledge-discover-the-origin-of-a-vanished-expedition',description:'Discover the origin of a vanished expedition',category:'knowledge'},
  {id:'knowledge-publish-the-truth-concerning-an-ancient-empire',description:'Publish the truth concerning an ancient empire',category:'knowledge'},
  {id:'knowledge-publish-the-truth-concerning-a-planar-anomaly',description:'Publish the truth concerning a planar anomaly',category:'knowledge'},
  {id:'knowledge-publish-the-truth-concerning-a-vanished-expedition',description:'Publish the truth concerning a vanished expedition',category:'knowledge'},
  {id:'power-gain-command-over-a-mercenary-company',description:'Gain command over a mercenary company',category:'power'},
  {id:'power-gain-command-over-a-royal-court',description:'Gain command over a royal court',category:'power'},
  {id:'power-gain-command-over-an-arcane-institution',description:'Gain command over an arcane institution',category:'power'},
  {id:'power-acquire-leverage-against-a-mercenary-company',description:'Acquire leverage against a mercenary company',category:'power'},
  {id:'power-acquire-leverage-against-a-royal-court',description:'Acquire leverage against a royal court',category:'power'},
  {id:'power-acquire-leverage-against-an-arcane-institution',description:'Acquire leverage against an arcane institution',category:'power'},
  {id:'power-claim-the-authority-to-govern-a-mercenary-company',description:'Claim the authority to govern a mercenary company',category:'power'},
  {id:'power-claim-the-authority-to-govern-a-royal-court',description:'Claim the authority to govern a royal court',category:'power'},
  {id:'power-claim-the-authority-to-govern-an-arcane-institution',description:'Claim the authority to govern an arcane institution',category:'power'},
  {id:'power-bind-the-magic-contained-in-a-mercenary-company',description:'Bind the magic contained in a mercenary company',category:'power'},
  {id:'power-bind-the-magic-contained-in-a-royal-court',description:'Bind the magic contained in a royal court',category:'power'},
  {id:'power-bind-the-magic-contained-in-an-arcane-institution',description:'Bind the magic contained in an arcane institution',category:'power'},
  {id:'power-recruit-loyal-agents-throughout-a-mercenary-company',description:'Recruit loyal agents throughout a mercenary company',category:'power'},
  {id:'power-recruit-loyal-agents-throughout-a-royal-court',description:'Recruit loyal agents throughout a royal court',category:'power'},
  {id:'power-recruit-loyal-agents-throughout-an-arcane-institution',description:'Recruit loyal agents throughout an arcane institution',category:'power'},
  {id:'power-control-access-to-a-mercenary-company',description:'Control access to a mercenary company',category:'power'},
  {id:'power-control-access-to-a-royal-court',description:'Control access to a royal court',category:'power'},
  {id:'power-control-access-to-an-arcane-institution',description:'Control access to an arcane institution',category:'power'},
  {id:'power-become-indispensable-to-a-mercenary-company',description:'Become indispensable to a mercenary company',category:'power'},
  {id:'power-become-indispensable-to-a-royal-court',description:'Become indispensable to a royal court',category:'power'},
  {id:'power-become-indispensable-to-an-arcane-institution',description:'Become indispensable to an arcane institution',category:'power'},
] as const satisfies readonly GoalData[];
