import type { HookData } from '../types';

export const HOOKS = [
  {id:'hook-001',title:'A patrol vanished after confronting',summary:'A patrol vanished after confronting raiders. The obvious patron is withholding a crucial fact.',category:'combat'},
  {id:'hook-002',title:'A patrol vanished after confronting',summary:'A patrol vanished after confronting raiders. A rival group is pursuing the same objective.',category:'combat'},
  {id:'hook-003',title:'A patrol vanished after confronting',summary:'A patrol vanished after confronting raiders. Success will require cooperation with a distrusted faction.',category:'combat'},
  {id:'hook-004',title:'A patrol vanished after confronting',summary:'A patrol vanished after confronting raiders. The danger grows substantially after sunset.',category:'combat'},
  {id:'hook-005',title:'A wounded monster has entered',summary:'A wounded monster has entered settled lands. The obvious patron is withholding a crucial fact.',category:'combat'},
  {id:'hook-006',title:'A wounded monster has entered',summary:'A wounded monster has entered settled lands. A rival group is pursuing the same objective.',category:'combat'},
  {id:'hook-007',title:'A wounded monster has entered',summary:'A wounded monster has entered settled lands. Success will require cooperation with a distrusted faction.',category:'combat'},
  {id:'hook-008',title:'A wounded monster has entered',summary:'A wounded monster has entered settled lands. The danger grows substantially after sunset.',category:'combat'},
  {id:'hook-009',title:'Two mercenary companies are about',summary:'Two mercenary companies are about to clash. The obvious patron is withholding a crucial fact.',category:'combat'},
  {id:'hook-010',title:'Two mercenary companies are about',summary:'Two mercenary companies are about to clash. A rival group is pursuing the same objective.',category:'combat'},
  {id:'hook-011',title:'Two mercenary companies are about',summary:'Two mercenary companies are about to clash. Success will require cooperation with a distrusted faction.',category:'combat'},
  {id:'hook-012',title:'Two mercenary companies are about',summary:'Two mercenary companies are about to clash. The danger grows substantially after sunset.',category:'combat'},
  {id:'hook-013',title:'An old battlefield has begun',summary:'An old battlefield has begun raising its dead. The obvious patron is withholding a crucial fact.',category:'combat'},
  {id:'hook-014',title:'An old battlefield has begun',summary:'An old battlefield has begun raising its dead. A rival group is pursuing the same objective.',category:'combat'},
  {id:'hook-015',title:'An old battlefield has begun',summary:'An old battlefield has begun raising its dead. Success will require cooperation with a distrusted faction.',category:'combat'},
  {id:'hook-016',title:'An old battlefield has begun',summary:'An old battlefield has begun raising its dead. The danger grows substantially after sunset.',category:'combat'},
  {id:'hook-017',title:'A warlord is testing the',summary:'A warlord is testing the town\'s defenses. The obvious patron is withholding a crucial fact.',category:'combat'},
  {id:'hook-018',title:'A warlord is testing the',summary:'A warlord is testing the town\'s defenses. A rival group is pursuing the same objective.',category:'combat'},
  {id:'hook-019',title:'A warlord is testing the',summary:'A warlord is testing the town\'s defenses. Success will require cooperation with a distrusted faction.',category:'combat'},
  {id:'hook-020',title:'A warlord is testing the',summary:'A warlord is testing the town\'s defenses. The danger grows substantially after sunset.',category:'combat'},
  {id:'hook-021',title:'A caravan is pinned down',summary:'A caravan is pinned down by predators. The obvious patron is withholding a crucial fact.',category:'combat'},
  {id:'hook-022',title:'A caravan is pinned down',summary:'A caravan is pinned down by predators. A rival group is pursuing the same objective.',category:'combat'},
  {id:'hook-023',title:'A caravan is pinned down',summary:'A caravan is pinned down by predators. Success will require cooperation with a distrusted faction.',category:'combat'},
  {id:'hook-024',title:'A caravan is pinned down',summary:'A caravan is pinned down by predators. The danger grows substantially after sunset.',category:'combat'},
  {id:'hook-025',title:'A champion demands trial by',summary:'A champion demands trial by combat. The obvious patron is withholding a crucial fact.',category:'combat'},
  {id:'hook-026',title:'A champion demands trial by',summary:'A champion demands trial by combat. A rival group is pursuing the same objective.',category:'combat'},
  {id:'hook-027',title:'A champion demands trial by',summary:'A champion demands trial by combat. Success will require cooperation with a distrusted faction.',category:'combat'},
  {id:'hook-028',title:'A champion demands trial by',summary:'A champion demands trial by combat. The danger grows substantially after sunset.',category:'combat'},
  {id:'hook-029',title:'A public wedding joins two',summary:'A public wedding joins two hostile families. The obvious patron is withholding a crucial fact.',category:'social'},
  {id:'hook-030',title:'A public wedding joins two',summary:'A public wedding joins two hostile families. A rival group is pursuing the same objective.',category:'social'},
  {id:'hook-031',title:'A public wedding joins two',summary:'A public wedding joins two hostile families. Success will require cooperation with a distrusted faction.',category:'social'},
  {id:'hook-032',title:'A public wedding joins two',summary:'A public wedding joins two hostile families. The danger grows substantially after sunset.',category:'social'},
  {id:'hook-033',title:'A beloved performer refuses to',summary:'A beloved performer refuses to take the stage. The obvious patron is withholding a crucial fact.',category:'social'},
  {id:'hook-034',title:'A beloved performer refuses to',summary:'A beloved performer refuses to take the stage. A rival group is pursuing the same objective.',category:'social'},
  {id:'hook-035',title:'A beloved performer refuses to',summary:'A beloved performer refuses to take the stage. Success will require cooperation with a distrusted faction.',category:'social'},
  {id:'hook-036',title:'A beloved performer refuses to',summary:'A beloved performer refuses to take the stage. The danger grows substantially after sunset.',category:'social'},
  {id:'hook-037',title:'A foreign envoy has insulted',summary:'A foreign envoy has insulted a local custom. The obvious patron is withholding a crucial fact.',category:'social'},
  {id:'hook-038',title:'A foreign envoy has insulted',summary:'A foreign envoy has insulted a local custom. A rival group is pursuing the same objective.',category:'social'},
  {id:'hook-039',title:'A foreign envoy has insulted',summary:'A foreign envoy has insulted a local custom. Success will require cooperation with a distrusted faction.',category:'social'},
  {id:'hook-040',title:'A foreign envoy has insulted',summary:'A foreign envoy has insulted a local custom. The danger grows substantially after sunset.',category:'social'},
  {id:'hook-041',title:'A guild election depends on',summary:'A guild election depends on one undecided voter. The obvious patron is withholding a crucial fact.',category:'social'},
  {id:'hook-042',title:'A guild election depends on',summary:'A guild election depends on one undecided voter. A rival group is pursuing the same objective.',category:'social'},
  {id:'hook-043',title:'A guild election depends on',summary:'A guild election depends on one undecided voter. Success will require cooperation with a distrusted faction.',category:'social'},
  {id:'hook-044',title:'A guild election depends on',summary:'A guild election depends on one undecided voter. The danger grows substantially after sunset.',category:'social'},
  {id:'hook-045',title:'A festival prize has gone',summary:'A festival prize has gone to the wrong contestant. The obvious patron is withholding a crucial fact.',category:'social'},
  {id:'hook-046',title:'A festival prize has gone',summary:'A festival prize has gone to the wrong contestant. A rival group is pursuing the same objective.',category:'social'},
  {id:'hook-047',title:'A festival prize has gone',summary:'A festival prize has gone to the wrong contestant. Success will require cooperation with a distrusted faction.',category:'social'},
  {id:'hook-048',title:'A festival prize has gone',summary:'A festival prize has gone to the wrong contestant. The danger grows substantially after sunset.',category:'social'},
  {id:'hook-049',title:'A reclusive witness will speak',summary:'A reclusive witness will speak to only one guest. The obvious patron is withholding a crucial fact.',category:'social'},
  {id:'hook-050',title:'A reclusive witness will speak',summary:'A reclusive witness will speak to only one guest. A rival group is pursuing the same objective.',category:'social'},
  {id:'hook-051',title:'A reclusive witness will speak',summary:'A reclusive witness will speak to only one guest. Success will require cooperation with a distrusted faction.',category:'social'},
  {id:'hook-052',title:'A reclusive witness will speak',summary:'A reclusive witness will speak to only one guest. The danger grows substantially after sunset.',category:'social'},
  {id:'hook-053',title:'A prominent host has invited',summary:'A prominent host has invited sworn enemies. The obvious patron is withholding a crucial fact.',category:'social'},
  {id:'hook-054',title:'A prominent host has invited',summary:'A prominent host has invited sworn enemies. A rival group is pursuing the same objective.',category:'social'},
  {id:'hook-055',title:'A prominent host has invited',summary:'A prominent host has invited sworn enemies. Success will require cooperation with a distrusted faction.',category:'social'},
  {id:'hook-056',title:'A prominent host has invited',summary:'A prominent host has invited sworn enemies. The danger grows substantially after sunset.',category:'social'},
  {id:'hook-057',title:'A newly exposed stair descends',summary:'A newly exposed stair descends beneath the cliffs. The obvious patron is withholding a crucial fact.',category:'exploration'},
  {id:'hook-058',title:'A newly exposed stair descends',summary:'A newly exposed stair descends beneath the cliffs. A rival group is pursuing the same objective.',category:'exploration'},
  {id:'hook-059',title:'A newly exposed stair descends',summary:'A newly exposed stair descends beneath the cliffs. Success will require cooperation with a distrusted faction.',category:'exploration'},
  {id:'hook-060',title:'A newly exposed stair descends',summary:'A newly exposed stair descends beneath the cliffs. The danger grows substantially after sunset.',category:'exploration'},
  {id:'hook-061',title:'An old map marks a',summary:'An old map marks a valley absent from modern charts. The obvious patron is withholding a crucial fact.',category:'exploration'},
  {id:'hook-062',title:'An old map marks a',summary:'An old map marks a valley absent from modern charts. A rival group is pursuing the same objective.',category:'exploration'},
  {id:'hook-063',title:'An old map marks a',summary:'An old map marks a valley absent from modern charts. Success will require cooperation with a distrusted faction.',category:'exploration'},
  {id:'hook-064',title:'An old map marks a',summary:'An old map marks a valley absent from modern charts. The danger grows substantially after sunset.',category:'exploration'},
  {id:'hook-065',title:'A lighthouse shines from an',summary:'A lighthouse shines from an abandoned coast. The obvious patron is withholding a crucial fact.',category:'exploration'},
  {id:'hook-066',title:'A lighthouse shines from an',summary:'A lighthouse shines from an abandoned coast. A rival group is pursuing the same objective.',category:'exploration'},
  {id:'hook-067',title:'A lighthouse shines from an',summary:'A lighthouse shines from an abandoned coast. Success will require cooperation with a distrusted faction.',category:'exploration'},
  {id:'hook-068',title:'A lighthouse shines from an',summary:'A lighthouse shines from an abandoned coast. The danger grows substantially after sunset.',category:'exploration'},
  {id:'hook-069',title:'A migrating beast carries ruins',summary:'A migrating beast carries ruins on its back. The obvious patron is withholding a crucial fact.',category:'exploration'},
  {id:'hook-070',title:'A migrating beast carries ruins',summary:'A migrating beast carries ruins on its back. A rival group is pursuing the same objective.',category:'exploration'},
  {id:'hook-071',title:'A migrating beast carries ruins',summary:'A migrating beast carries ruins on its back. Success will require cooperation with a distrusted faction.',category:'exploration'},
  {id:'hook-072',title:'A migrating beast carries ruins',summary:'A migrating beast carries ruins on its back. The danger grows substantially after sunset.',category:'exploration'},
  {id:'hook-073',title:'A sinkhole reveals an intact',summary:'A sinkhole reveals an intact underground road. The obvious patron is withholding a crucial fact.',category:'exploration'},
  {id:'hook-074',title:'A sinkhole reveals an intact',summary:'A sinkhole reveals an intact underground road. A rival group is pursuing the same objective.',category:'exploration'},
  {id:'hook-075',title:'A sinkhole reveals an intact',summary:'A sinkhole reveals an intact underground road. Success will require cooperation with a distrusted faction.',category:'exploration'},
  {id:'hook-076',title:'A sinkhole reveals an intact',summary:'A sinkhole reveals an intact underground road. The danger grows substantially after sunset.',category:'exploration'},
  {id:'hook-077',title:'A constellation points toward a',summary:'A constellation points toward a moving island. The obvious patron is withholding a crucial fact.',category:'exploration'},
  {id:'hook-078',title:'A constellation points toward a',summary:'A constellation points toward a moving island. A rival group is pursuing the same objective.',category:'exploration'},
  {id:'hook-079',title:'A constellation points toward a',summary:'A constellation points toward a moving island. Success will require cooperation with a distrusted faction.',category:'exploration'},
  {id:'hook-080',title:'A constellation points toward a',summary:'A constellation points toward a moving island. The danger grows substantially after sunset.',category:'exploration'},
  {id:'hook-081',title:'A glacier has uncovered a',summary:'A glacier has uncovered a sealed doorway. The obvious patron is withholding a crucial fact.',category:'exploration'},
  {id:'hook-082',title:'A glacier has uncovered a',summary:'A glacier has uncovered a sealed doorway. A rival group is pursuing the same objective.',category:'exploration'},
  {id:'hook-083',title:'A glacier has uncovered a',summary:'A glacier has uncovered a sealed doorway. Success will require cooperation with a distrusted faction.',category:'exploration'},
  {id:'hook-084',title:'A glacier has uncovered a',summary:'A glacier has uncovered a sealed doorway. The danger grows substantially after sunset.',category:'exploration'},
  {id:'hook-085',title:'A ruler dies without naming',summary:'A ruler dies without naming an heir. The obvious patron is withholding a crucial fact.',category:'political'},
  {id:'hook-086',title:'A ruler dies without naming',summary:'A ruler dies without naming an heir. A rival group is pursuing the same objective.',category:'political'},
  {id:'hook-087',title:'A ruler dies without naming',summary:'A ruler dies without naming an heir. Success will require cooperation with a distrusted faction.',category:'political'},
  {id:'hook-088',title:'A ruler dies without naming',summary:'A ruler dies without naming an heir. The danger grows substantially after sunset.',category:'political'},
  {id:'hook-089',title:'A border treaty contains a',summary:'A border treaty contains a deliberately vague clause. The obvious patron is withholding a crucial fact.',category:'political'},
  {id:'hook-090',title:'A border treaty contains a',summary:'A border treaty contains a deliberately vague clause. A rival group is pursuing the same objective.',category:'political'},
  {id:'hook-091',title:'A border treaty contains a',summary:'A border treaty contains a deliberately vague clause. Success will require cooperation with a distrusted faction.',category:'political'},
  {id:'hook-092',title:'A border treaty contains a',summary:'A border treaty contains a deliberately vague clause. The danger grows substantially after sunset.',category:'political'},
  {id:'hook-093',title:'A councilor is buying votes',summary:'A councilor is buying votes through intermediaries. The obvious patron is withholding a crucial fact.',category:'political'},
  {id:'hook-094',title:'A councilor is buying votes',summary:'A councilor is buying votes through intermediaries. A rival group is pursuing the same objective.',category:'political'},
  {id:'hook-095',title:'A councilor is buying votes',summary:'A councilor is buying votes through intermediaries. Success will require cooperation with a distrusted faction.',category:'political'},
  {id:'hook-096',title:'A councilor is buying votes',summary:'A councilor is buying votes through intermediaries. The danger grows substantially after sunset.',category:'political'},
  {id:'hook-097',title:'A province refuses the crown\'s',summary:'A province refuses the crown\'s new tax. The obvious patron is withholding a crucial fact.',category:'political'},
  {id:'hook-098',title:'A province refuses the crown\'s',summary:'A province refuses the crown\'s new tax. A rival group is pursuing the same objective.',category:'political'},
  {id:'hook-099',title:'A province refuses the crown\'s',summary:'A province refuses the crown\'s new tax. Success will require cooperation with a distrusted faction.',category:'political'},
  {id:'hook-100',title:'A province refuses the crown\'s',summary:'A province refuses the crown\'s new tax. The danger grows substantially after sunset.',category:'political'},
  {id:'hook-101',title:'A diplomatic hostage has disappeared',summary:'A diplomatic hostage has disappeared. The obvious patron is withholding a crucial fact.',category:'political'},
  {id:'hook-102',title:'A diplomatic hostage has disappeared',summary:'A diplomatic hostage has disappeared. A rival group is pursuing the same objective.',category:'political'},
  {id:'hook-103',title:'A diplomatic hostage has disappeared',summary:'A diplomatic hostage has disappeared. Success will require cooperation with a distrusted faction.',category:'political'},
  {id:'hook-104',title:'A diplomatic hostage has disappeared',summary:'A diplomatic hostage has disappeared. The danger grows substantially after sunset.',category:'political'},
  {id:'hook-105',title:'A reformer needs proof of',summary:'A reformer needs proof of official corruption. The obvious patron is withholding a crucial fact.',category:'political'},
  {id:'hook-106',title:'A reformer needs proof of',summary:'A reformer needs proof of official corruption. A rival group is pursuing the same objective.',category:'political'},
  {id:'hook-107',title:'A reformer needs proof of',summary:'A reformer needs proof of official corruption. Success will require cooperation with a distrusted faction.',category:'political'},
  {id:'hook-108',title:'A reformer needs proof of',summary:'A reformer needs proof of official corruption. The danger grows substantially after sunset.',category:'political'},
  {id:'hook-109',title:'A neutral city is pressured',summary:'A neutral city is pressured to choose a side. The obvious patron is withholding a crucial fact.',category:'political'},
  {id:'hook-110',title:'A neutral city is pressured',summary:'A neutral city is pressured to choose a side. A rival group is pursuing the same objective.',category:'political'},
  {id:'hook-111',title:'A neutral city is pressured',summary:'A neutral city is pressured to choose a side. Success will require cooperation with a distrusted faction.',category:'political'},
  {id:'hook-112',title:'A neutral city is pressured',summary:'A neutral city is pressured to choose a side. The danger grows substantially after sunset.',category:'political'},
  {id:'hook-113',title:'A temple\'s sacred flame has',summary:'A temple\'s sacred flame has changed color. The obvious patron is withholding a crucial fact.',category:'religious'},
  {id:'hook-114',title:'A temple\'s sacred flame has',summary:'A temple\'s sacred flame has changed color. A rival group is pursuing the same objective.',category:'religious'},
  {id:'hook-115',title:'A temple\'s sacred flame has',summary:'A temple\'s sacred flame has changed color. Success will require cooperation with a distrusted faction.',category:'religious'},
  {id:'hook-116',title:'A temple\'s sacred flame has',summary:'A temple\'s sacred flame has changed color. The danger grows substantially after sunset.',category:'religious'},
  {id:'hook-117',title:'Pilgrims report conflicting visions at',summary:'Pilgrims report conflicting visions at one shrine. The obvious patron is withholding a crucial fact.',category:'religious'},
  {id:'hook-118',title:'Pilgrims report conflicting visions at',summary:'Pilgrims report conflicting visions at one shrine. A rival group is pursuing the same objective.',category:'religious'},
  {id:'hook-119',title:'Pilgrims report conflicting visions at',summary:'Pilgrims report conflicting visions at one shrine. Success will require cooperation with a distrusted faction.',category:'religious'},
  {id:'hook-120',title:'Pilgrims report conflicting visions at',summary:'Pilgrims report conflicting visions at one shrine. The danger grows substantially after sunset.',category:'religious'},
  {id:'hook-121',title:'A relic rejects its appointed',summary:'A relic rejects its appointed keeper. The obvious patron is withholding a crucial fact.',category:'religious'},
  {id:'hook-122',title:'A relic rejects its appointed',summary:'A relic rejects its appointed keeper. A rival group is pursuing the same objective.',category:'religious'},
  {id:'hook-123',title:'A relic rejects its appointed',summary:'A relic rejects its appointed keeper. Success will require cooperation with a distrusted faction.',category:'religious'},
  {id:'hook-124',title:'A relic rejects its appointed',summary:'A relic rejects its appointed keeper. The danger grows substantially after sunset.',category:'religious'},
  {id:'hook-125',title:'Two faiths claim the same',summary:'Two faiths claim the same newly found saint. The obvious patron is withholding a crucial fact.',category:'religious'},
  {id:'hook-126',title:'Two faiths claim the same',summary:'Two faiths claim the same newly found saint. A rival group is pursuing the same objective.',category:'religious'},
  {id:'hook-127',title:'Two faiths claim the same',summary:'Two faiths claim the same newly found saint. Success will require cooperation with a distrusted faction.',category:'religious'},
  {id:'hook-128',title:'Two faiths claim the same',summary:'Two faiths claim the same newly found saint. The danger grows substantially after sunset.',category:'religious'},
  {id:'hook-129',title:'A procession route crosses forbidden',summary:'A procession route crosses forbidden ground. The obvious patron is withholding a crucial fact.',category:'religious'},
  {id:'hook-130',title:'A procession route crosses forbidden',summary:'A procession route crosses forbidden ground. A rival group is pursuing the same objective.',category:'religious'},
  {id:'hook-131',title:'A procession route crosses forbidden',summary:'A procession route crosses forbidden ground. Success will require cooperation with a distrusted faction.',category:'religious'},
  {id:'hook-132',title:'A procession route crosses forbidden',summary:'A procession route crosses forbidden ground. The danger grows substantially after sunset.',category:'religious'},
  {id:'hook-133',title:'A god\'s name is vanishing',summary:'A god\'s name is vanishing from old inscriptions. The obvious patron is withholding a crucial fact.',category:'religious'},
  {id:'hook-134',title:'A god\'s name is vanishing',summary:'A god\'s name is vanishing from old inscriptions. A rival group is pursuing the same objective.',category:'religious'},
  {id:'hook-135',title:'A god\'s name is vanishing',summary:'A god\'s name is vanishing from old inscriptions. Success will require cooperation with a distrusted faction.',category:'religious'},
  {id:'hook-136',title:'A god\'s name is vanishing',summary:'A god\'s name is vanishing from old inscriptions. The danger grows substantially after sunset.',category:'religious'},
  {id:'hook-137',title:'A monastery has stopped answering',summary:'A monastery has stopped answering its bells. The obvious patron is withholding a crucial fact.',category:'religious'},
  {id:'hook-138',title:'A monastery has stopped answering',summary:'A monastery has stopped answering its bells. A rival group is pursuing the same objective.',category:'religious'},
  {id:'hook-139',title:'A monastery has stopped answering',summary:'A monastery has stopped answering its bells. Success will require cooperation with a distrusted faction.',category:'religious'},
  {id:'hook-140',title:'A monastery has stopped answering',summary:'A monastery has stopped answering its bells. The danger grows substantially after sunset.',category:'religious'},
  {id:'hook-141',title:'A thieves\' guild declares an',summary:'A thieves\' guild declares an unexpected amnesty. The obvious patron is withholding a crucial fact.',category:'crime'},
  {id:'hook-142',title:'A thieves\' guild declares an',summary:'A thieves\' guild declares an unexpected amnesty. A rival group is pursuing the same objective.',category:'crime'},
  {id:'hook-143',title:'A thieves\' guild declares an',summary:'A thieves\' guild declares an unexpected amnesty. Success will require cooperation with a distrusted faction.',category:'crime'},
  {id:'hook-144',title:'A thieves\' guild declares an',summary:'A thieves\' guild declares an unexpected amnesty. The danger grows substantially after sunset.',category:'crime'},
  {id:'hook-145',title:'Counterfeit coins carry a real',summary:'Counterfeit coins carry a real royal seal. The obvious patron is withholding a crucial fact.',category:'crime'},
  {id:'hook-146',title:'Counterfeit coins carry a real',summary:'Counterfeit coins carry a real royal seal. A rival group is pursuing the same objective.',category:'crime'},
  {id:'hook-147',title:'Counterfeit coins carry a real',summary:'Counterfeit coins carry a real royal seal. Success will require cooperation with a distrusted faction.',category:'crime'},
  {id:'hook-148',title:'Counterfeit coins carry a real',summary:'Counterfeit coins carry a real royal seal. The danger grows substantially after sunset.',category:'crime'},
  {id:'hook-149',title:'A smuggler wants protection for',summary:'A smuggler wants protection for one final delivery. The obvious patron is withholding a crucial fact.',category:'crime'},
  {id:'hook-150',title:'A smuggler wants protection for',summary:'A smuggler wants protection for one final delivery. A rival group is pursuing the same objective.',category:'crime'},
  {id:'hook-151',title:'A smuggler wants protection for',summary:'A smuggler wants protection for one final delivery. Success will require cooperation with a distrusted faction.',category:'crime'},
  {id:'hook-152',title:'A smuggler wants protection for',summary:'A smuggler wants protection for one final delivery. The danger grows substantially after sunset.',category:'crime'},
  {id:'hook-153',title:'A prison ledger lists inmates',summary:'A prison ledger lists inmates who never existed. The obvious patron is withholding a crucial fact.',category:'crime'},
  {id:'hook-154',title:'A prison ledger lists inmates',summary:'A prison ledger lists inmates who never existed. A rival group is pursuing the same objective.',category:'crime'},
  {id:'hook-155',title:'A prison ledger lists inmates',summary:'A prison ledger lists inmates who never existed. Success will require cooperation with a distrusted faction.',category:'crime'},
  {id:'hook-156',title:'A prison ledger lists inmates',summary:'A prison ledger lists inmates who never existed. The danger grows substantially after sunset.',category:'crime'},
  {id:'hook-157',title:'A stolen painting contains a',summary:'A stolen painting contains a coded confession. The obvious patron is withholding a crucial fact.',category:'crime'},
  {id:'hook-158',title:'A stolen painting contains a',summary:'A stolen painting contains a coded confession. A rival group is pursuing the same objective.',category:'crime'},
  {id:'hook-159',title:'A stolen painting contains a',summary:'A stolen painting contains a coded confession. Success will require cooperation with a distrusted faction.',category:'crime'},
  {id:'hook-160',title:'A stolen painting contains a',summary:'A stolen painting contains a coded confession. The danger grows substantially after sunset.',category:'crime'},
  {id:'hook-161',title:'A crime boss offers evidence',summary:'A crime boss offers evidence against a worse rival. The obvious patron is withholding a crucial fact.',category:'crime'},
  {id:'hook-162',title:'A crime boss offers evidence',summary:'A crime boss offers evidence against a worse rival. A rival group is pursuing the same objective.',category:'crime'},
  {id:'hook-163',title:'A crime boss offers evidence',summary:'A crime boss offers evidence against a worse rival. Success will require cooperation with a distrusted faction.',category:'crime'},
  {id:'hook-164',title:'A crime boss offers evidence',summary:'A crime boss offers evidence against a worse rival. The danger grows substantially after sunset.',category:'crime'},
  {id:'hook-165',title:'A quiet district is paying',summary:'A quiet district is paying two protection rackets. The obvious patron is withholding a crucial fact.',category:'crime'},
  {id:'hook-166',title:'A quiet district is paying',summary:'A quiet district is paying two protection rackets. A rival group is pursuing the same objective.',category:'crime'},
  {id:'hook-167',title:'A quiet district is paying',summary:'A quiet district is paying two protection rackets. Success will require cooperation with a distrusted faction.',category:'crime'},
  {id:'hook-168',title:'A quiet district is paying',summary:'A quiet district is paying two protection rackets. The danger grows substantially after sunset.',category:'crime'},
  {id:'hook-169',title:'Every clock in one manor',summary:'Every clock in one manor stopped at the same moment. The obvious patron is withholding a crucial fact.',category:'mystery'},
  {id:'hook-170',title:'Every clock in one manor',summary:'Every clock in one manor stopped at the same moment. A rival group is pursuing the same objective.',category:'mystery'},
  {id:'hook-171',title:'Every clock in one manor',summary:'Every clock in one manor stopped at the same moment. Success will require cooperation with a distrusted faction.',category:'mystery'},
  {id:'hook-172',title:'Every clock in one manor',summary:'Every clock in one manor stopped at the same moment. The danger grows substantially after sunset.',category:'mystery'},
  {id:'hook-173',title:'A dead traveler arrives with',summary:'A dead traveler arrives with tomorrow\'s newspaper. The obvious patron is withholding a crucial fact.',category:'mystery'},
  {id:'hook-174',title:'A dead traveler arrives with',summary:'A dead traveler arrives with tomorrow\'s newspaper. A rival group is pursuing the same objective.',category:'mystery'},
  {id:'hook-175',title:'A dead traveler arrives with',summary:'A dead traveler arrives with tomorrow\'s newspaper. Success will require cooperation with a distrusted faction.',category:'mystery'},
  {id:'hook-176',title:'A dead traveler arrives with',summary:'A dead traveler arrives with tomorrow\'s newspaper. The danger grows substantially after sunset.',category:'mystery'},
  {id:'hook-177',title:'Villagers remember a house that',summary:'Villagers remember a house that is not there. The obvious patron is withholding a crucial fact.',category:'mystery'},
  {id:'hook-178',title:'Villagers remember a house that',summary:'Villagers remember a house that is not there. A rival group is pursuing the same objective.',category:'mystery'},
  {id:'hook-179',title:'Villagers remember a house that',summary:'Villagers remember a house that is not there. Success will require cooperation with a distrusted faction.',category:'mystery'},
  {id:'hook-180',title:'Villagers remember a house that',summary:'Villagers remember a house that is not there. The danger grows substantially after sunset.',category:'mystery'},
  {id:'hook-181',title:'Identical letters reach strangers across',summary:'Identical letters reach strangers across the city. The obvious patron is withholding a crucial fact.',category:'mystery'},
  {id:'hook-182',title:'Identical letters reach strangers across',summary:'Identical letters reach strangers across the city. A rival group is pursuing the same objective.',category:'mystery'},
  {id:'hook-183',title:'Identical letters reach strangers across',summary:'Identical letters reach strangers across the city. Success will require cooperation with a distrusted faction.',category:'mystery'},
  {id:'hook-184',title:'Identical letters reach strangers across',summary:'Identical letters reach strangers across the city. The danger grows substantially after sunset.',category:'mystery'},
  {id:'hook-185',title:'A statue weeps water from',summary:'A statue weeps water from a distant sea. The obvious patron is withholding a crucial fact.',category:'mystery'},
  {id:'hook-186',title:'A statue weeps water from',summary:'A statue weeps water from a distant sea. A rival group is pursuing the same objective.',category:'mystery'},
  {id:'hook-187',title:'A statue weeps water from',summary:'A statue weeps water from a distant sea. Success will require cooperation with a distrusted faction.',category:'mystery'},
  {id:'hook-188',title:'A statue weeps water from',summary:'A statue weeps water from a distant sea. The danger grows substantially after sunset.',category:'mystery'},
  {id:'hook-189',title:'A witness casts no reflection',summary:'A witness casts no reflection. The obvious patron is withholding a crucial fact.',category:'mystery'},
  {id:'hook-190',title:'A witness casts no reflection',summary:'A witness casts no reflection. A rival group is pursuing the same objective.',category:'mystery'},
  {id:'hook-191',title:'A witness casts no reflection',summary:'A witness casts no reflection. Success will require cooperation with a distrusted faction.',category:'mystery'},
  {id:'hook-192',title:'A witness casts no reflection',summary:'A witness casts no reflection. The danger grows substantially after sunset.',category:'mystery'},
  {id:'hook-193',title:'A missing person appears in',summary:'A missing person appears in decades-old portraits. The obvious patron is withholding a crucial fact.',category:'mystery'},
  {id:'hook-194',title:'A missing person appears in',summary:'A missing person appears in decades-old portraits. A rival group is pursuing the same objective.',category:'mystery'},
  {id:'hook-195',title:'A missing person appears in',summary:'A missing person appears in decades-old portraits. Success will require cooperation with a distrusted faction.',category:'mystery'},
  {id:'hook-196',title:'A missing person appears in',summary:'A missing person appears in decades-old portraits. The danger grows substantially after sunset.',category:'mystery'},
  {id:'hook-197',title:'Spells near the academy produce',summary:'Spells near the academy produce unintended colors. The obvious patron is withholding a crucial fact.',category:'magic'},
  {id:'hook-198',title:'Spells near the academy produce',summary:'Spells near the academy produce unintended colors. A rival group is pursuing the same objective.',category:'magic'},
  {id:'hook-199',title:'Spells near the academy produce',summary:'Spells near the academy produce unintended colors. Success will require cooperation with a distrusted faction.',category:'magic'},
  {id:'hook-200',title:'Spells near the academy produce',summary:'Spells near the academy produce unintended colors. The danger grows substantially after sunset.',category:'magic'},
  {id:'hook-201',title:'A dormant portal now opens',summary:'A dormant portal now opens for one minute nightly. The obvious patron is withholding a crucial fact.',category:'magic'},
  {id:'hook-202',title:'A dormant portal now opens',summary:'A dormant portal now opens for one minute nightly. A rival group is pursuing the same objective.',category:'magic'},
  {id:'hook-203',title:'A dormant portal now opens',summary:'A dormant portal now opens for one minute nightly. Success will require cooperation with a distrusted faction.',category:'magic'},
  {id:'hook-204',title:'A dormant portal now opens',summary:'A dormant portal now opens for one minute nightly. The danger grows substantially after sunset.',category:'magic'},
  {id:'hook-205',title:'A familiar has begun delivering',summary:'A familiar has begun delivering unknown messages. The obvious patron is withholding a crucial fact.',category:'magic'},
  {id:'hook-206',title:'A familiar has begun delivering',summary:'A familiar has begun delivering unknown messages. A rival group is pursuing the same objective.',category:'magic'},
  {id:'hook-207',title:'A familiar has begun delivering',summary:'A familiar has begun delivering unknown messages. Success will require cooperation with a distrusted faction.',category:'magic'},
  {id:'hook-208',title:'A familiar has begun delivering',summary:'A familiar has begun delivering unknown messages. The danger grows substantially after sunset.',category:'magic'},
  {id:'hook-209',title:'A failed ritual split one',summary:'A failed ritual split one object into many realities. The obvious patron is withholding a crucial fact.',category:'magic'},
  {id:'hook-210',title:'A failed ritual split one',summary:'A failed ritual split one object into many realities. A rival group is pursuing the same objective.',category:'magic'},
  {id:'hook-211',title:'A failed ritual split one',summary:'A failed ritual split one object into many realities. Success will require cooperation with a distrusted faction.',category:'magic'},
  {id:'hook-212',title:'A failed ritual split one',summary:'A failed ritual split one object into many realities. The danger grows substantially after sunset.',category:'magic'},
  {id:'hook-213',title:'An enchanted market stall grants',summary:'An enchanted market stall grants literal wishes. The obvious patron is withholding a crucial fact.',category:'magic'},
  {id:'hook-214',title:'An enchanted market stall grants',summary:'An enchanted market stall grants literal wishes. A rival group is pursuing the same objective.',category:'magic'},
  {id:'hook-215',title:'An enchanted market stall grants',summary:'An enchanted market stall grants literal wishes. Success will require cooperation with a distrusted faction.',category:'magic'},
  {id:'hook-216',title:'An enchanted market stall grants',summary:'An enchanted market stall grants literal wishes. The danger grows substantially after sunset.',category:'magic'},
  {id:'hook-217',title:'A wizard\'s tower is slowly',summary:'A wizard\'s tower is slowly becoming weightless. The obvious patron is withholding a crucial fact.',category:'magic'},
  {id:'hook-218',title:'A wizard\'s tower is slowly',summary:'A wizard\'s tower is slowly becoming weightless. A rival group is pursuing the same objective.',category:'magic'},
  {id:'hook-219',title:'A wizard\'s tower is slowly',summary:'A wizard\'s tower is slowly becoming weightless. Success will require cooperation with a distrusted faction.',category:'magic'},
  {id:'hook-220',title:'A wizard\'s tower is slowly',summary:'A wizard\'s tower is slowly becoming weightless. The danger grows substantially after sunset.',category:'magic'},
  {id:'hook-221',title:'A spellbook is rewriting its',summary:'A spellbook is rewriting its own final page. The obvious patron is withholding a crucial fact.',category:'magic'},
  {id:'hook-222',title:'A spellbook is rewriting its',summary:'A spellbook is rewriting its own final page. A rival group is pursuing the same objective.',category:'magic'},
  {id:'hook-223',title:'A spellbook is rewriting its',summary:'A spellbook is rewriting its own final page. Success will require cooperation with a distrusted faction.',category:'magic'},
  {id:'hook-224',title:'A spellbook is rewriting its',summary:'A spellbook is rewriting its own final page. The danger grows substantially after sunset.',category:'magic'},
  {id:'hook-225',title:'An early winter has sealed',summary:'An early winter has sealed the mountain pass. The obvious patron is withholding a crucial fact.',category:'survival'},
  {id:'hook-226',title:'An early winter has sealed',summary:'An early winter has sealed the mountain pass. A rival group is pursuing the same objective.',category:'survival'},
  {id:'hook-227',title:'An early winter has sealed',summary:'An early winter has sealed the mountain pass. Success will require cooperation with a distrusted faction.',category:'survival'},
  {id:'hook-228',title:'An early winter has sealed',summary:'An early winter has sealed the mountain pass. The danger grows substantially after sunset.',category:'survival'},
  {id:'hook-229',title:'A well is drying faster',summary:'A well is drying faster than it can be filled. The obvious patron is withholding a crucial fact.',category:'survival'},
  {id:'hook-230',title:'A well is drying faster',summary:'A well is drying faster than it can be filled. A rival group is pursuing the same objective.',category:'survival'},
  {id:'hook-231',title:'A well is drying faster',summary:'A well is drying faster than it can be filled. Success will require cooperation with a distrusted faction.',category:'survival'},
  {id:'hook-232',title:'A well is drying faster',summary:'A well is drying faster than it can be filled. The danger grows substantially after sunset.',category:'survival'},
  {id:'hook-233',title:'Ashfall has turned noon into',summary:'Ashfall has turned noon into darkness. The obvious patron is withholding a crucial fact.',category:'survival'},
  {id:'hook-234',title:'Ashfall has turned noon into',summary:'Ashfall has turned noon into darkness. A rival group is pursuing the same objective.',category:'survival'},
  {id:'hook-235',title:'Ashfall has turned noon into',summary:'Ashfall has turned noon into darkness. Success will require cooperation with a distrusted faction.',category:'survival'},
  {id:'hook-236',title:'Ashfall has turned noon into',summary:'Ashfall has turned noon into darkness. The danger grows substantially after sunset.',category:'survival'},
  {id:'hook-237',title:'Refugees need a route through',summary:'Refugees need a route through monster territory. The obvious patron is withholding a crucial fact.',category:'survival'},
  {id:'hook-238',title:'Refugees need a route through',summary:'Refugees need a route through monster territory. A rival group is pursuing the same objective.',category:'survival'},
  {id:'hook-239',title:'Refugees need a route through',summary:'Refugees need a route through monster territory. Success will require cooperation with a distrusted faction.',category:'survival'},
  {id:'hook-240',title:'Refugees need a route through',summary:'Refugees need a route through monster territory. The danger grows substantially after sunset.',category:'survival'},
  {id:'hook-241',title:'A ship is stranded beyond',summary:'A ship is stranded beyond the reach of tides. The obvious patron is withholding a crucial fact.',category:'survival'},
  {id:'hook-242',title:'A ship is stranded beyond',summary:'A ship is stranded beyond the reach of tides. A rival group is pursuing the same objective.',category:'survival'},
  {id:'hook-243',title:'A ship is stranded beyond',summary:'A ship is stranded beyond the reach of tides. Success will require cooperation with a distrusted faction.',category:'survival'},
  {id:'hook-244',title:'A ship is stranded beyond',summary:'A ship is stranded beyond the reach of tides. The danger grows substantially after sunset.',category:'survival'},
  {id:'hook-245',title:'A blight is moving from',summary:'A blight is moving from field to field. The obvious patron is withholding a crucial fact.',category:'survival'},
  {id:'hook-246',title:'A blight is moving from',summary:'A blight is moving from field to field. A rival group is pursuing the same objective.',category:'survival'},
  {id:'hook-247',title:'A blight is moving from',summary:'A blight is moving from field to field. Success will require cooperation with a distrusted faction.',category:'survival'},
  {id:'hook-248',title:'A blight is moving from',summary:'A blight is moving from field to field. The danger grows substantially after sunset.',category:'survival'},
  {id:'hook-249',title:'A planar storm makes ordinary',summary:'A planar storm makes ordinary shelter unsafe. The obvious patron is withholding a crucial fact.',category:'survival'},
  {id:'hook-250',title:'A planar storm makes ordinary',summary:'A planar storm makes ordinary shelter unsafe. A rival group is pursuing the same objective.',category:'survival'},
  {id:'hook-251',title:'A planar storm makes ordinary',summary:'A planar storm makes ordinary shelter unsafe. Success will require cooperation with a distrusted faction.',category:'survival'},
  {id:'hook-252',title:'A planar storm makes ordinary',summary:'A planar storm makes ordinary shelter unsafe. The danger grows substantially after sunset.',category:'survival'},
] as const satisfies readonly HookData[];
