import type { LanguageData } from '../types';

export const LANGUAGES = [
  {id:'common',name:'Common',category:'standard',script:'Common',parentLanguageId:null,typicalSpeakers:['Humans','cosmopolitan peoples']},
  {id:'dwarvish',name:'Dwarvish',category:'standard',script:'Dwarvish',parentLanguageId:null,typicalSpeakers:['Dwarves']},
  {id:'elvish',name:'Elvish',category:'standard',script:'Elvish',parentLanguageId:null,typicalSpeakers:['Elves']},
  {id:'giant',name:'Giant',category:'standard',script:'Dwarvish',parentLanguageId:null,typicalSpeakers:['Giants','ogres']},
  {id:'gnomish',name:'Gnomish',category:'standard',script:'Dwarvish',parentLanguageId:null,typicalSpeakers:['Gnomes']},
  {id:'goblin',name:'Goblin',category:'standard',script:'Dwarvish',parentLanguageId:null,typicalSpeakers:['Goblinoids']},
  {id:'halfling',name:'Halfling',category:'standard',script:'Common',parentLanguageId:null,typicalSpeakers:['Halflings']},
  {id:'orc',name:'Orc',category:'standard',script:'Dwarvish',parentLanguageId:null,typicalSpeakers:['Orcs']},
  {id:'abyssal',name:'Abyssal',category:'exotic',script:'Infernal',parentLanguageId:null,typicalSpeakers:['Demons']},
  {id:'celestial',name:'Celestial',category:'exotic',script:'Celestial',parentLanguageId:null,typicalSpeakers:['Celestials']},
  {id:'draconic',name:'Draconic',category:'exotic',script:'Draconic',parentLanguageId:null,typicalSpeakers:['Dragons','dragonborn']},
  {id:'deep-speech',name:'Deep Speech',category:'exotic',script:null,parentLanguageId:null,typicalSpeakers:['Aberrations']},
  {id:'infernal',name:'Infernal',category:'exotic',script:'Infernal',parentLanguageId:null,typicalSpeakers:['Devils']},
  {id:'primordial',name:'Primordial',category:'exotic',script:'Dwarvish',parentLanguageId:null,typicalSpeakers:['Elementals']},
  {id:'sylvan',name:'Sylvan',category:'exotic',script:'Elvish',parentLanguageId:null,typicalSpeakers:['Fey']},
  {id:'undercommon',name:'Undercommon',category:'exotic',script:'Elvish',parentLanguageId:null,typicalSpeakers:['Underdark traders']},
  {id:'aquan',name:'Aquan',category:'dialect',script:'Dwarvish',parentLanguageId:'primordial',typicalSpeakers:['Water elementals']},
  {id:'auran',name:'Auran',category:'dialect',script:'Dwarvish',parentLanguageId:'primordial',typicalSpeakers:['Air elementals']},
  {id:'ignan',name:'Ignan',category:'dialect',script:'Dwarvish',parentLanguageId:'primordial',typicalSpeakers:['Fire elementals']},
  {id:'terran',name:'Terran',category:'dialect',script:'Dwarvish',parentLanguageId:'primordial',typicalSpeakers:['Earth elementals']},
  {id:'druidic',name:'Druidic',category:'secret',script:null,parentLanguageId:null,typicalSpeakers:['Druids']},
  {id:'thieves-cant',name:"Thieves' Cant",category:'secret',script:null,parentLanguageId:null,typicalSpeakers:['Rogues','criminal networks']},
  {id:'aarakocra',name:'Aarakocra',category:'setting',script:null,parentLanguageId:null,typicalSpeakers:['Aarakocra']},
  {id:'gith',name:'Gith',category:'setting',script:'Tir’su',parentLanguageId:null,typicalSpeakers:['Githyanki','githzerai']},
  {id:'minotaur',name:'Minotaur',category:'setting',script:'Dwarvish',parentLanguageId:null,typicalSpeakers:['Minotaurs']},
  {id:'vedalken',name:'Vedalken',category:'setting',script:'Vedalken',parentLanguageId:null,typicalSpeakers:['Vedalken']},
  {id:'quori',name:'Quori',category:'setting',script:'Quori',parentLanguageId:null,typicalSpeakers:['Quori','kalashtar']},
  {id:'daelkyr',name:'Daelkyr',category:'setting',script:'Daelkyr',parentLanguageId:null,typicalSpeakers:['Daelkyr','symbionts']},
  {id:'rikka',name:'Riedran',category:'setting',script:'Quori',parentLanguageId:null,typicalSpeakers:['Riedrans']},
  {id:'loross',name:'Loross',category:'setting',script:'Draconic',parentLanguageId:null,typicalSpeakers:['Netherese scholars']},
  {id:'bothii',name:'Bothii',category:'setting',script:null,parentLanguageId:null,typicalSpeakers:['Uthgardt tribes']},
  {id:'gnoll',name:'Gnoll',category:'setting',script:null,parentLanguageId:null,typicalSpeakers:['Gnolls']},
  {id:'grung',name:'Grung',category:'setting',script:null,parentLanguageId:null,typicalSpeakers:['Grungs']},
  {id:'leonin',name:'Leonin',category:'setting',script:'Common',parentLanguageId:null,typicalSpeakers:['Leonin']},
  {id:'loxodon',name:'Loxodon',category:'setting',script:'Elvish',parentLanguageId:null,typicalSpeakers:['Loxodons']},
  {id:'marquesian',name:'Marquesian',category:'setting',script:'Common',parentLanguageId:null,typicalSpeakers:['People of Marquet']},
  {id:'naush',name:'Naush',category:'setting',script:'Common',parentLanguageId:null,typicalSpeakers:['Sailors of the Menagerie Coast']},
  {id:'netherese',name:'Netherese',category:'setting',script:'Draconic',parentLanguageId:null,typicalSpeakers:['Netherese arcanists']},
  {id:'olman',name:'Olman',category:'setting',script:'Olman',parentLanguageId:null,typicalSpeakers:['Olman peoples']},
  {id:'sahuagin',name:'Sahuagin',category:'setting',script:null,parentLanguageId:null,typicalSpeakers:['Sahuagin']},
  {id:'thri-kreen',name:'Thri-kreen',category:'setting',script:null,parentLanguageId:null,typicalSpeakers:['Thri-kreen']},
  {id:'zemnian',name:'Zemnian',category:'setting',script:'Dwarvish',parentLanguageId:null,typicalSpeakers:['People of the Dwendalian Empire']},
  {id:'giant-eagle',name:'Giant Eagle',category:'setting',script:null,parentLanguageId:null,typicalSpeakers:['Giant eagles']},
  {id:'giant-elk',name:'Giant Elk',category:'setting',script:null,parentLanguageId:null,typicalSpeakers:['Giant elk']},
  {id:'giant-owl',name:'Giant Owl',category:'setting',script:null,parentLanguageId:null,typicalSpeakers:['Giant owls']},
  {id:'blink-dog',name:'Blink Dog',category:'setting',script:null,parentLanguageId:null,typicalSpeakers:['Blink dogs']},
  {id:'winter-wolf',name:'Winter Wolf',category:'setting',script:null,parentLanguageId:null,typicalSpeakers:['Winter wolves']},
  {id:'yeti',name:'Yeti',category:'setting',script:null,parentLanguageId:null,typicalSpeakers:['Yetis']},
] as const satisfies readonly LanguageData[];
