import { Alignment } from '../types';
import type { DeityData } from '../types';

export const RELIGIONS = [
  {id:'auril',name:'Auril',alignment:Alignment.NeutralEvil,domains:['Nature','Tempest'],followers:['winter cultists','survivalists'],description:'Embodies winter\'s merciless cold and the fear it commands.'},
  {id:'azuth',name:'Azuth',alignment:Alignment.LawfulNeutral,domains:['Knowledge'],followers:['wizards','arcane teachers'],description:'Patron of wizards, spellcraft, and disciplined arcane study.'},
  {id:'bane',name:'Bane',alignment:Alignment.LawfulEvil,domains:['Order','War'],followers:['tyrants','conquerors'],description:'God of tyranny, domination, and imposed order.'},
  {id:'beshaba',name:'Beshaba',alignment:Alignment.ChaoticEvil,domains:['Trickery'],followers:['gamblers','the unlucky'],description:'Goddess of misfortune, accidents, and cruel chance.'},
  {id:'bhaal',name:'Bhaal',alignment:Alignment.NeutralEvil,domains:['Death'],followers:['assassins','murder cults'],description:'God of murder, ritual killing, and violent death.'},
  {id:'chauntea',name:'Chauntea',alignment:Alignment.NeutralGood,domains:['Life','Nature'],followers:['farmers','gardeners'],description:'Goddess of agriculture, cultivated life, and patient growth.'},
  {id:'cyric',name:'Cyric',alignment:Alignment.ChaoticEvil,domains:['Trickery'],followers:['liars','schemers'],description:'God of lies, strife, and treacherous ambition.'},
  {id:'deneir',name:'Deneir',alignment:Alignment.NeutralGood,domains:['Knowledge'],followers:['scribes','cartographers'],description:'God of writing, glyphs, literature, and recorded knowledge.'},
  {id:'eldath',name:'Eldath',alignment:Alignment.NeutralGood,domains:['Life','Nature'],followers:['pacifists','healers'],description:'Goddess of peace, still waters, and quiet sanctuary.'},
  {id:'gond',name:'Gond',alignment:Alignment.TrueNeutral,domains:['Forge','Knowledge'],followers:['artisans','inventors'],description:'God of craft, construction, invention, and practical innovation.'},
  {id:'helm',name:'Helm',alignment:Alignment.LawfulNeutral,domains:['Life','Light','Order'],followers:['guards','watchers'],description:'God of vigilance, protection, and unwavering guardianship.'},
  {id:'ilmater',name:'Ilmater',alignment:Alignment.LawfulGood,domains:['Life'],followers:['healers','the oppressed'],description:'God of endurance, compassion, and bearing suffering for others.'},
  {id:'kelemvor',name:'Kelemvor',alignment:Alignment.LawfulNeutral,domains:['Death','Grave'],followers:['undertakers','judges'],description:'God who oversees the dead and the just passage beyond life.'},
  {id:'lathander',name:'Lathander',alignment:Alignment.NeutralGood,domains:['Life','Light'],followers:['artists','reformers'],description:'God of dawn, renewal, birth, and hopeful beginnings.'},
  {id:'leira',name:'Leira',alignment:Alignment.ChaoticNeutral,domains:['Trickery'],followers:['illusionists','deceivers'],description:'Goddess of illusion, mist, and concealed truth.'},
  {id:'lliira',name:'Lliira',alignment:Alignment.ChaoticGood,domains:['Life'],followers:['performers','festival keepers'],description:'Goddess of joy, liberty, dance, and celebration.'},
  {id:'loviatar',name:'Loviatar',alignment:Alignment.LawfulEvil,domains:['Death'],followers:['torturers','cruel disciplinarians'],description:'Goddess of pain, punishment, and deliberate suffering.'},
  {id:'malar',name:'Malar',alignment:Alignment.ChaoticEvil,domains:['Nature'],followers:['hunters','lycanthropes'],description:'God of predation, bloodlust, and the savage hunt.'},
  {id:'mask',name:'Mask',alignment:Alignment.ChaoticNeutral,domains:['Trickery'],followers:['thieves','spies'],description:'God of shadows, thieves, and concealed designs.'},
  {id:'milil',name:'Milil',alignment:Alignment.NeutralGood,domains:['Light'],followers:['poets','musicians'],description:'God of poetry, song, eloquence, and performance.'},
  {id:'myrkul',name:'Myrkul',alignment:Alignment.NeutralEvil,domains:['Death'],followers:['necromancers','death cultists'],description:'God of death\'s dread, decay, and fear of mortality.'},
  {id:'mystra',name:'Mystra',alignment:Alignment.NeutralGood,domains:['Knowledge','Arcana'],followers:['wizards','spellcasters'],description:'Goddess of magic and steward of the Weave.'},
  {id:'oghma',name:'Oghma',alignment:Alignment.TrueNeutral,domains:['Knowledge'],followers:['scholars','bards'],description:'God of knowledge, inspiration, invention, and shared ideas.'},
  {id:'savras',name:'Savras',alignment:Alignment.LawfulNeutral,domains:['Knowledge'],followers:['diviners','fate seekers'],description:'God of divination, fate, and truths revealed.'},
  {id:'selune',name:'Selûne',alignment:Alignment.ChaoticGood,domains:['Knowledge','Life','Twilight'],followers:['navigators','lycanthropes'],description:'Goddess of the moon, stars, navigation, and change.'},
  {id:'shar',name:'Shar',alignment:Alignment.NeutralEvil,domains:['Death','Trickery'],followers:['mourners','nihilists'],description:'Goddess of darkness, loss, secrets, and forgetfulness.'},
  {id:'silvanus',name:'Silvanus',alignment:Alignment.TrueNeutral,domains:['Nature'],followers:['druids','wildland guardians'],description:'God of untamed nature and the balance of the wild.'},
  {id:'sune',name:'Sune',alignment:Alignment.ChaoticGood,domains:['Life','Light'],followers:['artists','lovers'],description:'Goddess of beauty, love, passion, and artistic expression.'},
  {id:'talona',name:'Talona',alignment:Alignment.ChaoticEvil,domains:['Death'],followers:['poisoners','the diseased'],description:'Goddess of poison, disease, and corruption.'},
  {id:'talos',name:'Talos',alignment:Alignment.ChaoticEvil,domains:['Tempest'],followers:['raiders','storm cultists'],description:'God of storms, destruction, earthquakes, and ruin.'},
  {id:'tempus',name:'Tempus',alignment:Alignment.TrueNeutral,domains:['War'],followers:['soldiers','warriors'],description:'God of battle, martial courage, and honorable combat.'},
  {id:'torm',name:'Torm',alignment:Alignment.LawfulGood,domains:['War'],followers:['paladins','loyal servants'],description:'God of duty, loyalty, righteousness, and courageous service.'},
  {id:'tymora',name:'Tymora',alignment:Alignment.ChaoticGood,domains:['Trickery'],followers:['adventurers','gamblers'],description:'Goddess of good fortune, daring, and favorable chance.'},
  {id:'tyr',name:'Tyr',alignment:Alignment.LawfulGood,domains:['Order','War'],followers:['judges','knights'],description:'God of justice, law, and measured punishment.'},
  {id:'umberlee',name:'Umberlee',alignment:Alignment.ChaoticEvil,domains:['Tempest'],followers:['sailors','coastal folk'],description:'Goddess of the sea\'s destructive power and caprice.'},
  {id:'waukeen',name:'Waukeen',alignment:Alignment.TrueNeutral,domains:['Knowledge','Trickery'],followers:['merchants','traders'],description:'Goddess of trade, wealth, commerce, and negotiation.'},
  {id:'moradin',name:'Moradin',alignment:Alignment.LawfulGood,domains:['Forge','Knowledge'],followers:['dwarves','smiths'],description:'Dwarven creator god of craft, clans, and the forge.'},
  {id:'corellon',name:'Corellon',alignment:Alignment.ChaoticGood,domains:['Arcana','Light'],followers:['elves','artists'],description:'Elven deity of art, magic, beauty, and self-expression.'},
  {id:'gruumsh',name:'Gruumsh',alignment:Alignment.ChaoticEvil,domains:['Tempest','War'],followers:['orcs','warriors'],description:'Orc deity of conquest, strength, and survival through conflict.'},
  {id:'garl-glittergold',name:'Garl Glittergold',alignment:Alignment.LawfulGood,domains:['Trickery'],followers:['gnomes','jewelers'],description:'Gnome god of humor, craft, community, and protection.'},
  {id:'yondalla',name:'Yondalla',alignment:Alignment.LawfulGood,domains:['Life'],followers:['halflings','homemakers'],description:'Halfling goddess of fertility, protection, and home.'},
  {id:'bahamut',name:'Bahamut',alignment:Alignment.LawfulGood,domains:['Life','War'],followers:['dragonborn','paladins'],description:'Platinum dragon god of justice, honor, and protection.'},
  {id:'tiamat',name:'Tiamat',alignment:Alignment.LawfulEvil,domains:['Trickery','War'],followers:['chromatic dragons','conquerors'],description:'Five-headed dragon goddess of greed, vengeance, and domination.'},
  {id:'lolth',name:'Lolth',alignment:Alignment.ChaoticEvil,domains:['Trickery'],followers:['drow cultists','spiders'],description:'Drow goddess of spiders, schemes, and ruthless hierarchy.'},
  {id:'eilistraee',name:'Eilistraee',alignment:Alignment.ChaoticGood,domains:['Light','Nature'],followers:['drow exiles','artists'],description:'Drow goddess of moonlight, song, freedom, and redemption.'},
  {id:'valkur',name:'Valkur',alignment:Alignment.ChaoticGood,domains:['Tempest'],followers:['sailors','explorers'],description:'Heroic god of favorable winds, sailors, and bold voyages.'},
  {id:'hoar',name:'Hoar',alignment:Alignment.LawfulNeutral,domains:['War'],followers:['avengers','judges'],description:'God of retribution, poetic justice, and deserved consequence.'},
  {id:'jergal',name:'Jergal',alignment:Alignment.LawfulNeutral,domains:['Death','Knowledge'],followers:['scribes of the dead','undertakers'],description:'Ancient seneschal of death who records each mortal ending.'},
] as const satisfies readonly DeityData[];
