import { RiskLevel } from '../types';
import type { SecretData } from '../types';

export const SECRETS = [
  {id:'secret-001',description:'They concealed their true birthplace quietly, and only an old friend has proof.',severity:RiskLevel.Trivial},
  {id:'secret-002',description:'They owes money to a criminal lender quietly, while a rival is close to discovering it.',severity:RiskLevel.Trivial},
  {id:'secret-003',description:'They uses a name taken from the dead quietly, and exposure would end a valued relationship.',severity:RiskLevel.Trivial},
  {id:'secret-004',description:'They betrayed a former employer quietly, but the evidence is hidden nearby.',severity:RiskLevel.Trivial},
  {id:'secret-005',description:'They witnessed an unsolved murder quietly, and someone innocent currently bears the blame.',severity:RiskLevel.Trivial},
  {id:'secret-006',description:'They possesses a stolen family heirloom quietly, and only an old friend has proof.',severity:RiskLevel.Trivial},
  {id:'secret-007',description:'They belongs to a forbidden society quietly, while a rival is close to discovering it.',severity:RiskLevel.Trivial},
  {id:'secret-008',description:'They has an unrecognized child quietly, and exposure would end a valued relationship.',severity:RiskLevel.Trivial},
  {id:'secret-009',description:'They falsified an important credential quietly, but the evidence is hidden nearby.',severity:RiskLevel.Trivial},
  {id:'secret-010',description:'They knows a noble\'s hidden parentage quietly, and someone innocent currently bears the blame.',severity:RiskLevel.Trivial},
  {id:'secret-011',description:'They concealed their true birthplace years ago, while a rival is close to discovering it.',severity:RiskLevel.Trivial},
  {id:'secret-012',description:'They owes money to a criminal lender years ago, and exposure would end a valued relationship.',severity:RiskLevel.Trivial},
  {id:'secret-013',description:'They uses a name taken from the dead years ago, but the evidence is hidden nearby.',severity:RiskLevel.Trivial},
  {id:'secret-014',description:'They betrayed a former employer years ago, and someone innocent currently bears the blame.',severity:RiskLevel.Trivial},
  {id:'secret-015',description:'They witnessed an unsolved murder years ago, and only an old friend has proof.',severity:RiskLevel.Trivial},
  {id:'secret-016',description:'They possesses a stolen family heirloom years ago, while a rival is close to discovering it.',severity:RiskLevel.Trivial},
  {id:'secret-017',description:'They belongs to a forbidden society years ago, and exposure would end a valued relationship.',severity:RiskLevel.Trivial},
  {id:'secret-018',description:'They has an unrecognized child years ago, but the evidence is hidden nearby.',severity:RiskLevel.Trivial},
  {id:'secret-019',description:'They falsified an important credential years ago, and someone innocent currently bears the blame.',severity:RiskLevel.Trivial},
  {id:'secret-020',description:'They knows a noble\'s hidden parentage years ago, and only an old friend has proof.',severity:RiskLevel.Trivial},
  {id:'secret-021',description:'They concealed their true birthplace under pressure, and exposure would end a valued relationship.',severity:RiskLevel.Trivial},
  {id:'secret-022',description:'They owes money to a criminal lender under pressure, but the evidence is hidden nearby.',severity:RiskLevel.Trivial},
  {id:'secret-023',description:'They uses a name taken from the dead under pressure, and someone innocent currently bears the blame.',severity:RiskLevel.Trivial},
  {id:'secret-024',description:'They betrayed a former employer under pressure, and only an old friend has proof.',severity:RiskLevel.Trivial},
  {id:'secret-025',description:'They witnessed an unsolved murder under pressure, while a rival is close to discovering it.',severity:RiskLevel.Trivial},
  {id:'secret-026',description:'They possesses a stolen family heirloom under pressure, and exposure would end a valued relationship.',severity:RiskLevel.Trivial},
  {id:'secret-027',description:'They belongs to a forbidden society under pressure, but the evidence is hidden nearby.',severity:RiskLevel.Trivial},
  {id:'secret-028',description:'They has an unrecognized child under pressure, and someone innocent currently bears the blame.',severity:RiskLevel.Trivial},
  {id:'secret-029',description:'They falsified an important credential under pressure, and only an old friend has proof.',severity:RiskLevel.Trivial},
  {id:'secret-030',description:'They knows a noble\'s hidden parentage under pressure, while a rival is close to discovering it.',severity:RiskLevel.Trivial},
  {id:'secret-031',description:'They concealed their true birthplace to protect someone, but the evidence is hidden nearby.',severity:RiskLevel.Trivial},
  {id:'secret-032',description:'They owes money to a criminal lender to protect someone, and someone innocent currently bears the blame.',severity:RiskLevel.Trivial},
  {id:'secret-033',description:'They uses a name taken from the dead to protect someone, and only an old friend has proof.',severity:RiskLevel.Trivial},
  {id:'secret-034',description:'They betrayed a former employer to protect someone, while a rival is close to discovering it.',severity:RiskLevel.Trivial},
  {id:'secret-035',description:'They witnessed an unsolved murder to protect someone, and exposure would end a valued relationship.',severity:RiskLevel.Trivial},
  {id:'secret-036',description:'They possesses a stolen family heirloom to protect someone, but the evidence is hidden nearby.',severity:RiskLevel.Trivial},
  {id:'secret-037',description:'They belongs to a forbidden society to protect someone, and someone innocent currently bears the blame.',severity:RiskLevel.Trivial},
  {id:'secret-038',description:'They has an unrecognized child to protect someone, and only an old friend has proof.',severity:RiskLevel.Trivial},
  {id:'secret-039',description:'They falsified an important credential to protect someone, while a rival is close to discovering it.',severity:RiskLevel.Trivial},
  {id:'secret-040',description:'They knows a noble\'s hidden parentage to protect someone, and exposure would end a valued relationship.',severity:RiskLevel.Trivial},
  {id:'secret-041',description:'They concealed their true birthplace for personal gain, and someone innocent currently bears the blame.',severity:RiskLevel.Trivial},
  {id:'secret-042',description:'They owes money to a criminal lender for personal gain, and only an old friend has proof.',severity:RiskLevel.Trivial},
  {id:'secret-043',description:'They uses a name taken from the dead for personal gain, while a rival is close to discovering it.',severity:RiskLevel.Trivial},
  {id:'secret-044',description:'They betrayed a former employer for personal gain, and exposure would end a valued relationship.',severity:RiskLevel.Trivial},
  {id:'secret-045',description:'They witnessed an unsolved murder for personal gain, but the evidence is hidden nearby.',severity:RiskLevel.Trivial},
  {id:'secret-046',description:'They possesses a stolen family heirloom for personal gain, and someone innocent currently bears the blame.',severity:RiskLevel.Trivial},
  {id:'secret-047',description:'They belongs to a forbidden society for personal gain, and only an old friend has proof.',severity:RiskLevel.Trivial},
  {id:'secret-048',description:'They has an unrecognized child for personal gain, while a rival is close to discovering it.',severity:RiskLevel.Trivial},
  {id:'secret-049',description:'They falsified an important credential for personal gain, and exposure would end a valued relationship.',severity:RiskLevel.Trivial},
  {id:'secret-050',description:'They knows a noble\'s hidden parentage for personal gain, but the evidence is hidden nearby.',severity:RiskLevel.Trivial},
  {id:'secret-051',description:'They concealed their true birthplace quietly, and only an old friend has proof.',severity:RiskLevel.Low},
  {id:'secret-052',description:'They owes money to a criminal lender quietly, while a rival is close to discovering it.',severity:RiskLevel.Low},
  {id:'secret-053',description:'They uses a name taken from the dead quietly, and exposure would end a valued relationship.',severity:RiskLevel.Low},
  {id:'secret-054',description:'They betrayed a former employer quietly, but the evidence is hidden nearby.',severity:RiskLevel.Low},
  {id:'secret-055',description:'They witnessed an unsolved murder quietly, and someone innocent currently bears the blame.',severity:RiskLevel.Low},
  {id:'secret-056',description:'They possesses a stolen family heirloom quietly, and only an old friend has proof.',severity:RiskLevel.Low},
  {id:'secret-057',description:'They belongs to a forbidden society quietly, while a rival is close to discovering it.',severity:RiskLevel.Low},
  {id:'secret-058',description:'They has an unrecognized child quietly, and exposure would end a valued relationship.',severity:RiskLevel.Low},
  {id:'secret-059',description:'They falsified an important credential quietly, but the evidence is hidden nearby.',severity:RiskLevel.Low},
  {id:'secret-060',description:'They knows a noble\'s hidden parentage quietly, and someone innocent currently bears the blame.',severity:RiskLevel.Low},
  {id:'secret-061',description:'They concealed their true birthplace years ago, while a rival is close to discovering it.',severity:RiskLevel.Low},
  {id:'secret-062',description:'They owes money to a criminal lender years ago, and exposure would end a valued relationship.',severity:RiskLevel.Low},
  {id:'secret-063',description:'They uses a name taken from the dead years ago, but the evidence is hidden nearby.',severity:RiskLevel.Low},
  {id:'secret-064',description:'They betrayed a former employer years ago, and someone innocent currently bears the blame.',severity:RiskLevel.Low},
  {id:'secret-065',description:'They witnessed an unsolved murder years ago, and only an old friend has proof.',severity:RiskLevel.Low},
  {id:'secret-066',description:'They possesses a stolen family heirloom years ago, while a rival is close to discovering it.',severity:RiskLevel.Low},
  {id:'secret-067',description:'They belongs to a forbidden society years ago, and exposure would end a valued relationship.',severity:RiskLevel.Low},
  {id:'secret-068',description:'They has an unrecognized child years ago, but the evidence is hidden nearby.',severity:RiskLevel.Low},
  {id:'secret-069',description:'They falsified an important credential years ago, and someone innocent currently bears the blame.',severity:RiskLevel.Low},
  {id:'secret-070',description:'They knows a noble\'s hidden parentage years ago, and only an old friend has proof.',severity:RiskLevel.Low},
  {id:'secret-071',description:'They concealed their true birthplace under pressure, and exposure would end a valued relationship.',severity:RiskLevel.Low},
  {id:'secret-072',description:'They owes money to a criminal lender under pressure, but the evidence is hidden nearby.',severity:RiskLevel.Low},
  {id:'secret-073',description:'They uses a name taken from the dead under pressure, and someone innocent currently bears the blame.',severity:RiskLevel.Low},
  {id:'secret-074',description:'They betrayed a former employer under pressure, and only an old friend has proof.',severity:RiskLevel.Low},
  {id:'secret-075',description:'They witnessed an unsolved murder under pressure, while a rival is close to discovering it.',severity:RiskLevel.Low},
  {id:'secret-076',description:'They possesses a stolen family heirloom under pressure, and exposure would end a valued relationship.',severity:RiskLevel.Low},
  {id:'secret-077',description:'They belongs to a forbidden society under pressure, but the evidence is hidden nearby.',severity:RiskLevel.Low},
  {id:'secret-078',description:'They has an unrecognized child under pressure, and someone innocent currently bears the blame.',severity:RiskLevel.Low},
  {id:'secret-079',description:'They falsified an important credential under pressure, and only an old friend has proof.',severity:RiskLevel.Low},
  {id:'secret-080',description:'They knows a noble\'s hidden parentage under pressure, while a rival is close to discovering it.',severity:RiskLevel.Low},
  {id:'secret-081',description:'They concealed their true birthplace to protect someone, but the evidence is hidden nearby.',severity:RiskLevel.Low},
  {id:'secret-082',description:'They owes money to a criminal lender to protect someone, and someone innocent currently bears the blame.',severity:RiskLevel.Low},
  {id:'secret-083',description:'They uses a name taken from the dead to protect someone, and only an old friend has proof.',severity:RiskLevel.Low},
  {id:'secret-084',description:'They betrayed a former employer to protect someone, while a rival is close to discovering it.',severity:RiskLevel.Low},
  {id:'secret-085',description:'They witnessed an unsolved murder to protect someone, and exposure would end a valued relationship.',severity:RiskLevel.Low},
  {id:'secret-086',description:'They possesses a stolen family heirloom to protect someone, but the evidence is hidden nearby.',severity:RiskLevel.Low},
  {id:'secret-087',description:'They belongs to a forbidden society to protect someone, and someone innocent currently bears the blame.',severity:RiskLevel.Low},
  {id:'secret-088',description:'They has an unrecognized child to protect someone, and only an old friend has proof.',severity:RiskLevel.Low},
  {id:'secret-089',description:'They falsified an important credential to protect someone, while a rival is close to discovering it.',severity:RiskLevel.Low},
  {id:'secret-090',description:'They knows a noble\'s hidden parentage to protect someone, and exposure would end a valued relationship.',severity:RiskLevel.Low},
  {id:'secret-091',description:'They concealed their true birthplace for personal gain, and someone innocent currently bears the blame.',severity:RiskLevel.Low},
  {id:'secret-092',description:'They owes money to a criminal lender for personal gain, and only an old friend has proof.',severity:RiskLevel.Low},
  {id:'secret-093',description:'They uses a name taken from the dead for personal gain, while a rival is close to discovering it.',severity:RiskLevel.Low},
  {id:'secret-094',description:'They betrayed a former employer for personal gain, and exposure would end a valued relationship.',severity:RiskLevel.Low},
  {id:'secret-095',description:'They witnessed an unsolved murder for personal gain, but the evidence is hidden nearby.',severity:RiskLevel.Low},
  {id:'secret-096',description:'They possesses a stolen family heirloom for personal gain, and someone innocent currently bears the blame.',severity:RiskLevel.Low},
  {id:'secret-097',description:'They belongs to a forbidden society for personal gain, and only an old friend has proof.',severity:RiskLevel.Low},
  {id:'secret-098',description:'They has an unrecognized child for personal gain, while a rival is close to discovering it.',severity:RiskLevel.Low},
  {id:'secret-099',description:'They falsified an important credential for personal gain, and exposure would end a valued relationship.',severity:RiskLevel.Low},
  {id:'secret-100',description:'They knows a noble\'s hidden parentage for personal gain, but the evidence is hidden nearby.',severity:RiskLevel.Low},
  {id:'secret-101',description:'They concealed their true birthplace quietly, and only an old friend has proof.',severity:RiskLevel.Moderate},
  {id:'secret-102',description:'They owes money to a criminal lender quietly, while a rival is close to discovering it.',severity:RiskLevel.Moderate},
  {id:'secret-103',description:'They uses a name taken from the dead quietly, and exposure would end a valued relationship.',severity:RiskLevel.Moderate},
  {id:'secret-104',description:'They betrayed a former employer quietly, but the evidence is hidden nearby.',severity:RiskLevel.Moderate},
  {id:'secret-105',description:'They witnessed an unsolved murder quietly, and someone innocent currently bears the blame.',severity:RiskLevel.Moderate},
  {id:'secret-106',description:'They possesses a stolen family heirloom quietly, and only an old friend has proof.',severity:RiskLevel.Moderate},
  {id:'secret-107',description:'They belongs to a forbidden society quietly, while a rival is close to discovering it.',severity:RiskLevel.Moderate},
  {id:'secret-108',description:'They has an unrecognized child quietly, and exposure would end a valued relationship.',severity:RiskLevel.Moderate},
  {id:'secret-109',description:'They falsified an important credential quietly, but the evidence is hidden nearby.',severity:RiskLevel.Moderate},
  {id:'secret-110',description:'They knows a noble\'s hidden parentage quietly, and someone innocent currently bears the blame.',severity:RiskLevel.Moderate},
  {id:'secret-111',description:'They concealed their true birthplace years ago, while a rival is close to discovering it.',severity:RiskLevel.Moderate},
  {id:'secret-112',description:'They owes money to a criminal lender years ago, and exposure would end a valued relationship.',severity:RiskLevel.Moderate},
  {id:'secret-113',description:'They uses a name taken from the dead years ago, but the evidence is hidden nearby.',severity:RiskLevel.Moderate},
  {id:'secret-114',description:'They betrayed a former employer years ago, and someone innocent currently bears the blame.',severity:RiskLevel.Moderate},
  {id:'secret-115',description:'They witnessed an unsolved murder years ago, and only an old friend has proof.',severity:RiskLevel.Moderate},
  {id:'secret-116',description:'They possesses a stolen family heirloom years ago, while a rival is close to discovering it.',severity:RiskLevel.Moderate},
  {id:'secret-117',description:'They belongs to a forbidden society years ago, and exposure would end a valued relationship.',severity:RiskLevel.Moderate},
  {id:'secret-118',description:'They has an unrecognized child years ago, but the evidence is hidden nearby.',severity:RiskLevel.Moderate},
  {id:'secret-119',description:'They falsified an important credential years ago, and someone innocent currently bears the blame.',severity:RiskLevel.Moderate},
  {id:'secret-120',description:'They knows a noble\'s hidden parentage years ago, and only an old friend has proof.',severity:RiskLevel.Moderate},
  {id:'secret-121',description:'They concealed their true birthplace under pressure, and exposure would end a valued relationship.',severity:RiskLevel.Moderate},
  {id:'secret-122',description:'They owes money to a criminal lender under pressure, but the evidence is hidden nearby.',severity:RiskLevel.Moderate},
  {id:'secret-123',description:'They uses a name taken from the dead under pressure, and someone innocent currently bears the blame.',severity:RiskLevel.Moderate},
  {id:'secret-124',description:'They betrayed a former employer under pressure, and only an old friend has proof.',severity:RiskLevel.Moderate},
  {id:'secret-125',description:'They witnessed an unsolved murder under pressure, while a rival is close to discovering it.',severity:RiskLevel.Moderate},
  {id:'secret-126',description:'They possesses a stolen family heirloom under pressure, and exposure would end a valued relationship.',severity:RiskLevel.Moderate},
  {id:'secret-127',description:'They belongs to a forbidden society under pressure, but the evidence is hidden nearby.',severity:RiskLevel.Moderate},
  {id:'secret-128',description:'They has an unrecognized child under pressure, and someone innocent currently bears the blame.',severity:RiskLevel.Moderate},
  {id:'secret-129',description:'They falsified an important credential under pressure, and only an old friend has proof.',severity:RiskLevel.Moderate},
  {id:'secret-130',description:'They knows a noble\'s hidden parentage under pressure, while a rival is close to discovering it.',severity:RiskLevel.Moderate},
  {id:'secret-131',description:'They concealed their true birthplace to protect someone, but the evidence is hidden nearby.',severity:RiskLevel.Moderate},
  {id:'secret-132',description:'They owes money to a criminal lender to protect someone, and someone innocent currently bears the blame.',severity:RiskLevel.Moderate},
  {id:'secret-133',description:'They uses a name taken from the dead to protect someone, and only an old friend has proof.',severity:RiskLevel.Moderate},
  {id:'secret-134',description:'They betrayed a former employer to protect someone, while a rival is close to discovering it.',severity:RiskLevel.Moderate},
  {id:'secret-135',description:'They witnessed an unsolved murder to protect someone, and exposure would end a valued relationship.',severity:RiskLevel.Moderate},
  {id:'secret-136',description:'They possesses a stolen family heirloom to protect someone, but the evidence is hidden nearby.',severity:RiskLevel.Moderate},
  {id:'secret-137',description:'They belongs to a forbidden society to protect someone, and someone innocent currently bears the blame.',severity:RiskLevel.Moderate},
  {id:'secret-138',description:'They has an unrecognized child to protect someone, and only an old friend has proof.',severity:RiskLevel.Moderate},
  {id:'secret-139',description:'They falsified an important credential to protect someone, while a rival is close to discovering it.',severity:RiskLevel.Moderate},
  {id:'secret-140',description:'They knows a noble\'s hidden parentage to protect someone, and exposure would end a valued relationship.',severity:RiskLevel.Moderate},
  {id:'secret-141',description:'They concealed their true birthplace for personal gain, and someone innocent currently bears the blame.',severity:RiskLevel.Moderate},
  {id:'secret-142',description:'They owes money to a criminal lender for personal gain, and only an old friend has proof.',severity:RiskLevel.Moderate},
  {id:'secret-143',description:'They uses a name taken from the dead for personal gain, while a rival is close to discovering it.',severity:RiskLevel.Moderate},
  {id:'secret-144',description:'They betrayed a former employer for personal gain, and exposure would end a valued relationship.',severity:RiskLevel.Moderate},
  {id:'secret-145',description:'They witnessed an unsolved murder for personal gain, but the evidence is hidden nearby.',severity:RiskLevel.Moderate},
  {id:'secret-146',description:'They possesses a stolen family heirloom for personal gain, and someone innocent currently bears the blame.',severity:RiskLevel.Moderate},
  {id:'secret-147',description:'They belongs to a forbidden society for personal gain, and only an old friend has proof.',severity:RiskLevel.Moderate},
  {id:'secret-148',description:'They has an unrecognized child for personal gain, while a rival is close to discovering it.',severity:RiskLevel.Moderate},
  {id:'secret-149',description:'They falsified an important credential for personal gain, and exposure would end a valued relationship.',severity:RiskLevel.Moderate},
  {id:'secret-150',description:'They knows a noble\'s hidden parentage for personal gain, but the evidence is hidden nearby.',severity:RiskLevel.Moderate},
  {id:'secret-151',description:'They concealed their true birthplace quietly, and only an old friend has proof.',severity:RiskLevel.High},
  {id:'secret-152',description:'They owes money to a criminal lender quietly, while a rival is close to discovering it.',severity:RiskLevel.High},
  {id:'secret-153',description:'They uses a name taken from the dead quietly, and exposure would end a valued relationship.',severity:RiskLevel.High},
  {id:'secret-154',description:'They betrayed a former employer quietly, but the evidence is hidden nearby.',severity:RiskLevel.High},
  {id:'secret-155',description:'They witnessed an unsolved murder quietly, and someone innocent currently bears the blame.',severity:RiskLevel.High},
  {id:'secret-156',description:'They possesses a stolen family heirloom quietly, and only an old friend has proof.',severity:RiskLevel.High},
  {id:'secret-157',description:'They belongs to a forbidden society quietly, while a rival is close to discovering it.',severity:RiskLevel.High},
  {id:'secret-158',description:'They has an unrecognized child quietly, and exposure would end a valued relationship.',severity:RiskLevel.High},
  {id:'secret-159',description:'They falsified an important credential quietly, but the evidence is hidden nearby.',severity:RiskLevel.High},
  {id:'secret-160',description:'They knows a noble\'s hidden parentage quietly, and someone innocent currently bears the blame.',severity:RiskLevel.High},
  {id:'secret-161',description:'They concealed their true birthplace years ago, while a rival is close to discovering it.',severity:RiskLevel.High},
  {id:'secret-162',description:'They owes money to a criminal lender years ago, and exposure would end a valued relationship.',severity:RiskLevel.High},
  {id:'secret-163',description:'They uses a name taken from the dead years ago, but the evidence is hidden nearby.',severity:RiskLevel.High},
  {id:'secret-164',description:'They betrayed a former employer years ago, and someone innocent currently bears the blame.',severity:RiskLevel.High},
  {id:'secret-165',description:'They witnessed an unsolved murder years ago, and only an old friend has proof.',severity:RiskLevel.High},
  {id:'secret-166',description:'They possesses a stolen family heirloom years ago, while a rival is close to discovering it.',severity:RiskLevel.High},
  {id:'secret-167',description:'They belongs to a forbidden society years ago, and exposure would end a valued relationship.',severity:RiskLevel.High},
  {id:'secret-168',description:'They has an unrecognized child years ago, but the evidence is hidden nearby.',severity:RiskLevel.High},
  {id:'secret-169',description:'They falsified an important credential years ago, and someone innocent currently bears the blame.',severity:RiskLevel.High},
  {id:'secret-170',description:'They knows a noble\'s hidden parentage years ago, and only an old friend has proof.',severity:RiskLevel.High},
  {id:'secret-171',description:'They concealed their true birthplace under pressure, and exposure would end a valued relationship.',severity:RiskLevel.High},
  {id:'secret-172',description:'They owes money to a criminal lender under pressure, but the evidence is hidden nearby.',severity:RiskLevel.High},
  {id:'secret-173',description:'They uses a name taken from the dead under pressure, and someone innocent currently bears the blame.',severity:RiskLevel.High},
  {id:'secret-174',description:'They betrayed a former employer under pressure, and only an old friend has proof.',severity:RiskLevel.High},
  {id:'secret-175',description:'They witnessed an unsolved murder under pressure, while a rival is close to discovering it.',severity:RiskLevel.High},
  {id:'secret-176',description:'They possesses a stolen family heirloom under pressure, and exposure would end a valued relationship.',severity:RiskLevel.High},
  {id:'secret-177',description:'They belongs to a forbidden society under pressure, but the evidence is hidden nearby.',severity:RiskLevel.High},
  {id:'secret-178',description:'They has an unrecognized child under pressure, and someone innocent currently bears the blame.',severity:RiskLevel.High},
  {id:'secret-179',description:'They falsified an important credential under pressure, and only an old friend has proof.',severity:RiskLevel.High},
  {id:'secret-180',description:'They knows a noble\'s hidden parentage under pressure, while a rival is close to discovering it.',severity:RiskLevel.High},
  {id:'secret-181',description:'They concealed their true birthplace to protect someone, but the evidence is hidden nearby.',severity:RiskLevel.High},
  {id:'secret-182',description:'They owes money to a criminal lender to protect someone, and someone innocent currently bears the blame.',severity:RiskLevel.High},
  {id:'secret-183',description:'They uses a name taken from the dead to protect someone, and only an old friend has proof.',severity:RiskLevel.High},
  {id:'secret-184',description:'They betrayed a former employer to protect someone, while a rival is close to discovering it.',severity:RiskLevel.High},
  {id:'secret-185',description:'They witnessed an unsolved murder to protect someone, and exposure would end a valued relationship.',severity:RiskLevel.High},
  {id:'secret-186',description:'They possesses a stolen family heirloom to protect someone, but the evidence is hidden nearby.',severity:RiskLevel.High},
  {id:'secret-187',description:'They belongs to a forbidden society to protect someone, and someone innocent currently bears the blame.',severity:RiskLevel.High},
  {id:'secret-188',description:'They has an unrecognized child to protect someone, and only an old friend has proof.',severity:RiskLevel.High},
  {id:'secret-189',description:'They falsified an important credential to protect someone, while a rival is close to discovering it.',severity:RiskLevel.High},
  {id:'secret-190',description:'They knows a noble\'s hidden parentage to protect someone, and exposure would end a valued relationship.',severity:RiskLevel.High},
  {id:'secret-191',description:'They concealed their true birthplace for personal gain, and someone innocent currently bears the blame.',severity:RiskLevel.High},
  {id:'secret-192',description:'They owes money to a criminal lender for personal gain, and only an old friend has proof.',severity:RiskLevel.High},
  {id:'secret-193',description:'They uses a name taken from the dead for personal gain, while a rival is close to discovering it.',severity:RiskLevel.High},
  {id:'secret-194',description:'They betrayed a former employer for personal gain, and exposure would end a valued relationship.',severity:RiskLevel.High},
  {id:'secret-195',description:'They witnessed an unsolved murder for personal gain, but the evidence is hidden nearby.',severity:RiskLevel.High},
  {id:'secret-196',description:'They possesses a stolen family heirloom for personal gain, and someone innocent currently bears the blame.',severity:RiskLevel.High},
  {id:'secret-197',description:'They belongs to a forbidden society for personal gain, and only an old friend has proof.',severity:RiskLevel.High},
  {id:'secret-198',description:'They has an unrecognized child for personal gain, while a rival is close to discovering it.',severity:RiskLevel.High},
  {id:'secret-199',description:'They falsified an important credential for personal gain, and exposure would end a valued relationship.',severity:RiskLevel.High},
  {id:'secret-200',description:'They knows a noble\'s hidden parentage for personal gain, but the evidence is hidden nearby.',severity:RiskLevel.High},
  {id:'secret-201',description:'They concealed their true birthplace quietly, and only an old friend has proof.',severity:RiskLevel.Critical},
  {id:'secret-202',description:'They owes money to a criminal lender quietly, while a rival is close to discovering it.',severity:RiskLevel.Critical},
  {id:'secret-203',description:'They uses a name taken from the dead quietly, and exposure would end a valued relationship.',severity:RiskLevel.Critical},
  {id:'secret-204',description:'They betrayed a former employer quietly, but the evidence is hidden nearby.',severity:RiskLevel.Critical},
  {id:'secret-205',description:'They witnessed an unsolved murder quietly, and someone innocent currently bears the blame.',severity:RiskLevel.Critical},
  {id:'secret-206',description:'They possesses a stolen family heirloom quietly, and only an old friend has proof.',severity:RiskLevel.Critical},
  {id:'secret-207',description:'They belongs to a forbidden society quietly, while a rival is close to discovering it.',severity:RiskLevel.Critical},
  {id:'secret-208',description:'They has an unrecognized child quietly, and exposure would end a valued relationship.',severity:RiskLevel.Critical},
  {id:'secret-209',description:'They falsified an important credential quietly, but the evidence is hidden nearby.',severity:RiskLevel.Critical},
  {id:'secret-210',description:'They knows a noble\'s hidden parentage quietly, and someone innocent currently bears the blame.',severity:RiskLevel.Critical},
  {id:'secret-211',description:'They concealed their true birthplace years ago, while a rival is close to discovering it.',severity:RiskLevel.Critical},
  {id:'secret-212',description:'They owes money to a criminal lender years ago, and exposure would end a valued relationship.',severity:RiskLevel.Critical},
  {id:'secret-213',description:'They uses a name taken from the dead years ago, but the evidence is hidden nearby.',severity:RiskLevel.Critical},
  {id:'secret-214',description:'They betrayed a former employer years ago, and someone innocent currently bears the blame.',severity:RiskLevel.Critical},
  {id:'secret-215',description:'They witnessed an unsolved murder years ago, and only an old friend has proof.',severity:RiskLevel.Critical},
  {id:'secret-216',description:'They possesses a stolen family heirloom years ago, while a rival is close to discovering it.',severity:RiskLevel.Critical},
  {id:'secret-217',description:'They belongs to a forbidden society years ago, and exposure would end a valued relationship.',severity:RiskLevel.Critical},
  {id:'secret-218',description:'They has an unrecognized child years ago, but the evidence is hidden nearby.',severity:RiskLevel.Critical},
  {id:'secret-219',description:'They falsified an important credential years ago, and someone innocent currently bears the blame.',severity:RiskLevel.Critical},
  {id:'secret-220',description:'They knows a noble\'s hidden parentage years ago, and only an old friend has proof.',severity:RiskLevel.Critical},
  {id:'secret-221',description:'They concealed their true birthplace under pressure, and exposure would end a valued relationship.',severity:RiskLevel.Critical},
  {id:'secret-222',description:'They owes money to a criminal lender under pressure, but the evidence is hidden nearby.',severity:RiskLevel.Critical},
  {id:'secret-223',description:'They uses a name taken from the dead under pressure, and someone innocent currently bears the blame.',severity:RiskLevel.Critical},
  {id:'secret-224',description:'They betrayed a former employer under pressure, and only an old friend has proof.',severity:RiskLevel.Critical},
  {id:'secret-225',description:'They witnessed an unsolved murder under pressure, while a rival is close to discovering it.',severity:RiskLevel.Critical},
  {id:'secret-226',description:'They possesses a stolen family heirloom under pressure, and exposure would end a valued relationship.',severity:RiskLevel.Critical},
  {id:'secret-227',description:'They belongs to a forbidden society under pressure, but the evidence is hidden nearby.',severity:RiskLevel.Critical},
  {id:'secret-228',description:'They has an unrecognized child under pressure, and someone innocent currently bears the blame.',severity:RiskLevel.Critical},
  {id:'secret-229',description:'They falsified an important credential under pressure, and only an old friend has proof.',severity:RiskLevel.Critical},
  {id:'secret-230',description:'They knows a noble\'s hidden parentage under pressure, while a rival is close to discovering it.',severity:RiskLevel.Critical},
  {id:'secret-231',description:'They concealed their true birthplace to protect someone, but the evidence is hidden nearby.',severity:RiskLevel.Critical},
  {id:'secret-232',description:'They owes money to a criminal lender to protect someone, and someone innocent currently bears the blame.',severity:RiskLevel.Critical},
  {id:'secret-233',description:'They uses a name taken from the dead to protect someone, and only an old friend has proof.',severity:RiskLevel.Critical},
  {id:'secret-234',description:'They betrayed a former employer to protect someone, while a rival is close to discovering it.',severity:RiskLevel.Critical},
  {id:'secret-235',description:'They witnessed an unsolved murder to protect someone, and exposure would end a valued relationship.',severity:RiskLevel.Critical},
  {id:'secret-236',description:'They possesses a stolen family heirloom to protect someone, but the evidence is hidden nearby.',severity:RiskLevel.Critical},
  {id:'secret-237',description:'They belongs to a forbidden society to protect someone, and someone innocent currently bears the blame.',severity:RiskLevel.Critical},
  {id:'secret-238',description:'They has an unrecognized child to protect someone, and only an old friend has proof.',severity:RiskLevel.Critical},
  {id:'secret-239',description:'They falsified an important credential to protect someone, while a rival is close to discovering it.',severity:RiskLevel.Critical},
  {id:'secret-240',description:'They knows a noble\'s hidden parentage to protect someone, and exposure would end a valued relationship.',severity:RiskLevel.Critical},
  {id:'secret-241',description:'They concealed their true birthplace for personal gain, and someone innocent currently bears the blame.',severity:RiskLevel.Critical},
  {id:'secret-242',description:'They owes money to a criminal lender for personal gain, and only an old friend has proof.',severity:RiskLevel.Critical},
  {id:'secret-243',description:'They uses a name taken from the dead for personal gain, while a rival is close to discovering it.',severity:RiskLevel.Critical},
  {id:'secret-244',description:'They betrayed a former employer for personal gain, and exposure would end a valued relationship.',severity:RiskLevel.Critical},
  {id:'secret-245',description:'They witnessed an unsolved murder for personal gain, but the evidence is hidden nearby.',severity:RiskLevel.Critical},
  {id:'secret-246',description:'They possesses a stolen family heirloom for personal gain, and someone innocent currently bears the blame.',severity:RiskLevel.Critical},
  {id:'secret-247',description:'They belongs to a forbidden society for personal gain, and only an old friend has proof.',severity:RiskLevel.Critical},
  {id:'secret-248',description:'They has an unrecognized child for personal gain, while a rival is close to discovering it.',severity:RiskLevel.Critical},
  {id:'secret-249',description:'They falsified an important credential for personal gain, and exposure would end a valued relationship.',severity:RiskLevel.Critical},
  {id:'secret-250',description:'They knows a noble\'s hidden parentage for personal gain, but the evidence is hidden nearby.',severity:RiskLevel.Critical},
] as const satisfies readonly SecretData[];
