import { Alignment } from '../types';
import type { SubraceData } from '../types';

export const SUBRACES = [
  {id:'hill-dwarf',parentRaceId:'dwarf',name:'Hill Dwarf',typicalLifespan:350,adultAge:50,heightInches:{min:48,max:54},weightPounds:{min:120,max:190},commonAlignments:[Alignment.LawfulGood],commonOccupationIds:['priest','artisan','farmer'],commonLanguageIds:['common','dwarvish'],description:'Dwarves associated with deep resilience, tradition, and wisdom.'},
  {id:'mountain-dwarf',parentRaceId:'dwarf',name:'Mountain Dwarf',typicalLifespan:350,adultAge:50,heightInches:{min:48,max:60},weightPounds:{min:140,max:220},commonAlignments:[Alignment.LawfulGood],commonOccupationIds:['blacksmith','soldier','miner'],commonLanguageIds:['common','dwarvish'],description:'Dwarves of mountain holds known for armorcraft and martial training.'},
  {id:'duergar',parentRaceId:'dwarf',name:'Duergar',typicalLifespan:350,adultAge:50,heightInches:{min:48,max:60},weightPounds:{min:130,max:210},commonAlignments:[Alignment.LawfulNeutral,Alignment.LawfulEvil],commonOccupationIds:['miner','smith','soldier'],commonLanguageIds:['common','dwarvish','undercommon'],description:'Underdark dwarves shaped by psionic power, hardship, and subterranean industry.'},
  {id:'high-elf',parentRaceId:'elf',name:'High Elf',typicalLifespan:750,adultAge:100,heightInches:{min:60,max:74},weightPounds:{min:95,max:180},commonAlignments:[Alignment.ChaoticGood],commonOccupationIds:['wizard','scholar','noble'],commonLanguageIds:['common','elvish'],description:'Elves whose cultures often prize arcane learning, art, and long memory.'},
  {id:'wood-elf',parentRaceId:'elf',name:'Wood Elf',typicalLifespan:750,adultAge:100,heightInches:{min:58,max:72},weightPounds:{min:100,max:190},commonAlignments:[Alignment.ChaoticGood],commonOccupationIds:['hunter','scout','druid'],commonLanguageIds:['common','elvish'],description:'Fleet forest-dwelling elves skilled in concealment and wilderness life.'},
  {id:'dark-elf-drow',parentRaceId:'elf',name:'Dark Elf (Drow)',typicalLifespan:750,adultAge:100,heightInches:{min:55,max:68},weightPounds:{min:85,max:160},commonAlignments:[Alignment.TrueNeutral,Alignment.ChaoticNeutral],commonOccupationIds:['scout','priest','wizard'],commonLanguageIds:['common','elvish','undercommon'],description:'Underdark elves with innate magic and adaptations to lightless realms.'},
  {id:'sea-elf',parentRaceId:'elf',name:'Sea Elf',typicalLifespan:750,adultAge:100,heightInches:{min:58,max:74},weightPounds:{min:100,max:190},commonAlignments:[Alignment.NeutralGood,Alignment.TrueNeutral],commonOccupationIds:['fisher','sailor','guard'],commonLanguageIds:['common','elvish','aquan'],description:'Amphibious elves at home in ocean communities and coastal waters.'},
  {id:'eladrin',parentRaceId:'elf',name:'Eladrin',typicalLifespan:750,adultAge:100,heightInches:{min:58,max:74},weightPounds:{min:90,max:180},commonAlignments:[Alignment.ChaoticGood,Alignment.ChaoticNeutral],commonOccupationIds:['noble','wizard','entertainer'],commonLanguageIds:['common','elvish','sylvan'],description:'Feywild elves whose appearance and magic shift with seasonal states.'},
  {id:'astral-elf',parentRaceId:'elf',name:'Astral Elf',typicalLifespan:1000,adultAge:100,heightInches:{min:58,max:74},weightPounds:{min:90,max:180},commonAlignments:[Alignment.TrueNeutral,Alignment.LawfulNeutral],commonOccupationIds:['sailor','scholar','wizard'],commonLanguageIds:['common','elvish'],description:'Elves transformed by long residence in the timeless Astral Plane.'},
  {id:'lightfoot-halfling',parentRaceId:'halfling',name:'Lightfoot Halfling',typicalLifespan:150,adultAge:20,heightInches:{min:31,max:38},weightPounds:{min:30,max:40},commonAlignments:[Alignment.LawfulGood],commonOccupationIds:['merchant','entertainer','innkeeper'],commonLanguageIds:['common','halfling'],description:'Sociable, stealthy halflings who readily live among other peoples.'},
  {id:'stout-halfling',parentRaceId:'halfling',name:'Stout Halfling',typicalLifespan:150,adultAge:20,heightInches:{min:32,max:40},weightPounds:{min:35,max:45},commonAlignments:[Alignment.LawfulGood],commonOccupationIds:['farmer','cook','guard'],commonLanguageIds:['common','halfling'],description:'Hardy halflings with notable resilience and sturdy constitutions.'},
  {id:'forest-gnome',parentRaceId:'gnome',name:'Forest Gnome',typicalLifespan:425,adultAge:40,heightInches:{min:35,max:42},weightPounds:{min:35,max:45},commonAlignments:[Alignment.NeutralGood],commonOccupationIds:['herbalist','druid','illusionist'],commonLanguageIds:['common','gnomish'],description:'Reclusive woodland gnomes with gifts for illusion and animal friendship.'},
  {id:'rock-gnome',parentRaceId:'gnome',name:'Rock Gnome',typicalLifespan:425,adultAge:40,heightInches:{min:36,max:44},weightPounds:{min:38,max:50},commonAlignments:[Alignment.NeutralGood],commonOccupationIds:['tinker','jeweler','alchemist'],commonLanguageIds:['common','gnomish'],description:'Inventive gnomes known for mechanisms, craft, and relentless curiosity.'},
  {id:'deep-gnome',parentRaceId:'gnome',name:'Deep Gnome',typicalLifespan:425,adultAge:40,heightInches:{min:34,max:42},weightPounds:{min:35,max:50},commonAlignments:[Alignment.NeutralGood,Alignment.TrueNeutral],commonOccupationIds:['miner','scout','gemcutter'],commonLanguageIds:['common','gnomish','undercommon'],description:'Cautious Underdark gnomes skilled at concealment, stone, and survival.'},
  {id:'air-genasi',parentRaceId:'genasi',name:'Air Genasi',typicalLifespan:120,adultAge:18,heightInches:{min:58,max:78},weightPounds:{min:90,max:220},commonAlignments:[Alignment.ChaoticNeutral],commonOccupationIds:['sailor','messenger','explorer'],commonLanguageIds:['common','auran'],description:'Genasi marked by wind, breath, and the restless influence of elemental air.'},
  {id:'earth-genasi',parentRaceId:'genasi',name:'Earth Genasi',typicalLifespan:120,adultAge:18,heightInches:{min:60,max:80},weightPounds:{min:140,max:280},commonAlignments:[Alignment.LawfulNeutral],commonOccupationIds:['miner','mason','guard'],commonLanguageIds:['common','terran'],description:'Genasi with stone-like traits and the enduring influence of elemental earth.'},
  {id:'fire-genasi',parentRaceId:'genasi',name:'Fire Genasi',typicalLifespan:120,adultAge:18,heightInches:{min:58,max:78},weightPounds:{min:100,max:240},commonAlignments:[Alignment.ChaoticNeutral],commonOccupationIds:['smith','alchemist','performer'],commonLanguageIds:['common','ignan'],description:'Genasi whose heat, glow, and temperament echo elemental fire.'},
  {id:'water-genasi',parentRaceId:'genasi',name:'Water Genasi',typicalLifespan:120,adultAge:18,heightInches:{min:58,max:78},weightPounds:{min:110,max:250},commonAlignments:[Alignment.TrueNeutral],commonOccupationIds:['sailor','fisher','healer'],commonLanguageIds:['common','aquan'],description:'Amphibious genasi carrying the fluid grace and resilience of elemental water.'},
  {id:'githyanki',parentRaceId:'gith',name:'Githyanki',typicalLifespan:100,adultAge:18,heightInches:{min:60,max:74},weightPounds:{min:90,max:190},commonAlignments:[Alignment.LawfulEvil,Alignment.LawfulNeutral],commonOccupationIds:['soldier','knight','sailor'],commonLanguageIds:['common','gith'],description:'Astral gith organized around martial tradition, raiding, and opposition to mind flayers.'},
  {id:'githzerai',parentRaceId:'gith',name:'Githzerai',typicalLifespan:100,adultAge:18,heightInches:{min:60,max:74},weightPounds:{min:90,max:190},commonAlignments:[Alignment.LawfulNeutral],commonOccupationIds:['monk','scholar','guard'],commonLanguageIds:['common','gith'],description:'Disciplined gith who cultivate psionic focus in monasteries amid Limbo.'},
] as const satisfies readonly SubraceData[];
