import { SocialStatus,Wealth } from '../../../../types';import type { InventoryEntry,Item,ItemCondition,ItemGenerationContext,ItemRarity,ItemType,QuestItem } from '../../types';
interface ItemBlueprint {readonly name:string;readonly type:ItemType;readonly reason:string;readonly tags:readonly string[]}
const OCCUPATION_BLUEPRINTS:Readonly<Record<string,readonly ItemBlueprint[]>>={
  blacksmith:[{name:'Smithing hammer',type:'tool',reason:'Used for daily forge work.',tags:['crafting','forge']},{name:'Metal samples',type:'material',reason:'Reference stock for judging alloys.',tags:['metal','trade']},{name:'Order ledger',type:'document',reason:'Tracks commissions and debts.',tags:['orders','business']}],
  guard:[{name:'Service weapon',type:'weapon',reason:'Issued or purchased for guard duty.',tags:['military']},{name:'Guard armor',type:'armor',reason:'Protects the wearer during patrols.',tags:['military']},{name:'Authority badge',type:'document',reason:'Establishes legal authority.',tags:['government']},{name:'Duty keys',type:'key',reason:'Opens assigned gates or cells.',tags:['security']}],
  merchant:[{name:'Trade samples',type:'trade-goods',reason:'Demonstrates current merchandise.',tags:['commerce']},{name:'Account ledger',type:'book',reason:'Records prices, credit, and stock.',tags:['commerce']},{name:'Signed contracts',type:'document',reason:'Proves commercial obligations.',tags:['legal']}],
  scholar:[{name:'Reference volume',type:'book',reason:'Supports current research.',tags:['education']},{name:'Research notes',type:'document',reason:'Preserves observations and citations.',tags:['research']},{name:'Ink and writing kit',type:'tool',reason:'Required for scholarly work.',tags:['writing']}],
  priest:[{name:'Holy symbol',type:'relic',reason:'Used in worship and pastoral duties.',tags:['religion']},{name:'Religious text',type:'book',reason:'Provides doctrine and liturgy.',tags:['religion']},{name:'Ritual implements',type:'tool',reason:'Supports ceremonies and observance.',tags:['ritual']}],
};
const wealthRank:Record<Wealth,number>={[Wealth.Destitute]:0,[Wealth.Poor]:1,[Wealth.Modest]:2,[Wealth.Comfortable]:3,[Wealth.Wealthy]:4,[Wealth.Rich]:5,[Wealth.VeryRich]:6,[Wealth.Opulent]:7};
const occupationKey=(title:string)=>{const value=title.toLowerCase();return Object.keys(OCCUPATION_BLUEPRINTS).find(key=>value.includes(key))??'professional'};
export function createItem(context:ItemGenerationContext,blueprint:ItemBlueprint,index:number):Item{const rank=wealthRank[context.npc.wealth],condition:ItemCondition=rank<=1?'worn':rank>=5?'fine':'serviceable',rarity:ItemRarity=rank>=6&&index===0?'uncommon':'common',city=context.city;return{id:context.idFactory(),name:blueprint.name,type:blueprint.type,rarity,description:`${blueprint.reason} This ${condition} example belongs to ${context.npc.name}, a ${context.npc.occupation.title.toLowerCase()}.`,category:blueprint.type==='weapon'||blueprint.type==='armor'||blueprint.type==='shield'?'equipment':blueprint.type==='document'||blueprint.type==='book'?'knowledge':blueprint.type==='trade-goods'||blueprint.type==='material'?'trade':'professional',value:{amount:basePrice(blueprint.type,rarity,condition,rank),currency:'gp'},weight:baseWeight(blueprint.type),owner:context.npc.id,origin:{locationId:city?.id??null,factionId:context.factions[0]?.id??null,creatorNpcId:occupationKey(context.npc.occupation.title)==='blacksmith'?context.npc.id:null,description:city?`Obtained or made in ${city.name}.`:`Connected to ${context.npc.occupation.workplace}.`},history:[blueprint.reason],condition,tags:[...blueprint.tags,context.npc.race.toLowerCase(),context.npc.occupation.title.toLowerCase()],evidence:[context.npc.occupation.title,context.npc.wealth,context.npc.occupation.workplace,blueprint.reason,city?.economy.join(', ')??''].filter(Boolean)};}
export function occupationItems(context:ItemGenerationContext):readonly Item[]{const key=occupationKey(context.npc.occupation.title),blueprints=OCCUPATION_BLUEPRINTS[key]??[{name:`${context.npc.occupation.title} tools`,type:'tool',reason:`Required for work as ${context.npc.occupation.title}.`,tags:['occupation']},{name:'Work records',type:'document',reason:`Documents duties at ${context.npc.occupation.workplace}.`,tags:['work']}];return blueprints.map((blueprint,index)=>createItem(context,blueprint,index));}
export function personalItem(context:ItemGenerationContext):Item{const hasFamily=context.npc.personality.bonds.find(bond=>/family|parent|sibling/i.test(bond)),hasFaith=context.npc.religion,secret=context.npc.secret.description,blueprint:ItemBlueprint=hasFamily?{name:'Family keepsake',type:'jewelry',reason:`Preserves the bond: ${hasFamily}`,tags:['personal','family']}:hasFaith?{name:'Childhood devotional token',type:'relic',reason:`Connects ${context.npc.name} to ${hasFaith}.`,tags:['personal','religion']}:secret?{name:'Private journal',type:'book',reason:`Contains guarded context related to: ${secret}`,tags:['personal','secret']}:{name:'Personal correspondence',type:'document',reason:`Records the pursuit of ${context.npc.goal.currentGoal}.`,tags:['personal','goal']};return{...createItem(context,blueprint,4),category:'personal'};}
export function questItem(context:ItemGenerationContext,questId:string):QuestItem{const quest=context.quests.find(item=>item.id===questId);if(!quest)throw new Error('Quest item generation requires an existing connected quest.');const factionId=quest.relatedFactions[0]??null,item=createItem(context,{name:`Evidence from ${quest.title}`,type:'quest-item',reason:`Required to advance the objective: ${quest.objectives[0]?.description??quest.description}`,tags:['quest',quest.type]},5);return{...item,type:'quest-item',category:'quest',rarity:quest.difficulty==='deadly'?'rare':quest.difficulty==='hard'?'uncommon':'common',origin:{...item.origin,factionId},quest:{purpose:quest.objectives[0]?.description??quest.description,history:quest.description,owner:item.owner,importance:quest.type==='main-quest'?'regional':'local',danger:quest.difficulty==='deadly'?'high':quest.difficulty==='hard'?'moderate':'low',questId:quest.id}};}
export function justifiedMagicItem(context:ItemGenerationContext,input:{readonly name:string;readonly type:ItemType;readonly rarity:Exclude<ItemRarity,'common'>;readonly justification:string}):Item{const support=[input.justification,...context.quests.map(quest=>quest.description),...context.factions.flatMap(faction=>[...faction.resources,...faction.history]),...context.npc.backstory.map(chapter=>chapter.selectedResult??chapter.climax)].filter(value=>value.trim().length>20);if(support.length===0)throw new Error('Magical items require substantial quest, faction, influence, or backstory justification.');if((input.rarity==='legendary'||input.rarity==='artifact')&&!context.quests.some(quest=>quest.difficulty==='deadly'||quest.type==='main-quest'))throw new Error('Legendary and artifact items require a deadly or main-quest connection.');const base=createItem(context,{name:input.name,type:input.type,reason:input.justification,tags:['magic','justified']},8);return{...base,rarity:input.rarity,category:input.type==='quest-item'?'quest':'valuable',history:support,evidence:[...base.evidence,...support]};}
export function toEntry(item:Item,locked=false):InventoryEntry{return{item,quantity:1,equipped:false,locked,notes:''};}
function basePrice(type:ItemType,rarity:ItemRarity,condition:ItemCondition,wealth:number):number{const typeBase:Partial<Record<ItemType,number>>={weapon:15,armor:50,shield:10,jewelry:25,potion:50,scroll:25,book:10,'trade-goods':10,artifact:1000,relic:25};const rarityMultiplier:Record<ItemRarity,number>={common:1,uncommon:5,rare:50,'very-rare':500,legendary:5000,artifact:10000},conditionMultiplier:Record<ItemCondition,number>={ruined:.05,poor:.25,worn:.5,serviceable:1,fine:2,pristine:3};return Math.max(1,Math.round((typeBase[type]??2)*rarityMultiplier[rarity]*conditionMultiplier[condition]*(1+wealth*.03)));}
function baseWeight(type:ItemType):number{return({weapon:3,armor:20,shield:6,tool:2,clothing:3,book:2,material:5,'trade-goods':5,food:1} as Partial<Record<ItemType,number>>)[type]??.5;}
export function itemCountForWealth(wealth:Wealth,status:SocialStatus):number{const base=Math.max(2,Math.min(10,3+Math.floor(wealthRank[wealth]/2)));return status===SocialStatus.Royalty||status===SocialStatus.Noble?Math.min(10,base+2):base;}
