import type { StorageProvider } from '../../storage';import type { NPC } from '../../types';import { EMPTY_WORKSPACE,metadata } from '../../workspace/defaults';import { isWorkspaceSnapshot } from '../../workspace/serialization';import type { CreateNPCInput,NPCVersion,UpdateNPCInput,UUID,VersionDifference,WorkspaceCampaign,WorkspaceFolder,WorkspaceNPC,WorkspacePage,WorkspaceQuery,WorkspaceSnapshot } from '../../workspace/types';import type { NPCRepository } from './NPCRepository';

const KEY='smart-npc-generator:workspace:v1',LEGACY_KEY='smart-npc-generator:saved:v1';
function uuid():UUID{return crypto.randomUUID();}
function clone<T>(value:T):T{return structuredClone(value);}
function normalizeSnapshot(snapshot:WorkspaceSnapshot):WorkspaceSnapshot{return {...snapshot,npcs:snapshot.npcs.map(item=>({...item,flavor:item.flavor??null,metadata:{...item.metadata,changeHistory:item.metadata.changeHistory??[]}})),versions:snapshot.versions.map(item=>({...item,flavor:item.flavor??null,metadata:{...item.metadata,changeHistory:item.metadata.changeHistory??[]}}))};}
interface LegacyRecord {readonly npc:NPC;readonly createdAt?:string;readonly favorite?:boolean}
function legacyRecords(value:unknown):readonly LegacyRecord[]{if(!Array.isArray(value))return [];return value.filter((item):item is LegacyRecord=>Boolean(item)&&typeof item==='object'&&'npc'in item&&Boolean((item as Record<string,unknown>).npc));}
function compareValues(before:unknown,after:unknown,path='',result:VersionDifference[]=[]):VersionDifference[]{if(Object.is(before,after))return result;if(typeof before!=='object'||before===null||typeof after!=='object'||after===null){result.push({path:path||'root',before,after});return result;}const left=before as Record<string,unknown>,right=after as Record<string,unknown>;for(const key of new Set([...Object.keys(left),...Object.keys(right)]))compareValues(left[key],right[key],path?`${path}.${key}`:key,result);return result;}
function searchable(record:WorkspaceNPC,campaigns:readonly WorkspaceCampaign[]):string{return [record.npc.name,record.npc.race,record.npc.occupation.title,record.npc.alignment,record.npc.religion,record.npc.goal.currentGoal,...record.metadata.tags.map(tag=>tag.name),...campaigns.filter(campaign=>record.metadata.campaignIds.includes(campaign.id)).map(campaign=>campaign.name)].filter(Boolean).join(' ').toLowerCase();}
function matches(record:WorkspaceNPC,query:WorkspaceQuery,campaigns:readonly WorkspaceCampaign[]):boolean{const filters=query.filters;if(query.search&&!searchable(record,campaigns).includes(query.search.trim().toLowerCase()))return false;if(!filters)return true;return (!filters.race||record.npc.race===filters.race)&&(!filters.minimumAge||record.npc.age>=filters.minimumAge)&&(!filters.maximumAge||record.npc.age<=filters.maximumAge)&&(!filters.occupation||record.npc.occupation.title===filters.occupation)&&(!filters.alignment||record.npc.alignment===filters.alignment)&&(!filters.campaignId||record.metadata.campaignIds.includes(filters.campaignId))&&(!filters.wealth||record.npc.wealth===filters.wealth)&&(!filters.socialStatus||record.npc.socialStatus===filters.socialStatus)&&(!filters.religion||record.npc.religion===filters.religion)&&(filters.favorite===undefined||record.metadata.favorite===filters.favorite)&&(filters.archived===undefined||record.metadata.archived===filters.archived);}
function sortRecords(records:readonly WorkspaceNPC[],sort:WorkspaceQuery['sort']):WorkspaceNPC[]{return [...records].sort((a,b)=>{switch(sort??'newest'){case'oldest':return a.metadata.createdAt.localeCompare(b.metadata.createdAt);case'name':return a.npc.name.localeCompare(b.npc.name);case'race':return a.npc.race.localeCompare(b.npc.race);case'occupation':return a.npc.occupation.title.localeCompare(b.npc.occupation.title);case'recently-modified':return b.metadata.modifiedAt.localeCompare(a.metadata.modifiedAt);case'newest':return b.metadata.createdAt.localeCompare(a.metadata.createdAt);}});}

export class LocalNPCRepository implements NPCRepository {
  private state:WorkspaceSnapshot=EMPTY_WORKSPACE;private queue:Promise<void>=Promise.resolve();
  constructor(private readonly storage:StorageProvider){}
  async initialize():Promise<void>{const raw=await this.storage.read(KEY);if(!raw){const legacy=await this.storage.read(LEGACY_KEY);if(legacy){try{const records=legacyRecords(JSON.parse(legacy) as unknown);const npcs=records.map(item=>{const id=uuid(),now=item.createdAt??new Date().toISOString();return {id,npc:{...clone(item.npc),id},flavor:null,metadata:{...metadata(now,'Local Dungeon Master'),favorite:item.favorite??false}} satisfies WorkspaceNPC;});this.state={...EMPTY_WORKSPACE,npcs,versions:npcs.map(record=>this.version(record,'Migrated from saved NPCs'))};await this.persist();await this.storage.remove(LEGACY_KEY);return;}catch(error){await this.preserveCorruptData(LEGACY_KEY,legacy);throw new Error('Saved NPC data could not be migrated. The original data was preserved for recovery.',{cause:error});}}await this.persist();return;}try{const parsed:unknown=JSON.parse(raw);if(!isWorkspaceSnapshot(parsed))throw new Error('The workspace schema is not recognized.');this.state=normalizeSnapshot(parsed);}catch(error){await this.preserveCorruptData(KEY,raw);throw new Error('Workspace data could not be read. The original data was preserved for recovery.',{cause:error});}}
  private async preserveCorruptData(sourceKey:string,raw:string):Promise<void>{await this.storage.write(`${sourceKey}:recovery:${new Date().toISOString()}`,raw);}
  async snapshot():Promise<WorkspaceSnapshot>{return clone(this.state);}
  async replace(snapshot:WorkspaceSnapshot):Promise<void>{await this.commit(()=>{this.state=clone(snapshot);});}
  private async persist():Promise<void>{await this.storage.write(KEY,JSON.stringify(this.state));}
  private async commit<T>(work:()=>T):Promise<T>{let output:T|undefined;const operation=this.queue.then(async()=>{output=work();await this.persist();});this.queue=operation.then(()=>undefined,()=>undefined);await operation;return output as T;}
  private find(id:UUID):WorkspaceNPC{const found=this.state.npcs.find(item=>item.id===id);if(!found)throw new Error(`NPC ${id} was not found.`);return found;}
  private version(record:WorkspaceNPC,reason:string):NPCVersion{return {id:uuid(),npcId:record.id,version:record.metadata.version,savedAt:record.metadata.modifiedAt,npc:clone(record.npc),flavor:clone(record.flavor),metadata:clone(record.metadata),reason};}
  async create(input:CreateNPCInput):Promise<WorkspaceNPC>{return this.commit(()=>{const id=uuid(),now=new Date().toISOString();const record:WorkspaceNPC={id,npc:{...clone(input.npc),id},flavor:clone(input.flavor??null),metadata:{...metadata(now,input.author),tags:clone(input.tags??[]),notes:input.notes??'',folderId:input.folderId??null,campaignIds:[...new Set(input.campaignIds??[])],changeHistory:clone(input.changeHistory??[])}};this.state={...this.state,npcs:[record,...this.state.npcs],versions:[...this.state.versions,this.version(record,'Created NPC')]};return clone(record);});}
  async get(id:UUID):Promise<WorkspaceNPC|null>{const found=this.state.npcs.find(item=>item.id===id);return found?clone(found):null;}
  async query(query:WorkspaceQuery):Promise<WorkspacePage>{const requestedPage=Math.max(1,query.page??1),pageSize=Math.min(100,Math.max(1,query.pageSize??12));const all=sortRecords(this.state.npcs.filter(item=>matches(item,query,this.state.campaigns)),query.sort),pageCount=Math.max(1,Math.ceil(all.length/pageSize)),page=Math.min(requestedPage,pageCount);return {items:clone(all.slice((page-1)*pageSize,page*pageSize)),total:all.length,page,pageSize,pageCount};}
  async update(id:UUID,input:UpdateNPCInput):Promise<WorkspaceNPC>{return this.commit(()=>{const current=this.find(id),now=new Date().toISOString();const nextVersion=current.metadata.version+1;const record:WorkspaceNPC={id,npc:{...clone(input.npc??current.npc),id},flavor:input.flavor===undefined?clone(current.flavor):clone(input.flavor),metadata:{...current.metadata,modifiedAt:now,version:nextVersion,favorite:input.favorite??current.metadata.favorite,archived:input.archived??current.metadata.archived,tags:clone(input.tags??current.metadata.tags),notes:input.notes??current.metadata.notes,folderId:input.folderId===undefined?current.metadata.folderId:input.folderId,campaignIds:input.campaignIds?[...new Set(input.campaignIds)]:current.metadata.campaignIds,author:input.author??current.metadata.author,changeHistory:clone(input.changeHistory??current.metadata.changeHistory??[])}};this.state={...this.state,npcs:this.state.npcs.map(item=>item.id===id?record:item),versions:[...this.state.versions,this.version(record,input.reason??'Saved NPC')]};return clone(record);});}
  async delete(id:UUID):Promise<void>{await this.commit(()=>{this.find(id);this.state={...this.state,npcs:this.state.npcs.filter(item=>item.id!==id),versions:this.state.versions.filter(item=>item.npcId!==id)};});}
  async duplicate(id:UUID):Promise<WorkspaceNPC>{const source=this.find(id);return this.create({npc:{...source.npc,name:`${source.npc.name} Copy`},flavor:source.flavor,tags:source.metadata.tags,notes:source.metadata.notes,folderId:source.metadata.folderId,campaignIds:source.metadata.campaignIds,author:source.metadata.author,changeHistory:source.metadata.changeHistory});}
  async setFavorite(id:UUID,favorite:boolean):Promise<WorkspaceNPC>{return this.update(id,{favorite,reason:favorite?'Favorited NPC':'Removed favorite'});}
  async setArchived(id:UUID,archived:boolean):Promise<WorkspaceNPC>{return this.update(id,{archived,reason:archived?'Archived NPC':'Restored NPC'});}
  async rename(id:UUID,name:string):Promise<WorkspaceNPC>{const current=this.find(id);return this.update(id,{npc:{...current.npc,name:name.trim()||current.npc.name},reason:'Renamed NPC'});}
  async versions(id:UUID):Promise<readonly NPCVersion[]>{this.find(id);return clone(this.state.versions.filter(item=>item.npcId===id).sort((a,b)=>b.version-a.version));}
  async restoreVersion(id:UUID,version:number):Promise<WorkspaceNPC>{const prior=this.state.versions.find(item=>item.npcId===id&&item.version===version);if(!prior)throw new Error(`Version ${version} was not found.`);return this.update(id,{npc:prior.npc,flavor:prior.flavor??null,favorite:prior.metadata.favorite,archived:prior.metadata.archived,tags:prior.metadata.tags,notes:prior.metadata.notes,folderId:prior.metadata.folderId,campaignIds:prior.metadata.campaignIds,author:prior.metadata.author,changeHistory:prior.metadata.changeHistory,reason:`Restored version ${version}`});}
  async compareVersions(id:UUID,left:number,right:number):Promise<readonly VersionDifference[]>{const versions=await this.versions(id),a=versions.find(item=>item.version===left),b=versions.find(item=>item.version===right);if(!a||!b)throw new Error('Both versions are required for comparison.');return compareValues({npc:a.npc,flavor:a.flavor,metadata:a.metadata},{npc:b.npc,flavor:b.flavor,metadata:b.metadata});}
  async createFolder(name:string):Promise<WorkspaceFolder>{return this.commit(()=>{const now=new Date().toISOString(),folder={id:uuid(),name:name.trim(),createdAt:now,modifiedAt:now};if(!folder.name)throw new Error('Folder name is required.');this.state={...this.state,folders:[...this.state.folders,folder]};return clone(folder);});}
  async renameFolder(id:UUID,name:string):Promise<WorkspaceFolder>{return this.commit(()=>{const folder=this.state.folders.find(item=>item.id===id);if(!folder)throw new Error('Folder was not found.');const updated={...folder,name:name.trim()||folder.name,modifiedAt:new Date().toISOString()};this.state={...this.state,folders:this.state.folders.map(item=>item.id===id?updated:item)};return clone(updated);});}
  async deleteFolder(id:UUID):Promise<void>{await this.commit(()=>{this.state={...this.state,folders:this.state.folders.filter(item=>item.id!==id),npcs:this.state.npcs.map(item=>item.metadata.folderId===id?{...item,metadata:{...item.metadata,folderId:null}}:item)};});}
  async createCampaign(name:string):Promise<WorkspaceCampaign>{return this.commit(()=>{const now=new Date().toISOString(),campaign={id:uuid(),name:name.trim(),createdAt:now,modifiedAt:now};if(!campaign.name)throw new Error('Campaign name is required.');this.state={...this.state,campaigns:[...this.state.campaigns,campaign]};return clone(campaign);});}
  async renameCampaign(id:UUID,name:string):Promise<WorkspaceCampaign>{return this.commit(()=>{const campaign=this.state.campaigns.find(item=>item.id===id);if(!campaign)throw new Error('Campaign was not found.');const updated={...campaign,name:name.trim()||campaign.name,modifiedAt:new Date().toISOString()};this.state={...this.state,campaigns:this.state.campaigns.map(item=>item.id===id?updated:item)};return clone(updated);});}
  async deleteCampaign(id:UUID):Promise<void>{await this.commit(()=>{this.state={...this.state,campaigns:this.state.campaigns.filter(item=>item.id!==id),npcs:this.state.npcs.map(item=>({...item,metadata:{...item.metadata,campaignIds:item.metadata.campaignIds.filter(value=>value!==id)}}))};});}
}
