import type { InventoryItem as FlavorInventoryItem } from '../../../../utils/generator/flavor';
import type { Inventory,InventoryEntry,InventoryGenerationResult,Item,ItemGenerationContext,LootGenerationInput,MerchantShop,ShopProduct } from '../../types';
import { locationPrice,validateEconomy,valueInGold } from '../economyValidator';import { resolveEquipment,validateEquipment } from '../equipmentResolver';import { itemCountForWealth,occupationItems,personalItem,toEntry } from '../itemEngine';

export function generateInventory(context:ItemGenerationContext,existing:readonly InventoryEntry[]=[]):InventoryGenerationResult{const locked=existing.filter(entry=>entry.locked),generated=[...occupationItems(context),personalItem(context)],limit=itemCountForWealth(context.npc.wealth,context.npc.socialStatus),entries=[...locked,...generated.filter(item=>!locked.some(entry=>entry.item.name.toLowerCase()===item.name.toLowerCase())).slice(0,Math.max(0,limit-locked.length)).map(item=>toEntry(item))],equipment=resolveEquipment(context,entries),equipped=entries.map(entry=>({...entry,equipped:[...equipment.weaponIds,equipment.armorId,equipment.shieldId,...equipment.toolIds,...equipment.clothingIds,...equipment.accessoryIds].filter(Boolean).includes(entry.item.id)})),inventory=aggregate(context,equipped),issues=[...validateEconomy(equipped,context.npc.wealth,context.city),...validateEquipment(context,equipment,equipped)];return{inventory,equipment,issues,stages:['npc','occupation','wealth','lifestyle','inventory','equipment','validation']};}
export function regenerateItem(context:ItemGenerationContext,inventory:Inventory,itemId:string):InventoryGenerationResult{const target=inventory.entries.find(entry=>entry.item.id===itemId);if(!target)throw new Error('Inventory item was not found.');if(target.locked)throw new Error('Locked items cannot regenerate.');return generateInventory(context,inventory.entries.filter(entry=>entry.item.id!==itemId));}
export function updateInventory(inventory:Inventory,entries:readonly InventoryEntry[],now=new Date().toISOString()):Inventory{return{...inventory,entries,totalWeight:entries.reduce((sum,entry)=>sum+entry.item.weight*entry.quantity,0),totalValueGp:entries.reduce((sum,entry)=>sum+valueInGold(entry.item.value)*entry.quantity,0),updatedAt:now};}
export function flavorItemAdapter(item:FlavorInventoryItem,ownerNpcId:string,idFactory:()=>string=()=>crypto.randomUUID()):Item{return{id:idFactory(),name:item.name,type:'tool',rarity:'common',description:item.description,category:'personal',value:{amount:1,currency:'gp'},weight:.5,owner:ownerNpcId,origin:{locationId:null,factionId:null,creatorNpcId:null,description:item.reason},history:[item.reason],condition:'serviceable',tags:['flavor-import'],evidence:[item.reason]};}
export function inventoryMarkdown(inventory:Inventory):string{return['# Inventory',`Owner: ${inventory.ownerNpcId}`,`Total weight: ${inventory.totalWeight}`,`Total value: ${inventory.totalValueGp} gp`,'',...inventory.entries.map(entry=>`- **${entry.item.name}** ×${entry.quantity} — ${entry.item.description} (${entry.item.value.amount} ${entry.item.value.currency})`)].join('\n');}
export function inventoryJSON(inventory:Inventory):string{return JSON.stringify({format:'smart-npc-inventory',version:1,inventory,questItems:inventory.entries.map(entry=>entry.item).filter(item=>item.type==='quest-item')},null,2);}
export function readStoredInventory(npcId:string):Inventory|null{try{const value=localStorage.getItem(`smart-npc-inventory-v1:${npcId}`);return value?JSON.parse(value) as Inventory:null}catch{return null}}
export function writeStoredInventory(inventory:Inventory):void{localStorage.setItem(`smart-npc-inventory-v1:${inventory.ownerNpcId}`,JSON.stringify(inventory));}
export function buildShopInventory(context:ItemGenerationContext,inventory:Inventory):MerchantShop{if(!/merchant|shop|trader|innkeeper|apothecary|blacksmith|jeweler/i.test(context.npc.occupation.title))throw new Error('Shop inventory requires an NPC with a commercial occupation.');if(!context.city)throw new Error('Shop inventory requires a city economy.');const products:ShopProduct[]=inventory.entries.filter(entry=>entry.item.category==='trade'||entry.item.category==='professional').map(entry=>({item:entry.item,price:locationPrice(entry.item,context.city),stock:Math.max(1,entry.quantity),availability:entry.item.rarity==='common'?'available':entry.item.rarity==='uncommon'?'limited':'scarce'}));return{id:context.idFactory(),merchantNpcId:context.npc.id,shopName:context.npc.occupation.workplace,category:context.npc.occupation.title,products,supplierFactionIds:context.factions.filter(faction=>faction.type==='merchant-company'||faction.type==='guild').map(faction=>faction.id),competitorFactionIds:context.factions.flatMap(faction=>faction.enemyFactionIds),cityId:context.city.id,updatedAt:context.now};}
export function generateLoot(input:LootGenerationInput):readonly Item[]{const idFactory=input.idFactory??(()=>crypto.randomUUID()),now=input.now??new Date().toISOString(),context:ItemGenerationContext={npc:input.enemyNpc,world:input.world,city:input.location,factions:input.faction?[input.faction]:[],quests:input.quest?[input.quest]:[],idFactory,now},inventory=generateInventory(context).inventory,questEvidence=input.quest?.rewards.filter(reward=>reward.type==='item').map(reward=>reward.name)??[],factionEvidence=input.faction?.resources??[],allowed=inventory.entries.map(entry=>entry.item).filter(item=>item.category==='equipment'||item.category==='professional'||item.category==='trade');if(!input.quest&&!input.faction&&allowed.length===0)throw new Error('No enemy, faction, location, or quest evidence supports loot.');const limit=input.difficulty==='deadly'?4:input.difficulty==='hard'?3:input.difficulty==='medium'?2:1;return allowed.slice(0,limit).map(item=>({...item,owner:null,history:[...item.history,`Recovered after conflict with ${input.enemyNpc.name} in ${input.location.name}.`],evidence:[...item.evidence,...questEvidence,...factionEvidence,input.location.environment,input.difficulty]}));}
function aggregate(context:ItemGenerationContext,entries:readonly InventoryEntry[]):Inventory{return updateInventory({id:context.idFactory(),ownerNpcId:context.npc.id,entries:[],carryingCapacity:Math.max(30,context.npc.weight.value*.45),totalWeight:0,totalValueGp:0,createdAt:context.now,updatedAt:context.now},entries,context.now);}
