import { useEffect,useMemo,useState } from 'react';import { FlavorEngine } from '../../utils/generator/flavor';import { FinalValidator } from '../../utils/generator/consistency';import { EditorRegenerationService } from '../../services/npcEditor';import type { FieldChangeRecord } from '../../workspace';import type { EditorDraft,NPCEditorProps,RegenerationProposal,RegenerationRequest } from './types';import { AdventureHookEditor,AppearanceEditor,BackstoryEditor,ChangeHistory,EditorHeader,FlavorEditor,GeneralEditor,GoalEditor,OccupationEditor,PersonalityEditor,RelationshipEditor,SaveControls,SecretEditor } from './sections';
type Tab='general'|'appearance'|'personality'|'occupation'|'backstory'|'goal'|'relationships'|'secret'|'hooks'|'flavor'|'history';
const tabs:readonly Tab[]=['general','appearance','personality','occupation','backstory','goal','relationships','secret','hooks','flavor','history'];
function initial(record:NPCEditorProps['record']):EditorDraft{return {npc:structuredClone(record.npc),flavor:structuredClone(record.flavor??FlavorEngine.enrich(record.npc,{seed:`${record.id}:editor-flavor`}).flavor)};}
function read(source:unknown,path:string):unknown{let current=source;for(const part of path.split('.')){if(current===null||typeof current!=='object')return undefined;current=(current as Record<string,unknown>)[part];}return current;}
function write<T>(source:T,path:string,value:unknown):T{const result=structuredClone(source),parts=path.split('.');let current=result as unknown as Record<string,unknown>;for(const part of parts.slice(0,-1)){const next=current[part];if(next===null||typeof next!=='object')throw new Error(`Editor path ${path} is invalid.`);current=next as Record<string,unknown>;}current[parts[parts.length-1]]=structuredClone(value);return result;}
function equal(left:unknown,right:unknown):boolean{return JSON.stringify(left)===JSON.stringify(right);}

export function NPCEditor({record,onSave,onClose,user}:NPCEditorProps){
  const [draft,setDraft]=useState<EditorDraft>(()=>initial(record)),[history,setHistory]=useState<readonly FieldChangeRecord[]>(record.metadata.changeHistory??[]),[tab,setTab]=useState<Tab>('general'),[proposal,setProposal]=useState<RegenerationProposal|null>(null),[autosave,setAutosave]=useState(false),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[confirmation,setConfirmation]=useState(''),[editorError,setEditorError]=useState('');
  const issues=useMemo(()=>FinalValidator.validate(draft),[draft]),blocking=issues.filter(issue=>issue.severity!=='warning');
  const sectionErrors=(sections:readonly string[])=>issues.filter(issue=>sections.includes(issue.section)).map(issue=>`${issue.message} Suggested correction: review the connected ${issue.section.replace(/([A-Z])/g,' $1')} values.`);
  const change=(path:string,value:unknown)=>{const oldValue=read(draft,path);if(equal(oldValue,value))return;setDraft(write(draft,path,value));setHistory(items=>[...items,{id:crypto.randomUUID(),field:path,oldValue:structuredClone(oldValue),newValue:structuredClone(value),changedAt:new Date().toISOString(),user}]);setDirty(true);setConfirmation('');};
  const regenerate=(request:RegenerationRequest)=>{try{setProposal(EditorRegenerationService.propose(draft,request));setEditorError('');}catch(reason){setEditorError(reason instanceof Error?reason.message:'This section could not be regenerated.');}};
  const save=async(auto=false)=>{if(blocking.length){setEditorError('Resolve the validation errors before saving. Your draft has not been changed automatically.');return;}setSaving(true);try{await onSave(draft,history,auto);setDirty(false);setConfirmation(auto?'Auto-saved':'Saved as a new version');setEditorError('');}catch(reason){setEditorError(reason instanceof Error?reason.message:'The NPC could not be saved.');}finally{setSaving(false);}};
  useEffect(()=>{if(autosave&&dirty){void save(true);}},[autosave,draft,history]);
  useEffect(()=>{const keydown=(event:KeyboardEvent)=>{if(event.key==='Escape'){if(proposal)setProposal(null);else onClose();}};window.addEventListener('keydown',keydown);return()=>window.removeEventListener('keydown',keydown);},[onClose,proposal]);
  const props={draft,change,regenerate};
  return <div className="npc-editor-overlay" role="dialog" aria-modal="true" aria-labelledby="npc-editor-title"><div className="npc-editor"><EditorHeader record={record} dirty={dirty} onClose={onClose}/><nav className="npc-editor-tabs" aria-label="NPC editor sections">{tabs.map(value=><button type="button" className={tab===value?'active':''} key={value} onClick={()=>setTab(value)}>{value.replace(/-/g,' ')}</button>)}</nav>{(editorError||blocking.length>0)&&<div className="editor-validation" role="alert"><strong>{editorError||`${blocking.length} validation issue${blocking.length===1?'':'s'} must be resolved.`}</strong>{blocking.slice(0,5).map(issue=><p key={`${issue.section}-${issue.code}`}>{issue.message}</p>)}</div>}<main className="npc-editor-body">
    {tab==='general'&&<GeneralEditor {...props} errors={sectionErrors(['age','race','religion'])}/>} {tab==='appearance'&&<AppearanceEditor {...props} errors={sectionErrors(['appearance'])}/>} {tab==='personality'&&<PersonalityEditor {...props} errors={sectionErrors(['personality','quote','voice','mannerisms'])}/>} {tab==='occupation'&&<OccupationEditor {...props} errors={sectionErrors(['occupation','dailyRoutine','inventory','residence'])}/>} {tab==='backstory'&&<BackstoryEditor {...props} errors={sectionErrors(['backstory'])}/>} {tab==='goal'&&<GoalEditor {...props} errors={sectionErrors(['goal'])}/>} {tab==='relationships'&&<RelationshipEditor {...props} errors={sectionErrors(['relationships'])}/>} {tab==='secret'&&<SecretEditor {...props} errors={sectionErrors(['secret','dmNotes'])}/>} {tab==='hooks'&&<AdventureHookEditor {...props} errors={sectionErrors(['adventureHooks'])}/>} {tab==='flavor'&&<FlavorEditor {...props} errors={sectionErrors(['inventory','residence','voice','quote','dmNotes','portraitPrompt','dailyRoutine','mannerisms'])}/>} {tab==='history'&&<ChangeHistory history={history}/>} </main><SaveControls autosave={autosave} onAutosave={setAutosave} onSave={()=>void save(false)} onCancel={onClose} disabled={!dirty||blocking.length>0} saving={saving} confirmation={confirmation}/>{proposal&&<div className="regeneration-preview" role="dialog" aria-modal="true" aria-label="Regeneration preview"><div><h3>Review Regeneration</h3><p>Only <code>{proposal.path}</code> will change.</p><div className="proposal-columns"><section><h4>Current version</h4><pre>{JSON.stringify(proposal.currentValue,null,2)}</pre></section><section><h4>New version</h4><pre>{JSON.stringify(proposal.newValue,null,2)}</pre></section></div><footer><button onClick={()=>setProposal(null)}>Reject</button><button className="button-primary" onClick={()=>{change(proposal.path,proposal.newValue);setProposal(null);}}>Accept</button></footer></div></div>}</div></div>;
}
export type * from './types';
