import { lazy,Suspense,useState,type CSSProperties } from 'react';
import { Alignment,SocialStatus,Wealth } from '../../types';
import type { useWorkspace } from '../../hooks/useWorkspace';
import type { WorkspaceCampaign,WorkspaceFilters,WorkspaceNPC,WorkspaceSort } from '../../workspace';
const ExportPanel=lazy(()=>import('../../features/export/components/ExportPanel').then(module=>({default:module.ExportPanel})));

interface Props {readonly workspace:ReturnType<typeof useWorkspace>;readonly onLoad:(npc:WorkspaceNPC['npc'])=>void;readonly onEdit:(record:WorkspaceNPC)=>void;readonly onDialogue:(record:WorkspaceNPC)=>void;readonly onVisual:(record:WorkspaceNPC)=>void;readonly onWorld:(campaign:WorkspaceCampaign)=>void}
function download(name:string,content:string,type:string):void{const url=URL.createObjectURL(new Blob([content],{type}));const anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();URL.revokeObjectURL(url);}
function words(value:string):string{return value.replace(/-/g,' ');}

export function SavedNPCPanel({workspace,onLoad,onEdit,onDialogue,onVisual,onWorld}:Props){
  const [editing,setEditing]=useState<string|null>(null),[details,setDetails]=useState<string|null>(null),[exportRecord,setExportRecord]=useState<WorkspaceNPC|null>(null),[folderName,setFolderName]=useState(''),[campaignName,setCampaignName]=useState(''),[tagName,setTagName]=useState(''),[tagColor,setTagColor]=useState('#9f7aea'),[autosave,setAutosave]=useState(false),[compare,setCompare]=useState<[number|null,number|null]>([null,null]);
  const records=workspace.page.items,all=workspace.snapshot?.npcs??[],folders=workspace.snapshot?.folders??[],campaigns=workspace.snapshot?.campaigns??[];
  const patchFilters=(patch:Partial<WorkspaceFilters>)=>{workspace.setFilters(value=>({...value,...patch}));workspace.setPageNumber(1);};
  const options=(selector:(record:WorkspaceNPC)=>string|null)=>[...new Set(all.map(selector).filter((value):value is string=>Boolean(value)))].sort();
  const addTag=(record:WorkspaceNPC)=>{const name=tagName.trim();if(!name)return;void workspace.setTag(record,{id:crypto.randomUUID(),name,color:tagColor});setTagName('');};
  const exportFile=async(format:'json'|'markdown')=>{const content=format==='json'?await workspace.exportJSON():await workspace.exportMarkdown();download(`smart-npc-workspace.${format==='json'?'json':'md'}`,content,format==='json'?'application/json':'text/markdown');};
  return <section className="saved-panel workspace-panel" aria-labelledby="saved-npcs-title">
    <header><div><span className="eyebrow">Campaign workspace</span><h2 id="saved-npcs-title">NPC Workspace</h2></div><span>{workspace.page.total} NPCs</span></header>
    {exportRecord&&<Suspense fallback={<div className="modal-loading" aria-live="polite">Loading export workspace…</div>}><ExportPanel record={exportRecord} onClose={()=>setExportRecord(null)}/></Suspense>}
    {workspace.error&&<p className="workspace-error" role="alert">{workspace.error}</p>}
    <div className="workspace-actions" aria-label="Workspace actions"><button disabled={!workspace.canUndo} onClick={()=>void workspace.undo()}>Undo</button><button disabled={!workspace.canRedo} onClick={()=>void workspace.redo()}>Redo</button><button onClick={()=>void exportFile('json')}>Export JSON</button><button onClick={()=>void exportFile('markdown')}>Export Markdown</button><label className="import-button">Import JSON<input type="file" accept="application/json,.json" onChange={event=>{const file=event.target.files?.[0];if(file)void file.text().then(source=>workspace.importJSON(source));event.currentTarget.value='';}}/></label><span title="PDF export is available through the typed PDFExporter interface">PDF prepared</span></div>
    <div className="workspace-create"><label>New folder<input value={folderName} onChange={event=>setFolderName(event.target.value)}/></label><button onClick={()=>{if(folderName.trim())void workspace.createFolder(folderName).then(()=>setFolderName(''));}}>Create Folder</button><label>New campaign<input value={campaignName} onChange={event=>setCampaignName(event.target.value)}/></label><button onClick={()=>{if(campaignName.trim())void workspace.createCampaign(campaignName).then(()=>setCampaignName(''));}}>Create Campaign</button></div>
    {campaigns.length>0&&<div className="campaign-launcher"><span>Campaign worlds</span>{campaigns.map(campaign=><button key={campaign.id} onClick={()=>onWorld(campaign)}>Open {campaign.name}</button>)}</div>}
    <div className="saved-controls"><input type="search" value={workspace.search} onChange={event=>{workspace.setSearch(event.target.value);workspace.setPageNumber(1);}} placeholder="Search name, race, occupation, alignment, campaign, tags, religion or goal" aria-label="Search workspace"/><select value={workspace.sort} onChange={event=>workspace.setSort(event.target.value as WorkspaceSort)} aria-label="Sort NPCs"><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="recently-modified">Recently Modified</option><option value="name">Name</option><option value="race">Race</option><option value="occupation">Occupation</option></select></div>
    <details className="workspace-filters"><summary>Workspace filters</summary><div className="filter-grid">
      <label>Race<select value={workspace.filters.race??''} onChange={event=>patchFilters({race:event.target.value||undefined})}><option value="">All races</option>{options(record=>record.npc.race).map(value=><option key={value}>{value}</option>)}</select></label>
      <label>Occupation<select value={workspace.filters.occupation??''} onChange={event=>patchFilters({occupation:event.target.value||undefined})}><option value="">All occupations</option>{options(record=>record.npc.occupation.title).map(value=><option key={value}>{value}</option>)}</select></label>
      <label>Alignment<select value={workspace.filters.alignment??''} onChange={event=>patchFilters({alignment:(event.target.value||undefined) as Alignment|undefined})}><option value="">All alignments</option>{Object.values(Alignment).map(value=><option value={value} key={value}>{words(value)}</option>)}</select></label>
      <label>Campaign<select value={workspace.filters.campaignId??''} onChange={event=>patchFilters({campaignId:event.target.value||undefined})}><option value="">All campaigns</option>{campaigns.map(value=><option value={value.id} key={value.id}>{value.name}</option>)}</select></label>
      <label>Wealth<select value={workspace.filters.wealth??''} onChange={event=>patchFilters({wealth:(event.target.value||undefined) as Wealth|undefined})}><option value="">All wealth</option>{Object.values(Wealth).map(value=><option value={value} key={value}>{words(value)}</option>)}</select></label>
      <label>Social status<select value={workspace.filters.socialStatus??''} onChange={event=>patchFilters({socialStatus:(event.target.value||undefined) as SocialStatus|undefined})}><option value="">All statuses</option>{Object.values(SocialStatus).map(value=><option value={value} key={value}>{words(value)}</option>)}</select></label>
      <label>Religion<select value={workspace.filters.religion??''} onChange={event=>patchFilters({religion:event.target.value||undefined})}><option value="">All religions</option>{options(record=>record.npc.religion).map(value=><option key={value}>{value}</option>)}</select></label>
      <label>Minimum age<input type="number" min="0" value={workspace.filters.minimumAge??''} onChange={event=>patchFilters({minimumAge:event.target.value?Number(event.target.value):undefined})}/></label><label>Maximum age<input type="number" min="0" value={workspace.filters.maximumAge??''} onChange={event=>patchFilters({maximumAge:event.target.value?Number(event.target.value):undefined})}/></label>
      <label>Favorites<select value={workspace.filters.favorite===undefined?'all':String(workspace.filters.favorite)} onChange={event=>patchFilters({favorite:event.target.value==='all'?undefined:event.target.value==='true'})}><option value="all">All</option><option value="true">Favorites only</option><option value="false">Not favorite</option></select></label>
      <label>Archive<select value={String(workspace.filters.archived??false)} onChange={event=>patchFilters({archived:event.target.value==='true'})}><option value="false">Active</option><option value="true">Archived</option></select></label>
    </div></details>
    {workspace.loading?<p className="saved-empty">Loading workspace…</p>:records.length===0?<p className="saved-empty">No NPCs match this workspace view. Generate and save a character, or adjust the active filters.</p>:<div className="saved-grid">{records.map(record=><article key={record.id} className={record.metadata.archived?'is-archived':''}>
      <div className="saved-main">{editing===record.id?<input autoFocus defaultValue={record.npc.name} aria-label={`Rename ${record.npc.name}`} onBlur={event=>{void workspace.rename(record.id,event.target.value);setEditing(null);}} onKeyDown={event=>{if(event.key==='Enter')event.currentTarget.blur();if(event.key==='Escape')setEditing(null);}}/>:<button onClick={()=>onLoad(record.npc)}><h3>{record.npc.name}</h3><p>{record.npc.race} / {record.npc.occupation.title} / Age {record.npc.age}</p><small>v{record.metadata.version} · {record.metadata.campaignIds.length} campaigns · {record.metadata.tags.length} tags</small></button>}</div>
      <div className="saved-card-actions"><button onClick={()=>setExportRecord(record)}>Export</button><button onClick={()=>onVisual(record)}>Portrait</button><button onClick={()=>onDialogue(record)}>Talk</button><button onClick={()=>onEdit(record)}>Edit NPC</button><button onClick={()=>void workspace.favorite(record)}>{record.metadata.favorite?'Unfavorite':'Favorite'}</button><button onClick={()=>setEditing(record.id)}>Rename</button><button onClick={()=>void workspace.duplicate(record.id)}>Duplicate</button><button onClick={()=>void workspace.archive(record)}>{record.metadata.archived?'Restore':'Archive'}</button><button onClick={()=>setDetails(details===record.id?null:record.id)}>Details</button><button onClick={()=>void workspace.remove(record.id)}>Delete</button></div>
      {details===record.id&&<div className="workspace-metadata">
        <label>Folder<select value={record.metadata.folderId??''} onChange={event=>void workspace.updateMetadata(record.id,{folderId:event.target.value||null,reason:'Moved folder'})}><option value="">No folder</option>{folders.map(folder=><option key={folder.id} value={folder.id}>{folder.name}</option>)}</select></label>
        <fieldset><legend>Campaigns</legend>{campaigns.map(campaign=><label key={campaign.id}><input type="checkbox" checked={record.metadata.campaignIds.includes(campaign.id)} onChange={event=>void workspace.updateMetadata(record.id,{campaignIds:event.target.checked?[...record.metadata.campaignIds,campaign.id]:record.metadata.campaignIds.filter(id=>id!==campaign.id),reason:'Updated campaigns'})}/>{campaign.name}</label>)}</fieldset>
        <div className="tag-editor"><label>Tag<input value={tagName} onChange={event=>setTagName(event.target.value)}/></label><input type="color" value={tagColor} onChange={event=>setTagColor(event.target.value)} aria-label="Tag color"/><button onClick={()=>addTag(record)}>Add tag</button></div><div className="workspace-tags">{record.metadata.tags.map(tag=><button style={{'--tag-color':tag.color} as CSSProperties} key={tag.id} onClick={()=>void workspace.removeTag(record,tag.id)}>{tag.name} ×</button>)}</div>
        <label className="notes-label">Private DM notes (Markdown)<textarea defaultValue={record.metadata.notes} onChange={event=>{if(autosave)workspace.scheduleAutosave(record.id,{notes:event.target.value,reason:'Auto-saved notes'});}} onBlur={event=>{if(!autosave)void workspace.updateMetadata(record.id,{notes:event.target.value,reason:'Updated notes'});}}/></label><label><input type="checkbox" checked={autosave} onChange={event=>setAutosave(event.target.checked)}/> Auto save notes</label>
        <label>Author<input defaultValue={record.metadata.author} onBlur={event=>{if(event.target.value.trim()!==record.metadata.author)void workspace.updateMetadata(record.id,{author:event.target.value.trim()||record.metadata.author,reason:'Updated author'});}}/></label><p>Created {new Date(record.metadata.createdAt).toLocaleDateString()} · Modified {new Date(record.metadata.modifiedAt).toLocaleString()}</p><button onClick={()=>void workspace.showVersions(record.id)}>Version history</button>
      </div>}
    </article>)}</div>}
    <nav className="workspace-pagination" aria-label="Workspace pages"><button disabled={workspace.page.page<=1} onClick={()=>workspace.setPageNumber(value=>Math.max(1,value-1))}>Previous</button><span>Page {workspace.page.page} of {workspace.page.pageCount}</span><button disabled={workspace.page.page>=workspace.page.pageCount} onClick={()=>workspace.setPageNumber(value=>value+1)}>Next</button></nav>
    {workspace.historyId&&<section className="version-panel" aria-labelledby="version-title"><header><h3 id="version-title">Version History</h3><button onClick={workspace.closeVersions}>Close</button></header><div>{workspace.history.map(version=><article key={version.id}><strong>Version {version.version}</strong><span>{new Date(version.savedAt).toLocaleString()} · {version.reason}</span><button onClick={()=>void workspace.restoreVersion(version.npcId,version.version)}>Restore</button><label>Compare<input type="checkbox" checked={compare.includes(version.version)} onChange={event=>setCompare(current=>event.target.checked?(current[0]===null?[version.version,current[1]]:[current[0],version.version]):current.map(value=>value===version.version?null:value) as [number|null,number|null])}/></label></article>)}</div><button disabled={compare.some(value=>value===null)} onClick={()=>{if(compare[0]!==null&&compare[1]!==null)void workspace.compareVersions(workspace.historyId!,compare[0],compare[1]);}}>Compare selected</button>{workspace.differences.length>0&&<ul>{workspace.differences.slice(0,50).map((difference,index)=><li key={`${difference.path}-${index}`}><code>{difference.path}</code> changed</li>)}</ul>}</section>}
  </section>;
}
