import { useCallback,useRef,useState } from 'react';
import { OCCUPATIONS,RELIGIONS } from '../constants';
import { SmartGenerationEngine } from '../utils/generator';
import { FlavorEngine } from '../utils/generator/flavor';
import type { NPC } from '../types';
import type { GenerationFilters,Locks,SectionKey } from '../ui/types';
import { useWorkspace } from './useWorkspace';

const DEFAULT_LOCKS:Locks={general:false,appearance:false,personality:false,occupation:false,backstory:false,goal:false,relationships:false,secret:false,hooks:false};
const DEFAULT_FILTERS:GenerationFilters={raceId:'',alignment:null,occupationId:'',minimumAge:null,maximumAge:null,religionId:'',gender:null,wealth:null,socialStatus:null};
function mergeLocked(previous:NPC|null,next:NPC,locks:Locks):NPC{if(!previous)return next;return {...next,...(locks.general?{name:previous.name,race:previous.race,subrace:previous.subrace,gender:previous.gender,age:previous.age,height:previous.height,weight:previous.weight,bodyBuild:previous.bodyBuild,alignment:previous.alignment,socialStatus:previous.socialStatus,wealth:previous.wealth,education:previous.education,languages:previous.languages,religion:previous.religion,birthplace:previous.birthplace,residence:previous.residence,maritalStatus:previous.maritalStatus,familyStatus:previous.familyStatus,voice:previous.voice,accent:previous.accent,reputation:previous.reputation}:{}),...(locks.appearance?{appearance:previous.appearance}:{}),...(locks.personality?{personality:previous.personality}:{}),...(locks.occupation?{occupation:previous.occupation}:{}),...(locks.backstory?{backstory:previous.backstory}:{}),...(locks.goal?{goal:previous.goal}:{}),...(locks.relationships?{relationships:previous.relationships}:{}),...(locks.secret?{secret:previous.secret}:{}),...(locks.hooks?{adventureHooks:previous.adventureHooks}:{})};}
function matches(npc:NPC,filters:GenerationFilters):boolean{const occupation=OCCUPATIONS.find(item=>item.id===filters.occupationId),deity=RELIGIONS.find(item=>item.id===filters.religionId),normalized=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]/g,'');return (!filters.raceId||normalized(npc.race)===normalized(filters.raceId))&&(!filters.alignment||npc.alignment===filters.alignment)&&(!occupation||npc.occupation.title===occupation.title)&&(!filters.minimumAge||npc.age>=filters.minimumAge)&&(!filters.maximumAge||npc.age<=filters.maximumAge)&&(!deity||npc.religion===deity.name)&&(!filters.gender||npc.gender===filters.gender)&&(!filters.wealth||npc.wealth===filters.wealth)&&(!filters.socialStatus||npc.socialStatus===filters.socialStatus);}

export function useNPCGenerator(){
  const workspace=useWorkspace();
  const [npc,setNpc]=useState<NPC|null>(null),[locks,setLocks]=useState<Locks>(DEFAULT_LOCKS),[filters,setFilters]=useState<GenerationFilters>(DEFAULT_FILTERS),[advanced,setAdvanced]=useState(false),[loading,setLoading]=useState(false),[progress,setProgress]=useState(0),[generationError,setGenerationError]=useState<string|null>(null);const counter=useRef(0);
  const candidate=useCallback((scope:string):NPC=>{for(let attempt=0;attempt<4;attempt+=1){const seed=`${Date.now()}-${counter.current++}-${scope}-${attempt}`;const generated=SmartGenerationEngine.generate({seed,raceId:filters.raceId||undefined,alignment:filters.alignment??undefined,gender:filters.gender??undefined,occupationId:filters.occupationId||undefined,religionId:filters.religionId||undefined,minimumAge:filters.minimumAge??undefined,maximumAge:filters.maximumAge??undefined,wealth:filters.wealth??undefined,socialStatus:filters.socialStatus??undefined}).npc;if(matches(generated,filters))return generated;}throw new Error('No NPC matched every active filter. Broaden one or more filters and try again.');},[filters]);
  const generate=useCallback(async()=>{setLoading(true);setGenerationError(null);setProgress(8);const timer=window.setInterval(()=>setProgress(value=>Math.min(92,value+7)),90);try{await new Promise(resolve=>window.setTimeout(resolve,320));setNpc(current=>mergeLocked(current,candidate('global'),locks));setProgress(100);}catch(reason){setGenerationError(reason instanceof Error?reason.message:'The generator could not complete this NPC.');}finally{window.clearInterval(timer);window.setTimeout(()=>setLoading(false),180);}},[candidate,locks]);
  const reroll=useCallback(async(section:SectionKey,field?:string,index?:number)=>{if(locks[section])return;setGenerationError(null);try{const next=candidate(`${section}:${field??'all'}:${index??0}`);setNpc(current=>{if(!current)return next;if(!field)return mergeLocked(current,next,Object.fromEntries(Object.keys(DEFAULT_LOCKS).map(key=>[key,key!==section])) as unknown as Locks);switch(section){case'general':if(field==='name')return {...current,name:next.name};if(field==='age')return {...current,age:next.age};if(field==='race')return {...current,race:next.race,subrace:next.subrace};return current;case'appearance':return {...current,appearance:{...current.appearance,[field]:next.appearance[field as keyof NPC['appearance']]}};case'personality':return {...current,personality:{...current.personality,[field]:next.personality[field as keyof NPC['personality']]}};case'occupation':return {...current,occupation:next.occupation};case'backstory':if(index!==undefined){const chapters=[...current.backstory];chapters[index]=next.backstory[index];return {...current,backstory:chapters as unknown as NPC['backstory']};}return {...current,backstory:next.backstory};case'goal':return {...current,goal:next.goal};case'relationships':return {...current,relationships:next.relationships};case'secret':return {...current,secret:next.secret};case'hooks':if(index!==undefined){const hooks=[...current.adventureHooks];hooks[index]=next.adventureHooks[index];return {...current,adventureHooks:hooks as unknown as NPC['adventureHooks']};}return {...current,adventureHooks:next.adventureHooks};}});}catch(reason){setGenerationError(reason instanceof Error?reason.message:'That field could not be regenerated.');}},[candidate,locks]);
  const toggleLock=useCallback((section:SectionKey)=>setLocks(value=>({...value,[section]:!value[section]})),[]),clear=useCallback(()=>{setNpc(null);setGenerationError(null);setProgress(0);},[]);
  const save=useCallback(async()=>{if(!npc)return;try{const flavor=FlavorEngine.enrich(npc,{seed:`${npc.id}:workspace-flavor`}).flavor,saved=await workspace.save(npc,'Local Dungeon Master',{flavor});if(saved)setNpc(saved.npc);}catch(reason){setGenerationError(reason instanceof Error?reason.message:'The NPC could not be prepared for the workspace.');}},[npc,workspace]);
  return {npc,setNpc,locks,filters,setFilters,advanced,setAdvanced,loading,progress,error:generationError,generate,reroll,toggleLock,clear,save,workspace};
}
