import type { Alignment } from '../../../types';

export interface Coordinates {readonly x:number;readonly y:number;readonly system:'grid'|'cartesian'|'latitude-longitude'}
export interface WorldLocation {readonly id:string;readonly name:string;readonly regionId:string|null;readonly coordinates:Coordinates|null;readonly environment:string;readonly connectedLocationIds:readonly string[]}
export interface TravelRoute {readonly id:string;readonly originId:string;readonly destinationId:string;readonly distance:number;readonly distanceUnit:'miles'|'kilometers'|'days';readonly terrain:string;readonly dangerLevel:number}
export interface Region extends WorldLocation {readonly description:string;readonly culture:string;readonly cityIds:readonly string[]}
export interface RaceDistribution {readonly race:string;readonly percentage:number}
export interface ImportantLocation {readonly id:string;readonly name:string;readonly type:string;readonly description:string}
export interface City extends WorldLocation {readonly population:number;readonly raceDistribution:readonly RaceDistribution[];readonly government:string;readonly leaderNpcId:string|null;readonly economy:readonly string[];readonly dangerLevel:number;readonly religionIds:readonly string[];readonly importantLocations:readonly ImportantLocation[];readonly npcIds:readonly string[];readonly history:readonly string[]}
export type FactionType='guild'|'kingdom'|'religious-order'|'criminal-organization'|'military-group'|'mage-circle'|'rebellion'|'merchant-company'|'secret-society';
export interface Faction {readonly id:string;readonly name:string;readonly type:FactionType;readonly alignment:Alignment;readonly leaderNpcId:string|null;readonly memberNpcIds:readonly string[];readonly goals:readonly string[];readonly resources:readonly string[];readonly territoryLocationIds:readonly string[];readonly enemyFactionIds:readonly string[];readonly allyFactionIds:readonly string[];readonly history:readonly string[];readonly secrets:readonly string[];readonly isPublic:boolean}
export interface Guild {readonly id:string;readonly factionId:string;readonly name:string;readonly profession:string;readonly leaderNpcId:string|null;readonly memberNpcIds:readonly string[];readonly reputation:string;readonly wealth:string;readonly rivalGuildIds:readonly string[];readonly missions:readonly string[];readonly headquartersLocationId:string|null}
export interface Kingdom {readonly id:string;readonly name:string;readonly capitalCityId:string|null;readonly rulerNpcId:string|null;readonly regionIds:readonly string[];readonly cityIds:readonly string[];readonly government:string;readonly history:readonly string[]}
export type WorldRelationshipType='family'|'friend'|'enemy'|'rival'|'mentor'|'ally'|'romance'|'employer'|'member'|'leader';
export type RelationshipStatus='active'|'strained'|'broken'|'secret'|'former'|'deceased';
export interface RelationshipEdge {readonly id:string;readonly sourceNpcId:string;readonly targetNpcId:string;readonly type:WorldRelationshipType;readonly strength:number;readonly history:string;readonly trust:number;readonly fear:number;readonly respect:number;readonly currentStatus:RelationshipStatus}
export type FamilyRelation='parent'|'child'|'sibling'|'partner'|'ancestor'|'descendant';
export interface FamilyLink {readonly id:string;readonly sourceNpcId:string;readonly targetNpcId:string;readonly relation:FamilyRelation;readonly history:string}
export interface World {readonly id:string;readonly name:string;readonly description:string;readonly era:string;readonly theme:string;readonly regions:readonly Region[];readonly cities:readonly City[];readonly kingdoms:readonly Kingdom[];readonly factions:readonly Faction[];readonly guilds:readonly Guild[];readonly religions:readonly string[];readonly history:readonly string[];readonly relationships:readonly RelationshipEdge[];readonly familyLinks:readonly FamilyLink[];readonly routes:readonly TravelRoute[]}
export interface WorldBrief {readonly name:string;readonly description:string;readonly era:string;readonly theme:string;readonly environments:readonly string[];readonly cultures:readonly string[]}
export interface WorldGenerationInput {readonly brief:WorldBrief;readonly regions:readonly Region[];readonly cities:readonly City[];readonly factions:readonly Faction[];readonly guilds:readonly Guild[];readonly kingdoms?:readonly Kingdom[];readonly religions?:readonly string[];readonly history?:readonly string[];readonly relationships?:readonly RelationshipEdge[];readonly familyLinks?:readonly FamilyLink[];readonly routes?:readonly TravelRoute[]}
export interface WorldGenerationResult {readonly world:World;readonly stages:readonly ['world','regions','cities','factions','guilds','npcs','relationships','events'];readonly validationIssues:readonly WorldValidationIssue[]}
export interface WorldSearchResult {readonly kind:'npc'|'city'|'faction'|'event';readonly id:string;readonly title:string;readonly detail:string}
export interface WorldValidationIssue {readonly code:string;readonly section:'world'|'city'|'faction'|'guild'|'relationship'|'family'|'timeline';readonly entityId:string;readonly message:string;readonly severity:'warning'|'error'}
