import type { NPC } from '../../../../types';import type { City,Faction,Guild,World,WorldBrief,WorldGenerationInput,WorldGenerationResult,WorldValidationIssue } from '../../types';
const lower=(values:readonly string[])=>values.join(' ').toLowerCase();
export function deriveCityEconomy(environment:string):readonly string[]{const e=environment.toLowerCase();if(e.includes('coast')||e.includes('port'))return['shipping','fishing','shipbuilding','maritime trade'];if(e.includes('mountain')||e.includes('mine'))return['mining','metalwork','stonework','overland trade'];if(e.includes('forest'))return['forestry','herbalism','hunting','woodcraft'];if(e.includes('farm')||e.includes('plain'))return['agriculture','livestock','milling','market trade'];return['local crafts','regional trade','services'];}
export function createCity(input:Omit<City,'id'|'economy'|'connectedLocationIds'> & {readonly economy?:readonly string[]}):City{return{...input,id:crypto.randomUUID(),economy:input.economy??deriveCityEconomy(input.environment),connectedLocationIds:[]};}
export function createWorld(brief:WorldBrief):World{if(!brief.name.trim()||!brief.description.trim())throw new Error('A world name and description are required.');return{id:crypto.randomUUID(),name:brief.name.trim(),description:brief.description.trim(),era:brief.era.trim(),theme:brief.theme.trim(),regions:[],cities:[],kingdoms:[],factions:[],guilds:[],religions:[],history:[],relationships:[],familyLinks:[],routes:[]};}
export function assignRelevantNpcs(city:City,npcs:readonly NPC[]):City{const economy=lower(city.economy);const matching=npcs.filter(n=>{const job=n.occupation.title.toLowerCase();return city.environment.toLowerCase().includes('port')?/(sail|merchant|pirate|ship|dock)/.test(job):city.environment.toLowerCase().includes('mine')?/(miner|smith|jewel|stone|merchant)/.test(job):economy.split(' ').some(term=>term.length>4&&job.includes(term));});return{...city,npcIds:[...new Set([...city.npcIds,...matching.map(n=>n.id)])]};}
export function validateWorld(world:World,npcs:readonly NPC[]):readonly WorldValidationIssue[]{const issues:WorldValidationIssue[]=[];for(const city of world.cities){const palaces=city.importantLocations.filter(v=>/palace/i.test(v.type+' '+v.name)).length;if(city.population<1000&&palaces>1)issues.push({code:'city.excess-palaces',section:'city',entityId:city.id,message:'A settlement this small cannot sustain multiple royal palaces.',severity:'error'});if(city.raceDistribution.reduce((sum,v)=>sum+v.percentage,0)!==100)issues.push({code:'city.race-distribution',section:'city',entityId:city.id,message:'Race distribution must total 100%.',severity:'error'});}
 const byNpc=new Map(npcs.map(n=>[n.id,n]));for(const faction of world.factions){if(faction.type==='secret-society'&&faction.isPublic)issues.push({code:'faction.public-secret',section:'faction',entityId:faction.id,message:'A secret society cannot also be publicly acknowledged.',severity:'error'});const leader=faction.leaderNpcId?byNpc.get(faction.leaderNpcId):undefined;if(leader&&leader.age<16)issues.push({code:'faction.child-leader',section:'faction',entityId:faction.id,message:'A child cannot lead this faction without an explicit exceptional explanation.',severity:'error'});}return issues;}
export function generationPlan(brief:WorldBrief,npcs:readonly NPC[]):Readonly<{world:World;stages:readonly ['world','regions','cities','factions','guilds','npcs','relationships','events'];eligibleNpcIds:readonly string[]}>{return{world:createWorld(brief),stages:['world','regions','cities','factions','guilds','npcs','relationships','events'],eligibleNpcIds:npcs.map(n=>n.id)};}
export function generateWorld(input:WorldGenerationInput,npcs:readonly NPC[]):WorldGenerationResult{const base=createWorld(input.brief),cities=input.cities.map(city=>assignRelevantNpcs({...city,economy:city.economy.length?city.economy:deriveCityEconomy(city.environment)},npcs)),world:World={...base,regions:input.regions,cities,factions:input.factions,guilds:input.guilds,kingdoms:input.kingdoms??[],religions:input.religions??[],history:input.history??[],relationships:input.relationships??[],familyLinks:input.familyLinks??[],routes:input.routes??[]};return{world,stages:['world','regions','cities','factions','guilds','npcs','relationships','events'],validationIssues:validateWorld(world,npcs)};}
export type WorldEntityDraft=City|Faction|Guild;
