import type { NPC } from '../../../types';import type { Quest } from '../../questGenerator';import type { City,Faction,World } from '../../world';import type { Item,ItemRarity,ItemType,QuestItem } from './item';
export interface InventoryEntry {readonly item:Item;readonly quantity:number;readonly equipped:boolean;readonly locked:boolean;readonly notes:string}
export interface Inventory {readonly id:string;readonly ownerNpcId:string;readonly entries:readonly InventoryEntry[];readonly carryingCapacity:number;readonly totalWeight:number;readonly totalValueGp:number;readonly createdAt:string;readonly updatedAt:string}
export interface EquipmentSet {readonly npcId:string;readonly weaponIds:readonly string[];readonly armorId:string|null;readonly shieldId:string|null;readonly toolIds:readonly string[];readonly clothingIds:readonly string[];readonly accessoryIds:readonly string[]}
export interface ShopProduct {readonly item:Item;readonly price:Item['value'];readonly stock:number;readonly availability:'plentiful'|'available'|'limited'|'scarce'|'unique'}
export interface MerchantShop {readonly id:string;readonly merchantNpcId:string;readonly shopName:string;readonly category:string;readonly products:readonly ShopProduct[];readonly supplierFactionIds:readonly string[];readonly competitorFactionIds:readonly string[];readonly cityId:string;readonly updatedAt:string}
export interface ItemGenerationContext {readonly npc:NPC;readonly world:World;readonly city:City|null;readonly factions:readonly Faction[];readonly quests:readonly Quest[];readonly idFactory:()=>string;readonly now:string}
export interface LootGenerationInput {readonly enemyNpc:NPC;readonly location:City;readonly difficulty:Quest['difficulty'];readonly faction:Faction|null;readonly quest:Quest|null;readonly world:World;readonly idFactory?:()=>string;readonly now?:string}
export interface InventoryValidationIssue {readonly code:string;readonly itemId:string|null;readonly field:'inventory'|'rarity'|'price'|'equipment'|'origin'|'owner'|'weight';readonly severity:'error'|'warning';readonly message:string}
export interface InventoryGenerationResult {readonly inventory:Inventory;readonly equipment:EquipmentSet;readonly issues:readonly InventoryValidationIssue[];readonly stages:readonly ['npc','occupation','wealth','lifestyle','inventory','equipment','validation']}
export interface ItemFilters {readonly search:string;readonly types:readonly ItemType[];readonly rarities:readonly ItemRarity[];readonly equipped?:boolean;readonly locked?:boolean;readonly sort:'name'|'value-ascending'|'value-descending'|'weight'|'rarity'}
export interface InventoryExport {readonly format:'smart-npc-inventory';readonly version:1;readonly inventory:Inventory;readonly questItems:readonly QuestItem[]}
export interface InventoryPDFExporter {export(inventory:Inventory):Promise<Blob>}
