import { npcMarkdown } from '../ui/format';import type { WorkspaceExport,WorkspaceSnapshot } from './types';
function object(value:unknown):value is Record<string,unknown>{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value);}
function text(value:unknown):value is string{return typeof value==='string';}
function metadata(value:unknown):boolean{return object(value)&&text(value.createdAt)&&text(value.modifiedAt)&&Number.isInteger(value.version)&&Number(value.version)>0&&typeof value.favorite==='boolean'&&typeof value.archived==='boolean'&&Array.isArray(value.tags)&&value.tags.every(tag=>object(tag)&&text(tag.id)&&text(tag.name)&&text(tag.color))&&text(value.notes)&&(value.folderId===null||text(value.folderId))&&Array.isArray(value.campaignIds)&&value.campaignIds.every(text)&&text(value.author);}
function npc(value:unknown):boolean{return object(value)&&text(value.id)&&text(value.name)&&text(value.race)&&typeof value.age==='number'&&text(value.alignment)&&object(value.occupation)&&text(value.occupation.title)&&object(value.goal)&&text(value.goal.currentGoal)&&Array.isArray(value.backstory)&&Array.isArray(value.adventureHooks);}
function named(value:unknown):boolean{return object(value)&&text(value.id)&&text(value.name)&&text(value.createdAt)&&text(value.modifiedAt);}
export function isWorkspaceSnapshot(value:unknown):value is WorkspaceSnapshot {if(!object(value)||value.schemaVersion!==1||!Array.isArray(value.npcs)||!Array.isArray(value.versions)||!Array.isArray(value.folders)||!Array.isArray(value.campaigns))return false;return value.npcs.every(item=>object(item)&&text(item.id)&&npc(item.npc)&&(item.flavor===undefined||item.flavor===null||object(item.flavor))&&metadata(item.metadata))&&value.versions.every(item=>object(item)&&text(item.id)&&text(item.npcId)&&typeof item.version==='number'&&text(item.savedAt)&&npc(item.npc)&&(item.flavor===undefined||item.flavor===null||object(item.flavor))&&metadata(item.metadata)&&text(item.reason))&&value.folders.every(named)&&value.campaigns.every(named);}
export function parseWorkspaceJSON(source:string):WorkspaceSnapshot{const parsed:unknown=JSON.parse(source);const candidate=parsed&&typeof parsed==='object'&&(parsed as Record<string,unknown>).format==='smart-npc-workspace'?(parsed as Record<string,unknown>).data:parsed;if(!isWorkspaceSnapshot(candidate))throw new Error('The selected file is not a valid Smart NPC workspace export.');return structuredClone(candidate);}
export function workspaceJSON(snapshot:WorkspaceSnapshot):string{const payload:WorkspaceExport={format:'smart-npc-workspace',exportedAt:new Date().toISOString(),data:snapshot};return JSON.stringify(payload,null,2);}
export function workspaceMarkdown(snapshot:WorkspaceSnapshot,includeNotes=true):string{return snapshot.npcs.map(record=>{const campaigns=snapshot.campaigns.filter(item=>record.metadata.campaignIds.includes(item.id)).map(item=>item.name).join(', ')||'None';const tags=record.metadata.tags.map(tag=>tag.name).join(', ')||'None';return `${npcMarkdown(record.npc)}\n\n## Workspace\n\n- Author: ${record.metadata.author}\n- Campaigns: ${campaigns}\n- Tags: ${tags}\n- Version: ${record.metadata.version}${includeNotes&&record.metadata.notes?`\n\n## Private DM Notes\n\n${record.metadata.notes}`:''}`;}).join('\n\n---\n\n');}
