import type { NameCulture,NameOrder,SurnameKind } from './types';
const p=(value:string):readonly string[]=>value?value.split('|'):[];
const SHARED_HONORIFICS=['Sir','Lady','Honored','Elder'] as const;const SHARED_TITLES=['Captain','Commander','High Priest','Temple Elder','Guildmaster','Master Smith','Archmage','Magister','Professor','Master Scholar','Magistrate','Councillor','Lord','Lady','Master Merchant','Waymaster'] as const;
function culture(id:string,name:string,races:string,male:string,female:string,neutral:string,families:string,clans:string,nicknames:string,order:NameOrder='given-family',surnameKind:SurnameKind='family',description='Names follow the established customs of this culture.'):NameCulture{return {id,name,raceIds:p(races),maleNames:p(male),femaleNames:p(female),neutralNames:p(neutral),familyNames:p(families),clanNames:p(clans),nicknames:p(nicknames),honorifics:SHARED_HONORIFICS,titles:SHARED_TITLES,rules:{order,surnameKind,surnameRequired:surnameKind!=='none',allowsVirtueName:id==='tiefling',allowsNickname:true,description}};}

export const NAME_CULTURES:readonly NameCulture[]=[
 culture('human-chondathan','Chondathan','human|half-elf','Darvin|Dorn|Evendur|Gorstag|Malark|Morn|Randal|Stedd','Arveene|Esvele|Jhessail|Kerri|Lureene|Miri|Rowan|Shandri','Avery|Kestrel|Merren|Rell|Tarn|Vale','Amblecrown|Buckman|Dundragon|Evenwood|Greycastle|Tallstag|Westwood|Wyvernspur','','Fox|Old Bear|Blackblade|Whisper|Redcloak'),
 culture('human-calishite','Calishite','human|half-elf','Aseir|Bardeid|Haseid|Khemed|Mehmen|Sudeiman|Zasheir|Farid','Atala|Ceidil|Hama|Jasmal|Meilil|Seipora|Yasheira|Zasheida','Aziz|Iman|Nuri|Rahi|Sahir|Zafir','Basha|Dumein|Jassan|Khalid|Mostana|Pashar|Rein|Tahir','','Falcon|Silkhand|Bright Coin|Desert Rose|The Patient'),
 culture('human-damaran','Damaran','human|half-elf','Bor|Fodel|Glar|Grigor|Igan|Ivor|Kosef|Pavel','Alethra|Kara|Katernin|Mara|Natali|Olma|Tana|Zora','Misha|Nika|Sasha|Vanya|Zhenya|Rin','Bersk|Chernin|Dotsk|Kulenov|Marsk|Nemetsk|Shemov|Starag','','Ironhand|Old Wolf|Snowfox|The Steady|Blackblade'),
 culture('human-illuskan','Illuskan','human|half-elf','Ander|Blath|Bran|Frath|Geth|Lander|Luth|Stor','Amafrey|Betha|Cefrey|Kethra|Mara|Olga|Silifrey|Westra','Ari|Bryn|Hale|Rann|Skye|Winter','Brightwood|Helder|Hornraven|Lackman|Stormwind|Windriver|Iceward|Rimehelm','','Old Bear|Stormcrow|Ironhand|One-Eye|The Bold'),
 culture('human-mulan','Mulan','human|half-elf','Aoth|Bareris|Ehput-Ki|Kethoth|Mumed|Ramas|So-Kehur|Urhur','Arizima|Chathi|Nephis|Nulara|Murithi|Sefris|Thola|Umara','Ankh|Hori|Neru|Sati|Tem|Zuri','Ankhalab|Anskuld|Fezim|Hahpet|Nathandem|Sepret|Uuthrakt|Zulmir','','Gold Voice|The Scribe|Sun-Eye|Quiet Reed|The Devout'),
 culture('human-rashemi','Rashemi','human|half-elf','Borivik|Faurgar|Jandar|Kanithar|Madislak|Ralmevik|Shaumar|Vladislak','Fyevarra|Hulmarra|Immith|Imzel|Navarra|Shevarra|Tammith|Yuldra','Darya|Miro|Nadya|Rada|Valen|Yuri','Chergoba|Dyernina|Iltazyara|Murnyethara|Stayanoga|Ulmokina|Vladaya|Yaroven','','Old Bear|Witch-Friend|Ironhand|Snow Hawk|The Stubborn'),
 culture('human-shou','Shou','human|half-elf','An|Chen|Chi|Fai|Jiang|Jun|Long|Wen','Bai|Chao|Jia|Lei|Mei|Qiao|Shui|Tai','Bo|Kai|Lian|Ren|Shan|Tao','Chien|Huang|Kao|Kung|Lao|Ling|Shin|Wan','','Jade Fox|Quiet Reed|Iron Crane|The Patient|Bright Blade','family-given'),
 culture('human-turami','Turami','human|half-elf','Anton|Diero|Marcon|Pieron|Rimardo|Romero|Salazar|Umbero','Balama|Dona|Faila|Jalana|Luisa|Marta|Quara|Selise','Caro|Luz|Mar|Paz|Sol|Val','Agosto|Astorio|Calabra|Domine|Falone|Marivaldi|Pisacar|Ramondo','','Redcloak|Silver Tongue|Fox|The Gallant|Old Lion'),
 culture('dwarf','Dwarven Clans','dwarf|hill-dwarf|mountain-dwarf|duergar','Adrik|Baern|Dain|Darrak|Eberk|Fargrim|Harbek|Rurik','Amber|Audhild|Dagnal|Eldeth|Falkrunn|Helja|Kathra|Vistra','Arin|Bryn|Dorn|Keld|Rinn|Tor','','Balderk|Battlehammer|Brawnanvil|Fireforge|Frostbeard|Ironfist|Rumnaheim|Torunn','Ironhand|Stoneheart|Forgewise|Goldnose|Deepdelver','given-family','clan','A clan elder grants a traditional personal name; clan identity is permanent and honored.'),
 culture('elf-high','High Elven','elf|high-elf|half-elf','Adran|Aelar|Aramil|Erevan|Hadarai|Paelias|Theren|Varis','Adrie|Althaea|Caelynn|Ielenia|Leshanna|Meriele|Sariel|Shava','Ara|Bryn|Eryn|Faen|Lael|Rael|Rinn|Thia','Amakiir|Amastacia|Galanodel|Holimion|Liadon|Meliamne|Siannodel|Xiloscient','','Moonwhisper|Star-Eye|The Rememberer|Silver Voice|Dawnblade'),
 culture('elf-wood','Wood Elven','wood-elf|elf|half-elf','Aelar|Carric|Erdan|Laucian|Peren|Rolen|Soveliss|Tharivol','Antinua|Birel|Enna|Felosial|Lia|Naivara|Thia|Vadania','Bryn|Del|Eryn|Faen|Naeris|Rinn|Sai|Thia','Autumnleaf|Briarbough|Greenmantle|Liadon|Meliamne|Oakstaff|Riverbend|Windgrove','','Leafrunner|Quiet Bow|Thornfriend|Fox|The Watchful'),
 culture('elf-drow','Drow','dark-elf-drow','Drisinil|Ilmryn|Jhael|Nalfein|Ryld|Sorn|Tebryn|Veldrin','Akordia|Briza|Eclavdra|Ilvara|Liriel|Sabrae|Shyntlara|Vierna','Aun|Ilyth|Nym|Riz|Sszin|Vrae','Auvryndar|Baenre|Duskryn|Hunzrin|Mizzrym|Tekenduis|Xorlarrin|Zauvirr','','Nightblade|Silken Voice|Whisper|Spiderkissed|The Exile'),
 culture('elf-eladrin','Eladrin','eladrin','Aelisar|Erevan|Faelar|Immeral|Loriel|Quarion|Soveliss|Theren','Althaea|Caelynn|Ilyrana|Lethia|Naivara|Sariel|Shanairra|Valanthe','Autumn|Briar|Dawn|Morrow|Rain|Winter','Dawnpetal|Eveningfall|Moonbrook|Silverfrond|Starflower|Summerwind|Wintermere|Zephyrbloom','','Dawnsong|Gloam-Eye|Summerheart|Winterthorn|The Mercurial'),
 culture('elf-sea','Sea Elven','sea-elf','Aelar|Coralin|Delian|Erevan|Marel|Nymor|Thalion|Varis','Aquina|Caelynn|Lia|Marilla|Naivara|Nerissa|Silaqui|Thia','Coral|Foam|Pearl|Rain|Tide|Wave','Coralcrest|Deepcurrent|Moonwake|Pearlfin|Reefguard|Saltbloom|Tidecaller|Wavewhisper','','Deep-Eye|Pearldiver|Stormwake|Tidefriend|The Far-Swimmer'),
 culture('elf-astral','Astral Elven','astral-elf','Aelar|Caelir|Erevan|Ithil|Quarion|Soveliss|Theren|Vaelis','Althaea|Ielenia|Lethiel|Naivara|Sariel|Shava|Thia|Xanaphia','Comet|Dawn|Echo|Nova|Star|Vesper','Astralweave|Cometfall|Moonpath|Silvervoid|Starwake|Sunward|Voidbloom|Worldwalker','','Star-Eye|Voidwalker|The Timeless|Silver Voice|Far-Wanderer'),
 culture('halfling','Halfling','halfling|lightfoot-halfling|stout-halfling','Alton|Cade|Corrin|Eldon|Garret|Lyle|Milo|Roscoe','Andry|Bree|Callie|Kithri|Lavinia|Merla|Nedda|Seraphina','Bryn|Cori|Merry|Pip|Robin|Tavi','Brushgather|Goodbarrel|Greenbottle|Highhill|Hilltopple|Leagallow|Tealeaf|Underbough','','Quickstep|Goodluck|Fox|Two-Pies|The Cheerful'),
 culture('gnome','Gnomish','gnome|forest-gnome|rock-gnome|deep-gnome','Alston|Boddynock|Brocc|Dimble|Fonkin|Gerbo|Kellen|Zook','Breena|Caramip|Donella|Ellywick|Lilli|Nissa|Orla|Zanna','Bim|Fizz|Nim|Pip|Tink|Wrenn','Beren|Daergel|Folkor|Garrick|Nackle|Ningel|Scheppen|Turen','','Badger|Doublelock|Oneshoe|Sparklegem|Stumbleduck'),
 culture('orcish','Orcish','orc|half-orc','Dench|Feng|Gell|Henk|Holg|Imsh|Keth|Thokk','Baggi|Emen|Engong|Kansif|Myev|Neega|Ovak|Shautha','Ash|Dren|Kesh|Mok|Ruk|Vash','Doomhammer|Ironhide|Skullcleaver|Stormfang|Strongbow|Thunderhide|Warsong|Wolfbrother','','Blackblade|Ironhand|Old Bear|One-Eye|The Unbroken'),
 culture('dragonborn','Dragonborn Clans','dragonborn|kobold|lizardfolk','Arjhan|Balasar|Bharash|Ghesh|Heskan|Kriv|Medrash|Rhogar','Akra|Biri|Daar|Harann|Kava|Mishann|Nala|Thava','Ash|Climber|Leaper|Pious|Shieldbiter|Zealous','','Clethtinthiallor|Daardendrian|Delmirev|Kepeshkmolik|Kerrhylon|Myastan|Norixius|Turnuroth','Climber|Earbender|Leaper|Pious|Shieldbiter','clan-given','clan','Clan names precede personal names as a public expression of honor.'),
 culture('tiefling','Tiefling','tiefling','Akmenos|Amnon|Barakas|Damakos|Ekemon|Iados|Kairon|Morthos','Akta|Anakis|Bryseis|Damaia|Kallista|Makaria|Nemeia|Rieta','Creed|Glory|Hope|Ideal|Quest|Reverence|Sorrow|Temerity','Avernus|Dispatir|Kairon|Melech|Nerath|Orianna|Therai|Valafar','','Ash|Blackblade|Ember|Whisper|The Defiant'),
 culture('celestial','Celestial-Touched','aasimar','Arael|Cassiel|Elyon|Ithuriel|Malach|Raziel|Samiel|Uriel','Anael|Cassia|Eliora|Haniel|Liora|Seraphine|Uriela|Zaphira','Dawn|Grace|Mercy|Radiance|Solace|Vesper','Brightmantle|Dawnward|Goldwing|Lightbearer|Morningstar|Silverhand|Sunweaver|Trueheart','','Dawn-Blessed|Silver Voice|The Merciful|Lightbearer|Star-Eye'),
 culture('giantkin','Giantkin','goliath|firbolg','Aukan|Eglath|Gae-Al|Keothi|Lo-Kag|Maveith|Nalla|Vimak','Gae-Al|Gauthak|Ilikan|Kolae|Manneo|Nalla|Pethani|Uthal','Cloud|Flint|Rain|Stone|Storm|Vale','','Anakalathai|Kathol-Olari|Kolae-Gileana|Ogolakanu|Thuliaga|Vaimei-Laga','Bearkiller|Dawncaller|Fearless|Skywatcher|Stonehand','given-family','clan'),
 culture('goblinoid','Goblinoid','goblin|hobgoblin|bugbear','Draz|Grek|Hruk|Kraz|Mog|Ruk|Thrag|Vek','Brikka|Droka|Gree|Makka|Neka|Rikka|Vexa|Zru','Grit|Nix|Rag|Skit|Vrik|Zek','Ashbanner|Ironmark|Redfang|Stoneboot|Wolfscar|Yelloweye|Blacktooth|Longmarch','','Nimble|One-Eye|Redknife|Slyboots|Whisper'),
 culture('beastfolk','Beastfolk','tabaxi|leonin|shifter|harengon|owlin|kenku|hadozee','Bright Mane|Cliff Runner|Distant Thunder|Quiet Step|Red Claw|Swift Current|Tall Grass|Winter Pelt','Dawn Song|Falling Rain|Golden Eye|Moon Shadow|Quiet Brook|Soft Wind|Summer Cloud|Willow Branch','Ash|Echo|Fox|Rain|Reed|Whisper','Dawn Pride|High Roost|Long Road|Moon Clan|Reed Warren|Stone Pack|Sun Pride|Wind Nest','','Fox|Old Bear|One-Eye|Whisper|Quickstep'),
 culture('fey','Fey','satyr|fairy|centaur','Aster|Bramble|Celandine|Daphnis|Melios|Oberon|Puck|Thistle','Aella|Calla|Daphne|Ianthe|Nerine|Phaedra|Selene|Xanthe','Briar|Dew|Lark|Moth|Rain|Thorn','Dawnmeadow|Greenbriar|Mooncap|Oakdance|Petalwing|Reedfoot|Summerwine|Thornvale','','Dawnsong|Greenfoot|Moon-Dancer|Piper|The Merry'),
 culture('aquatic','Aquatic Realms','triton|locathah','Corus|Delnis|Jorren|Merek|Nalos|Rellan|Taron|Vodos','Aryn|Belthyn|Doria|Miren|Nerissa|Sera|Thessia|Velyn','Coral|Pearl|Reef|Tide|Wave|Wake','Deepcurrent|Pearlguard|Reefborn|Saltcrown|Stormwake|Tidecaller|Wavecrest|Whalefriend','','Deep-Eye|Pearldiver|Stormwake|Tidecaller|Wave-Rider'),
 culture('githyanki','Githyanki','gith|githyanki','Aarvith|Dhaun|Gharvith|Kithrak|Quith|Vlaak|Xamith|Zerthimon','Alakith|Eshaal|Laez|Nashai|Qelith|Vaira|Xalith|Zerra','Gith|Kith|Voss|Xan|Zer|Zha','Astralblade|Githom|Silvercord|Tuunarath|Vlaakithar|Voidrider|Warband|Xenomar','','Silver Sword|Voidrider|The Unbound|Mindshield|Red Dragon'),
 culture('githzerai','Githzerai','githzerai','Dak|Hazar|Kith|Menyar|Nimon|Sarth|Zerth|Zhaan','Adaka|Ezhelya|Kalla|Mira|Nereth|Shakti|Yadra|Zertha','Dak|Kith|Rrakk|Saan|Zer|Zha','Adlishar|Limbohand|Mindward|Shraaktlor|Stillmind|Zerthamon|Zerthward|Zhjaeve','','Still Mind|The Centered|Chaos-Shaper|Zerth|Unbroken Thought'),
 culture('elemental','Elemental','genasi|air-genasi|earth-genasi|fire-genasi|water-genasi','Ashar|Cinder|Dhor|Gale|Marek|Rill|Sirocco|Torrent','Ember|Kora|Maris|Nerine|Opal|Raina|Terra|Zephyra','Ash|Cinder|Gale|Onyx|Rain|River','Ashfall|Cloudborn|Deepstone|Emberheart|Raincaller|Riverbend|Stormborn|Wavecrest','','Cinder|Stonehand|Storm-Eye|Whisper|Wave-Rider'),
 culture('constructed','Constructed','warforged|autognome','Bastion|Bulwark|Forge|Lancer|Sentinel|Shield|Vanguard|Warden','Aegis|Banner|Ember|Grace|Lumen|Mercy|Sable|Vigil','Anchor|Brass|Echo|Five|Iron|Journey|Seven|Wake','','','Ironhand|Old Soldier|The Last|Unbroken|Watchful','mononym','none','Constructed people use functional words, military designations, or later self-chosen names.'),
 culture('mutable','Mutable Folk','changeling|plasmoid|simic-hybrid|reborn|hexblood|dhampir','Ash|Cairn|Dusk|Echo|Morrow|Pale|Rook|Vale','Dawn|Ember|Iris|Mist|Nyx|Rain|Sable|Vesper','Blank|Change|Mirror|Nobody|Shift|Whisper','Glass|Gray|Mirror|Moon|Pale|Veil|Wax|White','','Many-Faced|Pale One|Whisper|The Returned|Unseen'),
 culture('wanderer','Wandering Peoples','aarakocra|tortle|minotaur|loxodon|vedalken|verdan|kender|thri-kreen|giff|grung|yuan-ti','Akan|Boro|Cask|Doran|Jek|Kesh|Nim|Tarek','Asha|Bela|Dori|Kira|Mara|Nesh|Tala|Veya','Cloud|Keen|Moss|Reed|Stone|Tide','Farroad|Kindred|Longstep|Openhand|Roadwise|Stonepath|Wayfarer|Windward','','Far-Wanderer|Ironhand|Quickstep|The Patient|Wayfinder'),
 culture('kalashtar','Kalashtar','kalashtar','Haru|Keshan|Melk|Rethan|Soran|Tash|Valen|Zereth','Adara|Kala|Lirra|Nari|Sava|Tana|Valara|Zhara','Ashana|Kora|Rin|Seli|Tari|Vash','Adaran|Korran|Melkash|Riedra|Shalquar|Tashana|Valesh|Zerash','','Dreamer|Mind-Eye|Quiet Voice|The Waking|Soulbound'),
];

export const HUMAN_CULTURE_IDS=['human-chondathan','human-calishite','human-damaran','human-illuskan','human-mulan','human-rashemi','human-shou','human-turami'] as const;
