import { BodyBuild,Wealth,type NPC } from '../../../../types';import type { Inventory } from '../../../items';import { calculateChallenge,proficiencyForChallenge } from '../challengeRatingEngine';import { abilityModifier,calculateArmorClass,calculateHitPoints,combatProfile,proficiencyForTier,resolveSize,resolveSpeed } from '../combatCalculator';import { resolveSavingThrows,resolveSkills } from '../skillResolver';import { resolveSpellcasting } from '../spellResolver';import { validateRules } from '../rulesValidator';import type { Ability,AbilityScores,NPCStatBlock,Sense,StatAction,StatGenerationInput,StatGenerationResult } from '../../types';
const abilities:readonly Ability[]=['strength','dexterity','constitution','intelligence','wisdom','charisma'];
const wealthLifestyle:Record<Wealth,number>={[Wealth.Destitute]:-1,[Wealth.Poor]:-1,[Wealth.Modest]:0,[Wealth.Comfortable]:0,[Wealth.Wealthy]:1,[Wealth.Rich]:1,[Wealth.VeryRich]:1,[Wealth.Opulent]:1};
export function generateStatBlock(npc:NPC,input:StatGenerationInput):StatGenerationResult{if(input.npcId!==npc.id)throw new Error('Stat request does not match the supplied NPC.');const inventory=input.inventory?.ownerNpcId===npc.id?input.inventory:null,importance=input.importance??'ordinary',scores=generateAbilities(npc),size=resolveSize(npc),trainingTier=Math.max(1,Math.min(20,1+Math.floor(npc.occupation.yearsExperience/2))),provisionalPB=proficiencyForTier(trainingTier),provisionalCombat=combatProfile(npc,scores,inventory,provisionalPB),armor=calculateArmorClass(scores,inventory),hp=calculateHitPoints(npc,scores,size,provisionalCombat.role),provisionalSpell=resolveSpellcasting(npc,scores,provisionalPB),challenge=calculateChallenge(armor.value,hp.hp,provisionalCombat,provisionalSpell?.level??0,importance),proficiencyBonus=proficiencyForChallenge(challenge.rating),combat=combatProfile(npc,scores,inventory,proficiencyBonus),spellcasting=resolveSpellcasting(npc,scores,proficiencyBonus),actions=resolveActions(npc,scores,inventory,combat.attackBonus,spellcasting?.spellSaveDC??null,input.idFactory??(()=>crypto.randomUUID())),block:NPCStatBlock={id:(input.idFactory??(()=>crypto.randomUUID()))(),npcId:npc.id,ruleset:input.ruleset??'srd-5.2.1',name:npc.name,size,type:`${npc.race} humanoid`,alignment:npc.alignment,armorClass:armor.value,armorDescription:armor.description,hitPoints:hp.hp,hitDice:hp.dice,speed:resolveSpeed(npc,inventory),abilityScores:scores,savingThrows:resolveSavingThrows(npc,scores,proficiencyBonus),skills:resolveSkills(npc,scores,proficiencyBonus),senses:resolveSenses(npc,scores),languages:npc.languages,challengeRating:challenge.rating,experiencePoints:challenge.experience,proficiencyBonus,actions,bonusActions:resolveBonusActions(npc,combat,input.idFactory??(()=>crypto.randomUUID())),reactions:resolveReactions(npc,combat,input.idFactory??(()=>crypto.randomUUID())),legendaryActions:importance==='legendary'?resolveLegendaryActions(npc,actions,input.idFactory??(()=>crypto.randomUUID())):[],spellcasting,equipment:inventory,combat,background:npc.backstory.map(chapter=>chapter.selectedResult??chapter.ending).filter(Boolean).join(' '),notes:[`${npc.occupation.yearsExperience} years of occupation-derived training.`,...(importance==='legendary'?['Legendary importance explicitly requested by the DM.']:[])],generatedAt:input.now??new Date().toISOString()},issues=validateRules(block,npc);return{statBlock:block,issues,valid:!issues.some(issue=>issue.severity==='error')};}
export function generateAbilities(npc:NPC):AbilityScores{
  const values:Record<Ability,number>={strength:10,dexterity:10,constitution:10,intelligence:10,wisdom:10,charisma:10};
  const evidence:Record<Ability,string[]>={strength:[],dexterity:[],constitution:[],intelligence:[],wisdom:[],charisma:[]};
  const job=npc.occupation.title.toLowerCase();
  const boost=(ability:Ability,amount:number,reason:string)=>{values[ability]+=amount;evidence[ability].push(reason)};
  if(/blacksmith|miner|soldier|guard|knight|labor|sailor/.test(job)){boost('strength',3,npc.occupation.title);boost('constitution',2,'Physical occupation')}
  if(/scholar|wizard|scribe|librarian|alchemist/.test(job))boost('intelligence',4,npc.occupation.title);
  if(/ranger|hunter|scout|thief|assassin|archer/.test(job)){boost('dexterity',3,npc.occupation.title);boost('wisdom',2,'Awareness training')}
  if(/noble|merchant|diplomat|performer|court/.test(job))boost('charisma',3,npc.occupation.title);
  if(/priest|cleric|druid|herbalist|mentor/.test(job))boost('wisdom',3,npc.occupation.title);
  const race=npc.race.toLowerCase();
  if(/dwarf|goliath|orc|dragonborn|bugbear/.test(race)){boost('constitution',1,`${npc.race} physical profile`);boost('strength',1,`${npc.race} physical profile`)}
  if(/elf|halfling|tabaxi|goblin/.test(race))boost('dexterity',1,`${npc.race} physical profile`);
  if([BodyBuild.Muscular,BodyBuild.Large,BodyBuild.Stocky].includes(npc.bodyBuild))boost('strength',1,npc.bodyBuild);
  const experience=Math.min(3,Math.floor(npc.occupation.yearsExperience/8));
  if(experience){const primary=highest(values);boost(primary,experience,`${npc.occupation.yearsExperience} years experience`)}
  if(wealthLifestyle[npc.wealth]<0)boost('constitution',wealthLifestyle[npc.wealth],'Resource-poor lifestyle');
  if(npc.age>60&&!/elf|dwarf|gnome/.test(race)){boost('strength',-1,'Age');boost('constitution',-1,'Age');boost('wisdom',1,'Life experience')}
  const score=(ability:Ability)=>{const value=Math.max(3,Math.min(20,values[ability]));return{ability,score:value,modifier:abilityModifier(value),evidence:evidence[ability]};};
  return{strength:score('strength'),dexterity:score('dexterity'),constitution:score('constitution'),intelligence:score('intelligence'),wisdom:score('wisdom'),charisma:score('charisma')};
}
function highest(values:Record<Ability,number>):Ability{return abilities.reduce((best,current)=>values[current]>values[best]?current:best,'strength');}
function resolveSenses(npc:NPC,scores:AbilityScores):readonly Sense[]{const result:Sense[]=[{name:'passive Perception',range:10+scores.wisdom.modifier,unit:null,evidence:['Wisdom modifier']}];if(/elf|dwarf|gnome|orc|tiefling|goblin|aasimar|dragonborn|triton|tabaxi|gith/.test(npc.race.toLowerCase()))result.push({name:'darkvision',range:60,unit:'ft.',evidence:[npc.race]});return result;}
function resolveActions(npc:NPC,scores:AbilityScores,inventory:Inventory|null,attackBonus:number,spellDC:number|null,idFactory:()=>string):readonly StatAction[]{const weapon=inventory?.entries.find(entry=>entry.equipped&&entry.item.type==='weapon')?.item,job=npc.occupation.title.toLowerCase(),actions:StatAction[]=[];if(weapon)actions.push({id:idFactory(),name:weapon.name,kind:'attack',description:`Melee or ranged attack using ${weapon.name}, if its documented form permits.`,attackBonus,damage:`1d${weapon.weight>4?8:weapon.weight>2?6:4} + ${Math.max(scores.strength.modifier,scores.dexterity.modifier)}`,saveDC:null,evidence:[weapon.name,npc.occupation.title],rulesStatus:'derived'});if(/blacksmith/.test(job))actions.push({id:idFactory(),name:'Field Repair',kind:'ability',description:'Makes a trained check to stabilize damaged nonmagical equipment using carried tools.',attackBonus:null,damage:null,saveDC:null,evidence:[npc.occupation.title,'Smithing tools'],rulesStatus:'derived'});if(/ranger|hunter/.test(job))actions.push({id:idFactory(),name:'Track Quarry',kind:'ability',description:'Makes a Wisdom (Survival) check to follow a known quarry.',attackBonus:null,damage:null,saveDC:null,evidence:[npc.occupation.title],rulesStatus:'srd'});if(/priest|cleric/.test(job))actions.push({id:idFactory(),name:'Divine Warning',kind:'social',description:'Invokes religious authority to warn or rally a creature that can understand the NPC.',attackBonus:null,damage:null,saveDC:spellDC,evidence:[npc.occupation.title,npc.religion??'Religious training'],rulesStatus:'derived'});if(spellDC)actions.push({id:idFactory(),name:'Spellcasting',kind:'spell',description:'Casts one prepared spell from the Spellcasting profile.',attackBonus:null,damage:null,saveDC:spellDC,evidence:[npc.occupation.title],rulesStatus:'srd'});if(!actions.length)actions.push({id:idFactory(),name:'Unarmed Strike',kind:'attack',description:'Melee Attack.',attackBonus:scores.strength.modifier+2,damage:`1 + ${Math.max(0,scores.strength.modifier)}`,saveDC:null,evidence:['No compatible weapon equipped'],rulesStatus:'srd'});return actions;}
function resolveBonusActions(npc:NPC,combat:ReturnType<typeof combatProfile>,idFactory:()=>string):readonly StatAction[]{return combat.role==='skirmisher'?[{id:idFactory(),name:'Reposition',kind:'ability',description:'Moves to cover as a tactical bonus action only when the encounter grants this derived NPC feature.',attackBonus:null,damage:null,saveDC:null,evidence:[npc.occupation.title,combat.style],rulesStatus:'derived'}]:[];}
function resolveReactions(npc:NPC,combat:ReturnType<typeof combatProfile>,idFactory:()=>string):readonly StatAction[]{const name=combat.role==='defender'?'Protect Ally':combat.role==='skirmisher'?'Evasive Withdrawal':combat.role==='controller'?'Arcane Defense':'Defensive Response';return[{id:idFactory(),name,kind:'ability',description:`Uses a reaction in accordance with this combat style: ${combat.style}`,attackBonus:null,damage:null,saveDC:null,evidence:[npc.occupation.title,combat.style],rulesStatus:'derived'}];}
function resolveLegendaryActions(npc:NPC,actions:readonly StatAction[],idFactory:()=>string):readonly StatAction[]{const action=actions[0];return[{...action,id:idFactory(),name:`Legendary ${action.name}`,description:`Costs 1 legendary action. ${action.description}`,evidence:[...action.evidence,'DM explicitly marked legendary importance'],rulesStatus:'derived'}];}
